Repository kubeflow/katib, pull requests merged in 2018-05, with the labels that each got.

#75 workflows.libsonnet: Fix the image name
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#83 OWNERS: Add @libbyandhelen
  OWNERS
Labels: approved, lgtm, size/XS

#81 add random forest prior to Bayesian Optimization
  README.md
  cmd/suggestion/bayesianoptimization/requirements.txt
  pkg/suggestion/bayesian_service.py
  pkg/suggestion/bayesianoptimization/src/acquisition_func/acquisition_func.py
  pkg/suggestion/bayesianoptimization/src/bayesian_optimization_algorithm.py
  pkg/suggestion/bayesianoptimization/src/global_optimizer/global_optimizer.py
  pkg/suggestion/bayesianoptimization/src/model/gp.py
  pkg/suggestion/bayesianoptimization/src/model/rf.py
  pkg/suggestion/test_client.py
Labels: approved, lgtm, size/M

#91 fix ui bug
  modeldb/frontend/public/js/models.js
Labels: approved, lgtm, size/XS

#92 fix get service-param-list bug
  pkg/db/interface.go
Labels: approved, lgtm, size/S

#94 Some fix to getting-started.md
  docs/getting-start.md
Labels: approved, lgtm, size/S

#95 save logs after check status
  pkg/manager/worker/kubernetes/kubernetes.go
Labels: approved, lgtm, size/XS

#93 Add katib-cli download command for Mac
  docs/getting-start.md
Labels: approved, lgtm, size/XS
