Repository kubeflow/katib, pull requests merged in 2018-04, with the labels that each got.

#3 add OWNERS file
  OWNERS
Labels: needs-ok-to-test, size/XS

#9 doc: Refactor
  README.md
  docs/CLI.md
  docs/developer-guide.md
  docs/getting-start.md
Labels: size/XL

#10 Rename packages and move dlk dir
  build.sh
  cli/Dockerfile
  cli/main.go
  db/interface.go
  db/interface_test.go
  db/test/test.go
  dlk/.gitignore
  dlk/Dockerfile
  dlk/dlkctl/.gitignore
  dlk/dlkctl/bash-cmp.go
  dlk/dlkctl/del-lt.go
  dlk/dlkctl/del.go
  dlk/dlkctl/dlkctl.go
  dlk/dlkctl/get-lt.go
  dlk/dlkctl/get-lts.go
  dlk/dlkctl/get.go
  dlk/dlkctl/logs.go
  dlk/dlkctl/root.go
  dlk/dlkctl/run.go
  dlk/dlkctl/utils/dockerUtils.go
  dlk/dlkctl/utils/flagUtils.go
  dlk/dlkctl/version.go
  dlk/dlkmanager/.gitignore
  dlk/dlkmanager/api/api.go
  dlk/dlkmanager/bash-cmp.go
  dlk/dlkmanager/client.go
  dlk/dlkmanager/configs/flags.go
  dlk/dlkmanager/datastore/dataStoreMap.go
  dlk/dlkmanager/datastore/learningTaskData.go
  dlk/dlkmanager/delete.go
  dlk/dlkmanager/dlkmanager.go
  dlk/dlkmanager/get.go
  dlk/dlkmanager/jobs.go
  dlk/dlkmanager/learningTask.go
  dlk/dlkmanager/post.go
  dlk/dlkmanager/put.go
  dlk/dlkmanager/services.go
  earlystopping/earlyStoppingService.go
  manager/Dockerfile
  manager/main.go
  manager/visualise/tensorboard/tensorboardIF.go
  manager/worker_interface/dlk/dlk.go
  manager/worker_interface/kubernetes/kubernetes.go
  manager/worker_interface/nvdocker/nvidia-docker.go
  manager/worker_interface/worker_interface.go
  suggestion/grid/Dockerfile
  suggestion/grid/main.go
  suggestion/hyperband/Dockerfile
  suggestion/hyperband/hyperband.go
  suggestion/hyperband/main.go
  suggestion/random/Dockerfile
  suggestion/random/main.go
  suggestion/suggestService.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#11 ignore: Add macOS, Windows and Go ignore files
  .gitignore
Labels: approved, lgtm, size/M

#13 Fixing some basic typos in README
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#17 README: Add code quality badge
  README.md
Labels: approved, lgtm, size/XS

#21 suggestion: Refactor
  suggestion/grid/main.go
  suggestion/grid_service.go
  suggestion/hyperband/main.go
  suggestion/hyperband_service.go
  suggestion/random/main.go
  suggestion/random_service.go
  suggestion/types.go
Labels: approved, lgtm, size/L

#22 Ci setup
  api/api.pb.go
  api/api.proto
  cli/main.go
  db/interface_test.go
  manager/main.go
  manager/main_test.go
  mock/mock_api/manager_mock.go
  mock/mock_api/suggestion_mock.go
  mock/mock_db/db_mock.go
  mock/mock_worker_interface/worker_interface_mock.go
  test/script/build.sh
  test/script/create-cluster.sh
  test/script/delete-cluster.sh
  test/script/run-tests.sh
  test/workflows/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/releasing/.metadata/k.libsonnet
  test/workflows/environments/releasing/.metadata/k8s.libsonnet
  test/workflows/environments/releasing/.metadata/swagger.json
  test/workflows/environments/releasing/main.jsonnet
  test/workflows/environments/releasing/params.libsonnet
  test/workflows/environments/test/.metadata/k.libsonnet
  test/workflows/environments/test/.metadata/k8s.libsonnet
  test/workflows/environments/test/.metadata/swagger.json
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#23 Dockerfile: Use multiple stage builds
  docs/developer-guide.md
  manifests/vizier/suggestion/grid/deployment.yaml
  manifests/vizier/suggestion/hyperband/deployment.yaml
  manifests/vizier/suggestion/random/deployment.yaml
  suggestion/grid/Dockerfile
  suggestion/hyperband/Dockerfile
  suggestion/random/Dockerfile
Labels: approved, lgtm, size/M

#28 Dockerfile: Support multiple stage build in dlk and frontend
  dlk/Dockerfile
  manager/modeldb/Dockerfile
Labels: approved, lgtm, size/L

#25 Dockerfile: Support multiple stage build in manager and cli
  build.sh
  cli/Dockerfile
  docs/getting-start.md
  manager/Dockerfile
  manifests/vizier/core/deployment.yaml
Labels: approved, lgtm, size/M

#30 cleanup of README
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#29 delete unnecessary settings
  manifests/dlk/deployment.yaml
  manifests/vizier/suggestion/random/deployment.yaml
Labels: lgtm, size/XS

#35 New db log schema
  db/db_init.go
  db/interface.go
  manager/Dockerfile
  manager/main.go
  manager/visualise/tensorboard/tensorboardIF.go
  manager/worker_interface/dlk/dlk.go
  manager/worker_interface/kubernetes/kubernetes.go
  manager/worker_interface/nvdocker/nvidia-docker.go
  manager/worker_interface/worker_interface.go
  suggestion/hyperband_service.go
Labels: lgtm, size/L

#36 docs: Update katib-cli
  docs/getting-start.md
Labels: approved, lgtm, size/S

#37 Dockerfile: Use alpine as base image
  cli/Dockerfile
Labels: approved, lgtm, size/XS

#27 Fix CI failures
  prow_config.yaml
  test/scripts/build.sh
  test/scripts/create-cluster.sh
  test/scripts/delete-cluster.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/S

#45 reviewers: Add @ddysher @jose5918 @mitake
  OWNERS
Labels: approved, lgtm, size/XS

#38 bayesian optimization draft
  .gitignore
  api/python/api_pb2.py
  api/python/api_pb2_grpc.py
  manifests/vizier/suggestion/bayesianoptimization/deployment.yaml
  manifests/vizier/suggestion/bayesianoptimization/service.yaml
  suggestion/bayesian_service.py
  suggestion/bayesianoptimization/Dockerfile
  suggestion/bayesianoptimization/README.md
  suggestion/bayesianoptimization/__init__.py
  suggestion/bayesianoptimization/main.py
  suggestion/bayesianoptimization/requirements.txt
  suggestion/bayesianoptimization/src/__init__.py
  suggestion/bayesianoptimization/src/acquisition_func/__init__.py
  suggestion/bayesianoptimization/src/acquisition_func/acquisition_func.py
  suggestion/bayesianoptimization/src/algorithm_manager.py
  suggestion/bayesianoptimization/src/bayesian_optimization_algorithm.py
  suggestion/bayesianoptimization/src/global_optimizer/__init__.py
  suggestion/bayesianoptimization/src/global_optimizer/global_optimizer.py
  suggestion/bayesianoptimization/src/model/Model.py
  suggestion/bayesianoptimization/src/model/__init__.py
  suggestion/test_client.py
  suggestion/test_func.py
  suggestion/types.py
  test/scripts/build.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/XXL

#49 improve test script
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/XS

#51 refactor Model API
  api/api.pb.go
  api/api.proto
  manager/main.go
  manager/modelstore/modeldb.go
  manager/modelstore/modelstore.go
Labels: approved, lgtm, size/XL

#52 Fix modelsave
  dlk/dlkmanager/learningTask.go
  manager/main.go
  manager/modelstore/modeldb.go
Labels: approved, lgtm, size/M

#55 main.go: Fix style
  manager/main.go
Labels: approved, size/M

#56 argo: Add unit test
  db/interface_test.go
  manager/main_test.go
  mock/api/manager.go
  mock/api/suggestion.go
  mock/db/db.go
  mock/modelstore/modelstore.go
  mock/worker/worker.go
  scripts/mockgen.sh
  test/scripts/build.sh
  test/scripts/unit-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#61 Replace kubeflow-images-staging with kubeflow-images-public
  test/workflows/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/XS

#60 improve frontend
  manager/main.go
  manager/modelstore/modeldb.go
  manager/visualise/tensorboard/tensorboardIF.go
  manifests/vizier/core/deployment.yaml
  modeldb/frontend/public/css/models.css
  modeldb/frontend/public/js/lib/d3.v5.min.js
  modeldb/frontend/public/js/model.js
  modeldb/frontend/public/js/models.js
  modeldb/frontend/views/models.ejs
  suggestion/hyperband_service.go
  suggestion/random_service.go
Labels: approved, lgtm, size/XL

#64 *: Update name
  README.md
  cli/Dockerfile
  cli/main.go
  db/interface.go
  db/interface_test.go
  db/test/test.go
  dlk/Dockerfile
  dlk/dlkctl/del-lt.go
  dlk/dlkctl/get-lt.go
  dlk/dlkctl/get-lts.go
  dlk/dlkctl/logs.go
  dlk/dlkctl/run.go
  dlk/dlkmanager/delete.go
  dlk/dlkmanager/dlkmanager.go
  dlk/dlkmanager/get.go
  dlk/dlkmanager/learningTask.go
  dlk/dlkmanager/post.go
  docs/getting-start.md
  earlystopping/medianstopping.go
  earlystopping/medianstopping/Dockerfile
  earlystopping/medianstopping/main.go
  earlystopping/types.go
  manager/Dockerfile
  manager/main.go
  manager/main_test.go
  manager/modelstore/modeldb.go
  manager/modelstore/modeldb/model_d_b_service-remote/model_d_b_service-remote.go
  manager/modelstore/modelstore.go
  manager/visualise/tensorboard/tensorboardIF.go
  manager/worker_interface/dlk/dlk.go
  manager/worker_interface/kubernetes/kubernetes.go
  manager/worker_interface/nvdocker/nvidia-docker.go
  manager/worker_interface/worker_interface.go
  mock/api/manager.go
  mock/api/suggestion.go
  mock/db/db.go
  mock/modelstore/modelstore.go
  mock/worker/worker.go
  prow_config.yaml
  scripts/mockgen.sh
  suggestion/bayesianoptimization/Dockerfile
  suggestion/grid/Dockerfile
  suggestion/grid/main.go
  suggestion/grid_service.go
  suggestion/hyperband/Dockerfile
  suggestion/hyperband/main.go
  suggestion/hyperband_service.go
  suggestion/random/Dockerfile
  suggestion/random/main.go
  suggestion/random_service.go
  suggestion/types.go
  test/scripts/build.sh
  test/workflows/components/workflows.libsonnet
Labels: do-not-merge/hold, size/L

#69 Cobra cli
  cmd/cli/create-study.go
  cmd/cli/create.go
  cmd/cli/get-model.go
  cmd/cli/get-study.go
  cmd/cli/get.go
  cmd/cli/katibctl.go
  cmd/cli/main.go
  cmd/cli/push-model.go
  cmd/cli/push-study.go
  cmd/cli/push.go
  cmd/cli/root.go
  cmd/cli/stop-study.go
  cmd/cli/stop.go
  cmd/manager/main.go
  cmd/manager/main_test.go
  docs/CLI.md
  pkg/api/api.pb.go
  pkg/api/api.proto
  pkg/earlystopping/medianstopping.go
  pkg/manager/modelstore/modeldb.go
  pkg/manager/visualise/tensorboard/tensorboardIF.go
Labels: approved, lgtm, size/XXL

#70 worker: Rename worker_interface to worker
  cmd/manager/main.go
  cmd/manager/main_test.go
  pkg/manager/worker/dlk/dlk.go
  pkg/manager/worker/interface.go
  pkg/manager/worker/kubernetes/kubernetes.go
  pkg/manager/worker/nvdocker/nvidia-docker.go
  pkg/mock/worker/worker.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/L
