Repository kubeflow/katib, pull requests merged in 2018-09, with the labels that each got.

#159 StudyJobController: Update worker status and fix status bug
  cmd/manager/main.go
  pkg/api/api.pb.go
  pkg/api/api.proto
  pkg/api/python/api_pb2.py
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XL

#142 Add REST API using grpc gateway
  Gopkg.lock
  Gopkg.toml
  cmd/manager-rest/Dockerfile
  cmd/manager-rest/proxy.go
  docs/rest-api.md
  manifests/vizier/core-rest/deployment.yaml
  manifests/vizier/core-rest/ingress.yaml_
  manifests/vizier/core-rest/service.yaml
  pkg/api/api.pb.go
  pkg/api/api.pb.gw.go
  pkg/api/api.proto
  pkg/api/api.swagger.json
  pkg/api/build.sh
  pkg/api/python/api_pb2.py
  scripts/build.sh
  scripts/deploy.sh
  test/scripts/build-manager-rest.sh
  test/scripts/run-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#174 Define workflows to build the study job CRD and metrics collector images
  docs/developer-guide.md
  prow_config.yaml
  releasing/releaser/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  releasing/releaser/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  releasing/releaser/app.yaml
  releasing/releaser/components/params.libsonnet
  releasing/releaser/components/workflows.jsonnet
  releasing/releaser/components/workflows.libsonnet
  releasing/releaser/environments/base.libsonnet
  releasing/releaser/environments/prow/.metadata/k.libsonnet
  releasing/releaser/environments/prow/.metadata/k8s.libsonnet
  releasing/releaser/environments/prow/.metadata/swagger.json
  releasing/releaser/environments/prow/main.jsonnet
  releasing/releaser/environments/prow/params.libsonnet
  releasing/releaser/environments/releasing/.metadata/k.libsonnet
  releasing/releaser/environments/releasing/.metadata/k8s.libsonnet
  releasing/releaser/environments/releasing/.metadata/swagger.json
  releasing/releaser/environments/releasing/main.jsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  releasing/releaser/lib/v1.7.0/k.libsonnet
  releasing/releaser/lib/v1.7.0/k8s.libsonnet
  releasing/releaser/lib/v1.7.0/swagger.json
  releasing/releaser/scripts/build_image.sh
  test/workflows/.ksonnet/registries/kubeflow/61c7da4756c8ba149637bf4a9e1805258fbead96.yaml
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
Labels: approved, lgtm, size/XXL

#177 Fix jsonnet so we override registry in image builds.
  prow_config.yaml
  releasing/cron_job_release.yaml
  releasing/prow_config_release.yaml
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/L

#185 Update `checkStatus` return value orders
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/M
