Repository kubeflow/katib, pull requests merged in 2018-11, with the labels that each got.

#229 Only retry an INSERT operation on unique constraint violation
  pkg/db/interface.go
Labels: approved, lgtm, size/M

#231 Fix the build script after #208
  scripts/build.sh
Labels: approved, lgtm, size/XS

#234 More DB unit tests
  pkg/db/interface.go
  pkg/db/interface_test.go
Labels: approved, lgtm, size/L

#233 Fix typo
  cmd/cli/command/push-model.go
  cmd/cli/command/push-study.go
  pkg/earlystopping/medianstopping.go
  pkg/suggestion/grid_service.go
  pkg/suggestion/hyperband_service.go
  pkg/suggestion/random_service.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#236 add starttime and completiontime to worker
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/S

#239 Add richardsliu to OWNERS/reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#242 Fix typos for json and objective
  examples/MinikubeDemo.md
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
  pkg/api/operators/apis/studyjob/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, ok-to-test, size/M

#247 Add texasmichelle as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#243 Add mysql based unit tests
  pkg/db/interface_test.go
  test/scripts/unit-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/L

#252 Change deploy.sh for Minikube example
  examples/MinikubeDemo.md
  examples/MinikubeDemo/deploy.sh
Labels: approved, lgtm, size/XS

#254 Refactor studyjobcontroller
  pkg/controller/add_studyjobcontroller.go
  pkg/controller/studyjob/katib_api_util.go
  pkg/controller/studyjob/manifest_parser.go
  pkg/controller/studyjob/model_util.go
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/XL

#255 update UI
  README.md
  cmd/ui/template/index.html
  cmd/ui/template/parallelcood.js
  cmd/ui/template/study.html
  cmd/ui/template/trial.html
  cmd/ui/template/worker.html
  pkg/ui/ui.go
Labels: approved, lgtm, size/L

#253 Set MYSQL_ROOT_PASSWORD via Secret
  manifests/vizier/core/deployment.yaml
  manifests/vizier/db/deployment.yaml
  manifests/vizier/db/secret.yaml
  pkg/db/interface.go
  test/scripts/run-tests.sh
Labels: approved, lgtm, ok-to-test, size/M

#260 Fix incorrectly set namespace
  manifests/vizier/db/secret.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#256 Downgrade kubernetes dependency to 1.10.1
  Gopkg.lock
  Gopkg.toml
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
  pkg/controller/studyjob/pod_control.go
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/L

#237 add UT of each suggestion algorithm
  pkg/suggestion/grid_service_test.go
  pkg/suggestion/hyperband_service_test.go
  pkg/suggestion/random_service_test.go
Labels: approved, lgtm, size/XL

#261 Prevent pod restarts caused by slow db boot
  manifests/vizier/db/deployment.yaml
  manifests/vizier/db/secret.yaml
  pkg/db/interface.go
  pkg/db/interface_test.go
Labels: approved, lgtm, ok-to-test, size/M
