Repository kubeflow/katib, pull requests merged in 2018-10, with the labels that each got.

#178 Add pv example to katibDB
  examples/MinikubeDemo/deploy.sh
  manifests/pv/pv.yaml
  manifests/pv/pvc.yaml
  manifests/vizier/db/deployment.yaml
  scripts/deploy.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/M

#176 Add Retain flag
  Gopkg.lock
  Gopkg.toml
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XL

#171 fix-MinikubeDemodox
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/XS

#181 fix random-example
  examples/random-example.yaml
Labels: approved, lgtm, size/XS

#189 Add Katib logo
  README.md
  img/Katib_Logo.png
Labels: approved, lgtm, size/XS

#194 Fix CI
  scripts/deploy.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/S

#190 add building metrics-collector to CI
  test/scripts/build-studyjobctr.sh
Labels: approved, lgtm, size/XS

#193 support request count
  examples/random-example.yaml
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XS

#201 Fix deadlock condition in ReconcileStudyJobController#Reconcile
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XS

#188 Bayesian Suggestion Algorithm Fixes
  cmd/suggestion/bayesianoptimization/Dockerfile
  cmd/suggestion/bayesianoptimization/requirements.txt
  pkg/api/build.sh
  pkg/api/python/api_pb2.py
  pkg/api/python/api_pb2_grpc.py
  scripts/deploy.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/XXL

#191 Fix CRD validation
  manifests/studyjobcontroller/crd.yaml
Labels: approved, lgtm, size/XS

#202 Point to the example version of ConfigMap from MinikubeDemo.md
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/XS

#213 fix manifest examples
  examples/random-example.yaml
  examples/workerConfigMap.yaml
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/studyjobcontroller/workerConfigMap.yaml
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/M

#200 enlarge max of check status grpc
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XS

#219 Check errors in order to avoid SEGV
  pkg/controller/studyjobcontroller/studyjob_controller.go
Labels: approved, lgtm, size/XS

#222 Fix storelogs
  pkg/db/db_init.go
  pkg/db/interface.go
Labels: approved, lgtm, size/L

#226 fix slice range
  pkg/suggestion/hyperband_service.go
Labels: approved, lgtm, size/XS
