Repository kubeflow/katib, pull requests merged in 2018-12, with the labels that each got.

#238 fix uncompleted value in ui
  pkg/ui/ui.go
Labels: approved, lgtm, size/XS

#274 add Richard Liu to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#269 Add Update{Study,Trial}
  pkg/db/interface.go
  pkg/db/interface_test.go
  pkg/mock/db/db.go
Labels: approved, lgtm, ok-to-test, size/L

#271 fix timing to determine slice size in grid search
  pkg/suggestion/grid_service.go
Labels: approved, lgtm, ok-to-test, size/XS

#267 POC: Katib integration with tf-operator
  Gopkg.lock
  Gopkg.toml
  examples/tfjob-example.yaml
  manifests/studyjobcontroller/rbac.yaml
  manifests/studyjobcontroller/tfjobsCrd.yaml
  pkg/api/operators/apis/addtoscheme_tfjob_v1beta1.go
  pkg/controller/studyjob/const.go
  pkg/controller/studyjob/studyjob_controller.go
  scripts/deploy.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/L

#270 Implement gRPC Health Checking Protocol + add readiness/liveness probes to vizier-core
  cmd/manager/Dockerfile
  cmd/manager/main.go
  manifests/vizier/core/deployment.yaml
  pkg/api/Makefile
  pkg/api/build.sh
  pkg/api/health/health.pb.go
  pkg/api/health/health.proto
  pkg/api/health/health.swagger.json
  pkg/api/python/health/health_pb2.py
  pkg/api/python/health/health_pb2_grpc.py
  pkg/db/db_init.go
  pkg/db/interface.go
  pkg/db/interface_test.go
  pkg/db/test/test.go
  pkg/earlystopping/medianstopping.go
  pkg/mock/db/db.go
Labels: approved, lgtm, ok-to-test, size/XL

#277 Fix katib ui resource paths
  cmd/ui/Dockerfile
  cmd/ui/main.go
  cmd/ui/template/layout.html
  cmd/ui/template/study.html
  cmd/ui/template/worker.html
  pkg/ui/ui.go
Labels: approved, lgtm, size/S

#278 Allow studyjobcontroller to delete pods
  manifests/studyjobcontroller/rbac.yaml
Labels: approved, lgtm, size/XS

#265 add e2eTest of each suggestion algorithm
  test/e2e/test-client.go
Labels: approved, lgtm, ok-to-test, size/L

#280 fix typo error
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/S

#282 fix typo error for MinikubeDemo
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/M

#281 update README
  README.md
Labels: approved, lgtm, size/M

#286 Update k8s cluster version to 1.10
  test/scripts/create-cluster.sh
Labels: approved, lgtm, size/XS

#283 Support Pytorch job in Katib
  Gopkg.lock
  Gopkg.toml
  cmd/metricscollector/main.go
  examples/pytorchjob-example.yaml
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/studyjobcontroller/pytorchjobsCrd.yaml
  manifests/studyjobcontroller/rbac.yaml
  pkg/api/operators/apis/addtoscheme_pytorchjob_v1beta1.go
  pkg/controller/studyjob/const.go
  pkg/controller/studyjob/manifest_parser.go
  pkg/controller/studyjob/studyjob_controller.go
  pkg/manager/metricscollector/meticscollector.go
  scripts/deploy.sh
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/L

#292 get metricscollector by API
  pkg/controller/studyjob/manifest_parser.go
Labels: approved, lgtm, size/S

#287 fix invalid worker kind issue
  pkg/controller/studyjob/const.go
  pkg/controller/studyjob/manifest_parser.go
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/S

#290 fix studyJob status suggestionCount mismatch error
  pkg/controller/studyjob/katib_api_util.go
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/XS

#295 update Readme
  README.md
Labels: approved, lgtm, size/XS

#284 Use same deploy.sh when deploy katib components
  examples/MinikubeDemo/deploy.sh
Labels: approved, lgtm, ok-to-test, size/S

#288 Extend studyjob client API
  pkg/manager/studyjobclient/studyjobclient.go
Labels: approved, lgtm, size/M

#300 Adding master pod check for default metric collector
  pkg/manager/metricscollector/meticscollector.go
Labels: approved, lgtm, size/S

#302 studyJob with non-kubeflow namespace cannot work
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/studyjobcontroller/workerConfigMap.yaml
  pkg/controller/studyjob/manifest_parser.go
  pkg/controller/studyjob/studyjob_controller.go
  pkg/types.go
Labels: approved, lgtm, size/S

#299 sync up worker status all the time
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/M

#304 Adding to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#310 add hougangliu as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#308 validate studyJob when first reconcile it
  Gopkg.lock
  pkg/controller/studyjob/katib_api_util.go
  pkg/controller/studyjob/manifest_parser.go
  pkg/controller/studyjob/utils.go
Labels: approved, lgtm, size/M
