Repository kubeflow/katib, pull requests merged in 2018-06, with the labels that each got.

#98 Fix dbbug
  pkg/db/interface.go
Labels: approved, lgtm, size/XS

#101 cli: Rename to katib-cli
  cmd/cli/root.go
  docs/CLI.md
Labels: approved, lgtm, size/S

#104 changelog: Add
  CHANGELOG.md
Labels: approved, lgtm, size/L

#105 docs: Generate CLI documentation
  .gitignore
  README.md
  cmd/cli/command/create-study.go
  cmd/cli/command/create.go
  cmd/cli/command/get-model.go
  cmd/cli/command/get-study.go
  cmd/cli/command/get.go
  cmd/cli/command/pull-study.go
  cmd/cli/command/pull.go
  cmd/cli/command/push-model.go
  cmd/cli/command/push-study.go
  cmd/cli/command/push.go
  cmd/cli/command/root.go
  cmd/cli/command/stop-study.go
  cmd/cli/command/stop.go
  cmd/cli/command/type.go
  cmd/cli/create.go
  cmd/cli/get.go
  cmd/cli/katibctl.go
  cmd/cli/pull.go
  cmd/cli/push.go
  cmd/cli/stop.go
  cmd/cli/type.go
  docs/CLI.md
  docs/CLI/katib-cli.md
  docs/CLI/katib-cli_create.md
  docs/CLI/katib-cli_create_study.md
  docs/CLI/katib-cli_get.md
  docs/CLI/katib-cli_get_model.md
  docs/CLI/katib-cli_get_studies.md
  docs/CLI/katib-cli_pull.md
  docs/CLI/katib-cli_pull_studies.md
  docs/CLI/katib-cli_push.md
  docs/CLI/katib-cli_push_study.md
  docs/CLI/katib-cli_stop.md
  docs/CLI/katib-cli_stop_study.md
  hack/docgen.go
  hack/gen-doc.sh
Labels: approved, lgtm, size/XL

#107 Remove dlk from manifests
  manifests/dlk/deployment.yaml
  manifests/dlk/rbac.yaml
  manifests/dlk/service.yaml
  manifests/vizier/core/deployment.yaml
Labels: approved, lgtm, size/M

#108 docs: Fix wrong command
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/XS

#111 use kubectl port-forward in demos
  examples/GKEDemo/GKE-Demo.md
  examples/GKEDemo/deploy.sh
  examples/GKEDemo/destroy.sh
  examples/GKEDemo/manifests/modeldb/frontend/service.yaml
  examples/GKEDemo/manifests/vizier/core/service.yaml
  examples/MinikubeDemo.md
  examples/MinikubeDemo/destroy.sh
  examples/MinikubeDemo/manifests/modeldb/frontend/service.yaml
  examples/MinikubeDemo/manifests/vizier/core/service.yaml
Labels: approved, lgtm, size/M

#110 API: Add WorkerStatus to GetMetrics and remove unused items
  cmd/manager/main.go
  examples/GKEDemo/git-issue-summarize-demo.go
  examples/client-example.go
  examples/study-config.yml
  pkg/api/api.pb.go
  pkg/api/api.proto
  pkg/api/build.sh
  pkg/api/python/api_pb2.py
  pkg/db/db_init.go
  pkg/db/interface.go
  pkg/db/interface_test.go
  pkg/suggestion/grid_service.go
  pkg/suggestion/random_service.go
Labels: approved, lgtm, size/XXL

#113 add releasing workflow
  releasing/cron_job_release.yaml
  releasing/prow_config_release.yaml
  releasing/releaser/.ksonnet/registries/incubator/ea3408d44c2d8ea4d321364e5533d5c60e74bce0.yaml
  releasing/releaser/.ksonnet/registries/kubeflow/5c35580d76092788b089cb447be3f3097cffe60b.yaml
  releasing/releaser/app.yaml
  releasing/releaser/components/params.libsonnet
  releasing/releaser/components/workflows.jsonnet
  releasing/releaser/components/workflows.libsonnet
  releasing/releaser/environments/base.libsonnet
  releasing/releaser/environments/prow/.metadata/k.libsonnet
  releasing/releaser/environments/prow/.metadata/k8s.libsonnet
  releasing/releaser/environments/prow/.metadata/swagger.json
  releasing/releaser/environments/prow/main.jsonnet
  releasing/releaser/environments/prow/params.libsonnet
  releasing/releaser/environments/releasing/.metadata/k.libsonnet
  releasing/releaser/environments/releasing/.metadata/k8s.libsonnet
  releasing/releaser/environments/releasing/.metadata/swagger.json
  releasing/releaser/environments/releasing/main.jsonnet
  releasing/releaser/environments/releasing/params.libsonnet
  releasing/releaser/lib/v1.7.0/k.libsonnet
  releasing/releaser/lib/v1.7.0/k8s.libsonnet
  releasing/releaser/lib/v1.7.0/swagger.json
  releasing/releaser/scripts/build_image.sh
Labels: approved, lgtm, size/XXL

#121 Fix indentation to use spaces (instead of a mix of tabs and spaces)
  pkg/api/api.proto
Labels: approved, lgtm, size/M

#123 Fix typo
  cmd/cli/command/get-model.go
Labels: approved, lgtm, size/XS

#120 fix doc link and kubectl port-forward command
  docs/images/SystemFlow.png
  examples/MinikubeDemo.md
Labels: approved, lgtm, size/XS

#129 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#127 Update status of workers in GetWorkers
  cmd/manager/main.go
  pkg/manager/worker/kubernetes/kubernetes.go
  pkg/suggestion/hyperband_service.go
  test/e2e/test-client.go
Labels: approved, lgtm, size/M
