Repository kubeflow/katib, pull requests merged in 2019-09, with the labels that each got.

#732 Add a metrics collector proposal
  docs/images/metrics-collector-design.png
  docs/proposals/metrics-collector.md
Labels: approved, lgtm, size/L

#738 MetricsCollector pod injection for katib job
  pkg/webhook/v1alpha2/pod/const.go
  pkg/webhook/v1alpha2/pod/inject_webhook.go
  pkg/webhook/v1alpha2/pod/utils.go
Labels: approved, lgtm, size/L

#741 Adding extra timeouts to builds
  test/scripts/v1alpha2/build-tc-nasrl-cifar10.sh
  test/scripts/v1alpha2/build-ui.sh
  test/scripts/v1alpha3/build-tc-nasrl-cifar10.sh
  test/scripts/v1alpha3/build-ui.sh
Labels: approved, lgtm, size/XS

#740 feat(apis): Add suggestion CRD API
  pkg/apis/controller/addtoscheme_katib_v1alpha3.go
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/common/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/suggestions/group.go
  pkg/apis/controller/suggestions/v1alpha3/doc.go
  pkg/apis/controller/suggestions/v1alpha3/register.go
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
  pkg/apis/controller/suggestions/v1alpha3/zz_generated.deepcopy.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/XL

#745 Inject sidecar container based on metrics collector kind
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/common/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1alpha2/experiment_types.go
  pkg/apis/controller/experiments/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1alpha3/constants.go
  pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1alpha3/trial_types.go
  pkg/apis/controller/trials/v1alpha3/zz_generated.deepcopy.go
  pkg/controller.v1alpha2/experiment/experiment_util.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/webhook/v1alpha2/pod/inject_webhook.go
  pkg/webhook/v1alpha2/webhook.go
  pkg/webhook/v1alpha3/pod/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/pod/utils.go
Labels: approved, lgtm, size/XL

#742 feat: Add suggestion controller
  manifests/v1alpha3/katib-controller/crd-suggestion.yaml
  manifests/v1alpha3/katib-controller/rbac.yaml
  pkg/controller.v1alpha3/add_suggestion.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_suite_test.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_util.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1alpha3/util/help.go
  test/scripts/v1alpha2/run-tests.sh
  test/scripts/v1alpha3/run-tests.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XL

#747 Ignore injecting sidecar for none collector kind
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/S

#749 Experiment webhook for metricsCollector
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/L

#750 Adding suggestion reconcile in Experiment controller
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
  pkg/apis/controller/suggestions/v1alpha3/zz_generated.deepcopy.go
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/controller.v1alpha3/experiment/manifest/generator_test.go
  pkg/controller.v1alpha3/experiment/suggestion/fake/fake.go
  pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/util/labels.go
  pkg/db/v1alpha3/db_init.go
  pkg/mock/v1alpha3/experiment/manifest/generator.go
  pkg/mock/v1alpha3/experiment/suggestion/suggestion.go
  test/scripts/v1alpha3/run-tests.sh
  test/workflows/components/workflows-v1alpha2.libsonnet
Labels: approved, lgtm, size/L

#752 Fix v1alpha3 paths in prow
  prow_config.yaml
Labels: approved, lgtm, size/M

#751 Populate Parameter assignments in trials
  pkg/controller.v1alpha3/experiment/experiment_util.go
Labels: approved, lgtm, size/XS

#754 Adding suggestion images to configmap
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/apis/controller/experiments/v1alpha3/constants.go
  pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/L

#756 Removing backup db password
  pkg/db/v1alpha3/interface.go
Labels: approved, lgtm, size/XS

#743 feat(GRPC): Update API for Suggestion
  cmd/manager/v1alpha3/main.go
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
  test/e2e/v1alpha3/test-katib-manager.py
  test/scripts/v1alpha3/run-tests.sh
Labels: approved, lgtm, size/XL

#758 Metrics collector exit when worker container done
  Gopkg.lock
  cmd/metricscollector/v1alpha3/Dockerfile
  cmd/metricscollector/v1alpha3/file-metricscollector/Dockerfile
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  cmd/metricscollector/v1alpha3/main.go
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  cmd/sidecar-metricscollector/v1alpha2/Dockerfile
  cmd/sidecar-metricscollector/v1alpha3/Dockerfile
  cmd/sidecar-metricscollector/v1alpha3/main.go
  pkg/metricscollector/v1alpha3/common/const.go
  pkg/metricscollector/v1alpha3/common/pns.go
  pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
  pkg/util/v1alpha3/sidecarmetricscollector/sidecarmetricscollector.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  prow_config.yaml
  scripts/v1alpha2/build.sh
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha2/build-katib-controller.sh
  test/scripts/v1alpha3/build-katib-controller.sh
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/inotify/LICENSE
  vendor/k8s.io/utils/inotify/PATENTS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/third_party/forked/golang/PATENTS
Labels: approved, lgtm, size/XXL

#760 Refactor DB interface
  cmd/manager/v1alpha3/main.go
  manifests/v1alpha3/manager/deployment.yaml
  pkg/db/v1alpha3/common/const.go
  pkg/db/v1alpha3/common/kdb.go
  pkg/db/v1alpha3/db.go
  pkg/db/v1alpha3/mysql/init.go
  pkg/db/v1alpha3/mysql/mysql.go
  pkg/db/v1alpha3/mysql/mysql_test.go
  pkg/mock/v1alpha3/db/db.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/L

#753 feat: Support HyperOpt
  cmd/suggestion/hyperopt/v1alpha3/Dockerfile
  cmd/suggestion/hyperopt/v1alpha3/__init__.py
  cmd/suggestion/hyperopt/v1alpha3/main.py
  cmd/suggestion/hyperopt/v1alpha3/requirements.txt
  examples/v1alpha3/hyperopt-random-example.yaml
  examples/v1alpha3/hyperopt-tpe-example.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/managerclient/managerclient.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1alpha3/trial/managerclient/managerclient.go
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/search_space.py
  pkg/suggestion/v1alpha3/internal/trial.py
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha3/build-suggestion-hyperopt.sh
  test/scripts/v1alpha3/run-tests.sh
  test/suggestion/v1alpha3/test_hyperopt_service.py
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XXL

#761 Remove old version metrics collector
  cmd/ui/v1alpha3/main.go
  examples/v1alpha3/bayseopt-example.yaml
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/hyperband-example.yaml
  examples/v1alpha3/hyperopt-random-example.yaml
  examples/v1alpha3/hyperopt-tpe-example.yaml
  examples/v1alpha3/pytorchjob-example.yaml
  examples/v1alpha3/random-example.yaml
  manifests/v1alpha3/0-namespace.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  manifests/v1alpha3/katib-controller/metricsControllerConfigMap.yaml
  pkg/apis/controller/experiments/v1alpha3/constants.go
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1alpha3/trial_types.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/controller.v1alpha3/experiment/manifest/generator_test.go
  pkg/controller.v1alpha3/trial/managerclient/managerclient.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/util.go
  pkg/util/v1alpha3/katibclient/katib_client.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  test/scripts/v1alpha3/run-tests.sh
Labels: approved, lgtm, size/XL

#765 Remove old metricscollector source code
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile
  pkg/metricscollector/v1alpha3/tfevent-metricscollector/__init__.py
  pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py
  pkg/util/v1alpha3/metricscollector/metricscollector.go
  scripts/v1alpha3/build.sh
Labels: approved, lgtm, size/L

#766 feat: Enable python test
  pkg/suggestion/v1alpha3/grid_service_test.py
  test/scripts/v1alpha3/python-tests.sh
  test/suggestion/v1alpha3/test_hyperopt_service.py
  test/suggestion/v1alpha3/test_requirements.txt
Labels: approved, lgtm, size/L

#767 feat(GRPC): Replace trial with assignment
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/trial.py
  test/suggestion/v1alpha3/test_hyperopt_service.py
Labels: approved, lgtm, size/XL

#770 Adding status conditions for Suggestion CRD
  cmd/manager/v1alpha3/main.go
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
  pkg/apis/controller/suggestions/v1alpha3/util.go
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/managerclient/managerclient.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/mock/v1alpha3/experiment/managerclient/managerclient.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/XL

#773 Marking experiment failed when suggestion fails
  pkg/controller.v1alpha3/experiment/experiment_controller.go
Labels: approved, lgtm, size/S

#772 Removing suggestions from manager interface
  cmd/manager/v1alpha3/main.go
  manifests/v1alpha3/katib-controller/katib-config.yaml
  manifests/v1alpha3/suggestion/bayesianoptimization/deployment.yaml
  manifests/v1alpha3/suggestion/bayesianoptimization/service.yaml
  manifests/v1alpha3/suggestion/grid/deployment.yaml
  manifests/v1alpha3/suggestion/grid/service.yaml
  manifests/v1alpha3/suggestion/hyperband/deployment.yaml
  manifests/v1alpha3/suggestion/hyperband/service.yaml
  manifests/v1alpha3/suggestion/nasrl/deployment.yaml
  manifests/v1alpha3/suggestion/nasrl/service.yaml
  manifests/v1alpha3/suggestion/random/deployment.yaml
  manifests/v1alpha3/suggestion/random/service.yaml
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.pb.gw.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/apis/manager/v1alpha3/python/api_pb2_grpc.py
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  scripts/v1alpha3/deploy.sh
  scripts/v1alpha3/undeploy.sh
  test/scripts/v1alpha3/run-tests.sh
Labels: approved, lgtm, size/XXL

#775 feat: Add more output in e2e test for debug purpose and fix test cases
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/mock/v1alpha3/experiment/manifest/generator.go
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/util/v1alpha3/katibclient/katib_client.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  test/e2e/v1alpha3/run-e2e-experiment.go
Labels: approved, lgtm, size/L

#779 feat: Add GRPC health check in suggestions
  cmd/suggestion/hyperopt/v1alpha3/Dockerfile
  cmd/suggestion/hyperopt/v1alpha3/main.py
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/suggestion/v1alpha3/base_health_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha3/python-tests.sh
Labels: approved, lgtm, size/L

#785 Wait for GRPC server to be up
  cmd/suggestion/hyperopt/v1alpha3/requirements.txt
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
Labels: approved, lgtm, size/S

#784 Adding algorithm deployment status to Suggestion status
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
  pkg/apis/controller/suggestions/v1alpha3/util.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
Labels: approved, lgtm, size/M

#782 feat: Remove useless algorithms
  cmd/suggestion/bayesianoptimization/v1alpha3/Dockerfile
  cmd/suggestion/bayesianoptimization/v1alpha3/README.md
  cmd/suggestion/bayesianoptimization/v1alpha3/__init__.py
  cmd/suggestion/bayesianoptimization/v1alpha3/main.py
  cmd/suggestion/bayesianoptimization/v1alpha3/requirements.txt
  cmd/suggestion/grid/v1alpha3/Dockerfile
  cmd/suggestion/grid/v1alpha3/__init__.py
  cmd/suggestion/grid/v1alpha3/main.py
  cmd/suggestion/grid/v1alpha3/requirements.txt
  cmd/suggestion/random/v1alpha3/Dockerfile
  cmd/suggestion/random/v1alpha3/__init__.py
  cmd/suggestion/random/v1alpha3/main.py
  cmd/suggestion/random/v1alpha3/requirements.txt
  examples/v1alpha3/bayseopt-example.yaml
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/random-example.yaml
  pkg/suggestion/v1alpha3/bayesian_service.py
  pkg/suggestion/v1alpha3/grid_service.py
  pkg/suggestion/v1alpha3/random_service.py
  test/scripts/v1alpha3/build-suggestion-bo.sh
  test/scripts/v1alpha3/build-suggestion-grid.sh
  test/scripts/v1alpha3/build-suggestion-random.sh
  test/scripts/v1alpha3/run-tests.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XL

#783 Implement file metrics collector
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  examples/v1alpha3/hyperband-example.yaml
  examples/v1alpha3/hyperopt-random-example.yaml
  examples/v1alpha3/hyperopt-tpe-example.yaml
  examples/v1alpha3/pytorchjob-example.yaml
  examples/v1alpha3/tfjob-example.yaml
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
  pkg/webhook/v1alpha3/pod/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/L

#777 feat: Add bayesian
  cmd/suggestion/skopt/v1alpha3/Dockerfile
  cmd/suggestion/skopt/v1alpha3/__init__.py
  cmd/suggestion/skopt/v1alpha3/main.py
  cmd/suggestion/skopt/v1alpha3/requirements.txt
  examples/v1alpha3/skopt-bayesian-optimization-example.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
  pkg/suggestion/v1alpha3/skopt_service.py
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha3/build-suggestion-skopt.sh
  test/scripts/v1alpha3/python-tests.sh
  test/scripts/v1alpha3/run-tests.sh
  test/suggestion/v1alpha3/test_skopt_service.py
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XL

#780 feat: Add grid with the help of chocolate
  cmd/suggestion/chocolate/v1alpha3/Dockerfile
  cmd/suggestion/chocolate/v1alpha3/__init__.py
  cmd/suggestion/chocolate/v1alpha3/main.py
  cmd/suggestion/chocolate/v1alpha3/requirements.txt
  examples/v1alpha3/chocolate-grid-example.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/chocolate_service.py
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha3/build-suggestion-chocolate.sh
  test/scripts/v1alpha3/python-tests.sh
  test/scripts/v1alpha3/run-tests.sh
  test/suggestion/v1alpha3/test_chocolate_service.py.failed
  test/suggestion/v1alpha3/test_requirements.txt
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XL

#789 Adding javascripts locally
  pkg/ui/v1alpha3/frontend/public/index.html
  pkg/ui/v1alpha3/frontend/public/scripts/ace.js
  pkg/ui/v1alpha3/frontend/public/scripts/bootstrap.min.js
  pkg/ui/v1alpha3/frontend/public/scripts/d3.v5.min.js
  pkg/ui/v1alpha3/frontend/public/scripts/jquery-3.2.1.slim.min.js
  pkg/ui/v1alpha3/frontend/public/scripts/mode-xml.js
  pkg/ui/v1alpha3/frontend/public/scripts/popper.min.js
  pkg/ui/v1alpha3/frontend/public/scripts/underscore-min.js
  pkg/ui/v1alpha3/frontend/public/scripts/viz.js
Labels: approved, lgtm, size/L

#791 Mark trial as failed when job fails
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/M

#792 Implement tfevent collector
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/requirements.txt
  cmd/tfevent-metricscollector/v1alpha2/main.py
  examples/v1alpha3/tfjob-example.yaml
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/metricscollector/v1alpha3/common/__init__.py
  pkg/metricscollector/v1alpha3/common/pns.py
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/L

#786 UI: Fix problems
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/backend.go
Labels: approved, lgtm, size/M

#796 feat: Add events in suggestion
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  test/e2e/v1alpha3/run-e2e-experiment.go
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
Labels: approved, lgtm, size/S

#794 feat: Rename algorithms
  examples/v1alpha3/bayesianoptimization-example.yaml
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/random-example.yaml
  examples/v1alpha3/tfjob-example.yaml
  examples/v1alpha3/tpe-example.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
  pkg/suggestion/v1alpha3/skopt_service.py
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
  test/suggestion/v1alpha3/test_chocolate_service.py.failed
  test/suggestion/v1alpha3/test_hyperopt_service.py
  test/suggestion/v1alpha3/test_skopt_service.py
Labels: approved, lgtm, size/M

#795 build: Support arguments
  scripts/v1alpha3/build.sh
Labels: approved, lgtm, size/M

#798 Use common metricsCollector struct
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/common/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1alpha3/trial_types.go
  pkg/apis/controller/trials/v1alpha3/zz_generated.deepcopy.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/L

#799 fix: Use commitid
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
Labels: approved, lgtm, size/XS

#800 Removing metric collector templates from UI
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/templateActions.js
  pkg/ui/v1alpha3/frontend/src/components/App.jsx
  pkg/ui/v1alpha3/frontend/src/components/Menu/Menu.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Collector.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/template.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
Labels: approved, lgtm, size/L

#801 Using example as the default trial
  manifests/v1alpha3/katib-controller/trialTemplateConfigmap.yaml
Labels: approved, lgtm, size/S

#802 fix: Remove copy
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
Labels: approved, lgtm, size/XS

#803 Removing unnecessary config from examples
  examples/v1alpha3/bayesianoptimization-example.yaml
  examples/v1alpha3/grid-example.yaml
  test/scripts/v1alpha3/check-katib-ready.sh
Labels: approved, lgtm, size/XS

#806 Remove unused field from Experiment Spec
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/util.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
Labels: approved, lgtm, size/M

#809 feat: Add tpe e2e test case
  test/scripts/v1alpha3/run-suggestion-tpe.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/M

#813 fix: Fix the type
  cmd/suggestion/chocolate/v1alpha3/main.py
  examples/v1alpha3/hyperband-example.yaml
Labels: approved, lgtm, size/XS

#814 Rename algorithm deployment and service
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1alpha3/util/labels.go
  pkg/controller.v1alpha3/util/suggestion.go
Labels: approved, lgtm, size/M

#816 metrics-collector role is not useful any more
  manifests/v1alpha3/katib-controller/mcrbac.yaml
Labels: approved, lgtm, size/M

#817 Adding additional printer columns for better debugging
  manifests/v1alpha3/katib-controller/crd-suggestion.yaml
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
Labels: approved, lgtm, size/S

#818 feat: Remove useless APIs
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.pb.gw.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/apis/manager/v1alpha3/python/api_pb2_grpc.py
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/experiment/managerclient/managerclient.go
  pkg/controller.v1alpha3/trial/managerclient/managerclient.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/mock/v1alpha3/api/manager.go
  pkg/mock/v1alpha3/trial/managerclient/katibmanager.go
  pkg/ui/v1alpha3/backend.go
  pkg/webhook/v1alpha3/experiment/validation_webhook.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/XXL

#819 Fix stdout of worker container show nothing
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/XS

#822 fix: Build e2e-runner
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-hyperband.sh
  test/scripts/v1alpha3/run-suggestion-nasrl.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
  test/scripts/v1alpha3/run-suggestion-tpe.sh
Labels: approved, lgtm, size/S

#821 feat: Support step when using grid in UI
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/scripts/start.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Parameters.jsx
Labels: approved, lgtm, size/M

#826 fix: Support multiple namespaces when using kubectl
  pkg/controller.v1alpha3/util/suggestion.go
Labels: approved, lgtm, size/XS

#824 Doc about katib workflow design
  docs/images/katib-workflow.png
  docs/workflow-design.md
Labels: approved, lgtm, size/L

#828 Make sure experiment namespace can inject metriccollector sidecar
  manifests/v1alpha3/katib-controller/rbac.yaml
  pkg/webhook/v1alpha3/common/const.go
  pkg/webhook/v1alpha3/experiment/validation_webhook.go
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/M

#829 feat: Use env var for namespace
  manifests/v1alpha3/ui/deployment.yaml
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/S

#831 Update status conditions during reconcile error
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
Labels: approved, lgtm, size/S

#830 Remove metrics in DB when delete trial
  cmd/manager/v1alpha3/main.go
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/apis/manager/v1alpha3/python/api_pb2_grpc.py
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/controller.v1alpha3/trial/managerclient/managerclient.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
  pkg/db/v1alpha3/common/kdb.go
  pkg/db/v1alpha3/mysql/mysql.go
  pkg/mock/v1alpha3/api/manager.go
  pkg/mock/v1alpha3/db/db.go
  pkg/mock/v1alpha3/trial/managerclient/katibmanager.go
Labels: approved, lgtm, size/XL

#827 feat: support namespace for trial template
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/templateActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/L

#832 File metrics collector end to end test
  examples/v1alpha3/file-metrics-collector/Dockerfile
  examples/v1alpha3/file-metrics-collector/mnist.py
  examples/v1alpha3/file-metricscollector-example.yaml
  examples/v1alpha3/tfevent-volume/tfevent-pv.yaml
  examples/v1alpha3/tfevent-volume/tfevent-pvc.yaml
  test/scripts/v1alpha3/run-file-metricscollector.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/L

#836 Remove used katib-manager code
  cmd/manager/v1alpha3/main.go
  cmd/manager/v1alpha3/main_test.go
  pkg/db/v1alpha3/common/kdb.go
  pkg/db/v1alpha3/mysql/init.go
  pkg/db/v1alpha3/mysql/mysql.go
  pkg/db/v1alpha3/mysql/mysql_test.go
Labels: approved, lgtm, size/XXL

#833 fix: Update liveness probe to avoid problems
  pkg/controller.v1alpha3/suggestion/composer/composer.go
Labels: approved, lgtm, size/S

#820 Add tfjob and pytorch examples to e2e
  examples/v1alpha3/pytorchjob-example.yaml
  test/e2e/v1alpha3/run-e2e-experiment.go
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/run-pytorchjob.sh
  test/scripts/v1alpha3/run-tfjob.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/L

#837 Remove unused manager message definition
  cmd/manager/v1alpha3/main_test.go
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.pb.gw.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/api.md
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  pkg/mock/v1alpha3/db/db.go
  pkg/mock/v1alpha3/experiment/managerclient/managerclient.go
Labels: approved, lgtm, size/XXL

#838 Delete jobs when trials are completed
  examples/v1alpha3/pytorchjob-example.yaml
  examples/v1alpha3/tfjob-example.yaml
Labels: approved, lgtm, size/XS

#835 feat: Show all experiments in monitor
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpCreateActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/App.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobList.jsx
  pkg/ui/v1alpha3/frontend/src/components/Menu/DeleteDialog.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/nas.go
  pkg/ui/v1alpha3/types.go
  pkg/ui/v1alpha3/util.go
Labels: approved, lgtm, size/L

#839 feat: Support namespace in NAS UI
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/nasCreateActions.js
  pkg/ui/v1alpha3/frontend/src/actions/nasMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/App.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobList.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/hp.go
  pkg/ui/v1alpha3/nas.go
Labels: approved, lgtm, size/XL

#769 feat: Add doc for implementing new algorithms
  Makefile
  docs/developer-guide.md
  docs/rest-api.md
Labels: approved, lgtm, size/L

#726 [docs] Add suggestion proposal
  docs/developer-guide.md
  docs/images/suggestion-workflow.png
  docs/proposals/suggestion.md
  pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
Labels: approved, lgtm, size/L
