Repository kubeflow/katib, pull requests merged in 2019-07, with the labels that each got.

#672 Update Build Script for v1alpha2
  scripts/v1alpha2/build.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/XS

#684 Fix prow error
  test/scripts/v1alpha1/create-cluster.sh
  test/scripts/v1alpha1/run-tests.sh
  test/scripts/v1alpha2/create-cluster.sh
  test/workflows/app.yaml
Labels: approved, lgtm, size/XS

#682 Use latest katib images to deploy katib
  manifests/v1alpha1/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/v1alpha1/studyjobcontroller/studyjobcontroller.yaml
  manifests/v1alpha1/vizier/core-rest/deployment.yaml
  manifests/v1alpha1/vizier/core/deployment.yaml
  manifests/v1alpha1/vizier/earlystopping/medianstopping/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/bayesianoptimization/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/grid/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/hyperband/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/nasenvelopenet/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/nasrl/deployment.yaml
  manifests/v1alpha1/vizier/suggestion/random/deployment.yaml
  manifests/v1alpha1/vizier/ui/deployment.yaml
  manifests/v1alpha2/katib-controller/katib-controller.yaml
  manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
  manifests/v1alpha2/manager-rest/deployment.yaml
  manifests/v1alpha2/manager/deployment.yaml
  manifests/v1alpha2/suggestion/bayesianoptimization/deployment.yaml
  manifests/v1alpha2/suggestion/grid/deployment.yaml
  manifests/v1alpha2/suggestion/hyperband/deployment.yaml
  manifests/v1alpha2/suggestion/nasrl/deployment.yaml
  manifests/v1alpha2/suggestion/random/deployment.yaml
  manifests/v1alpha2/ui/deployment.yaml
  test/scripts/v1alpha1/run-tests.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/L

#686 Change Image Tags to the latest in e2e tests
  test/scripts/v1alpha1/run-tests.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/XS

#681 Add tfevent-volume to v1alpha2 example
  examples/v1alpha2/tfevent-volume/tfevent-pv.yaml
  examples/v1alpha2/tfevent-volume/tfevent-pvc.yaml
Labels: approved, lgtm, size/S

#687 Fix error of undeploy.sh
  examples/v1alpha2/hyperband-example.yaml
  scripts/v1alpha1/undeploy.sh
  scripts/v1alpha2/deploy.sh
  scripts/v1alpha2/undeploy.sh
Labels: approved, lgtm, size/S

#688 Add example readme for v1alpha2
  README.md
  examples/v1alpha1/MinikubeDemo/mnist-models.yaml
  examples/v1alpha1/README.md
  examples/v1alpha2/MinikubeDemo/deploy.sh
  examples/v1alpha2/MinikubeDemo/destroy.sh
  examples/v1alpha2/README.md
Labels: approved, lgtm, size/XL

#689 Fix tf-event example cannot work
  examples/v1alpha1/README.md
  examples/v1alpha1/tf-event_test.yaml
  examples/v1alpha2/tfjob-example.yaml
Labels: approved, lgtm, size/L

#673 update some dockerfiles to support power
  cmd/katib-controller/v1alpha1/Dockerfile
  cmd/katib-controller/v1alpha2/Dockerfile
  cmd/manager-rest/v1alpha1/Dockerfile
  cmd/manager-rest/v1alpha2/Dockerfile
  cmd/manager/v1alpha1/Dockerfile
  cmd/manager/v1alpha2/Dockerfile
  cmd/metricscollector/v1alpha1/Dockerfile
  cmd/metricscollector/v1alpha2/Dockerfile
  cmd/suggestion/bayesianoptimization/v1alpha1/Dockerfile
  cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
  cmd/suggestion/grid/v1alpha1/Dockerfile
  cmd/suggestion/grid/v1alpha2/Dockerfile
  cmd/suggestion/hyperband/v1alpha1/Dockerfile
  cmd/suggestion/hyperband/v1alpha2/Dockerfile
  cmd/suggestion/random/v1alpha1/Dockerfile
  cmd/suggestion/random/v1alpha2/Dockerfile
  cmd/ui/v1alpha1/Dockerfile
  cmd/ui/v1alpha2/Dockerfile
Labels: approved, lgtm, ok-to-test, size/L

#695 Fix wrong end state of trial
  pkg/controller/v1alpha2/trial/trial_controller.go
Labels: approved, lgtm, size/XS

#700 Update vendor
  Gopkg.lock
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/constants.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/defaults.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/doc.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/register.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/types.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1beta2/zz_generated.defaults.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/constants.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/defaults.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/doc.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/openapi_generated.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/register.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/types.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/util.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/tf-operator/pkg/apis/tensorflow/v1beta2/zz_generated.defaults.go
Labels: approved, lgtm, size/XXL
