Repository kubeflow/katib, pull requests merged in 2019-04, with the labels that each got.

#450 Update API for NAS in v1alpha2
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
Labels: approved, lgtm, size/XL

#451 ClusterRoleBinding doesn't need namespace field
  manifests/v1alpha1/studyjobcontroller/mcrbac.yaml
  manifests/v1alpha1/studyjobcontroller/rbac.yaml
  manifests/v1alpha1/vizier/ui/rbac.yaml
Labels: approved, lgtm, size/XS

#453 fix py client import error
  py/study_job_client.py
Labels: approved, lgtm, size/XS

#452 Update REAME example links for v1alpha1
  README.md
  docs/developer-guide.md
  docs/rest-api.md
  examples/v1alpha1/README.md
  pkg/api/README.md
Labels: approved, lgtm, ok-to-test, size/M

#455 fix(readme): Merge image directory
  README.md
  docs/images/Katib_Logo.png
Labels: approved, lgtm, size/XS

#456 v1alpha2 api server implementation
  cmd/manager/v1alpha2/main.go
  cmd/manager/v1alpha2/main_test.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.pb.gw.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/db/v1alpha2/db_init.go
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
  pkg/mock/modelstore/modelstore.go
  pkg/mock/v1alpha1/api/manager.go
  pkg/mock/v1alpha1/api/suggestion.go
  pkg/mock/v1alpha1/db/db.go
  pkg/mock/v1alpha2/api/manager.go
  pkg/mock/v1alpha2/api/suggestion.go
  pkg/mock/v1alpha2/db/db.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/XXL

#467 chore: Skip test when code is not changed
  prow_config.yaml
Labels: approved, lgtm, size/S

#469 Add serviceAccountName in UI deployment
  manifests/v1alpha1/vizier/ui/deployment.yaml
Labels: approved, lgtm, size/XS

#465 enable test for v1alpha2
  examples/v1alpha2/random-example.yaml
  manifests/v1alpha2/0-namespace.yaml
  manifests/v1alpha2/katib-controller/crds.yaml
  manifests/v1alpha2/katib-controller/katib-controller.yaml
  manifests/v1alpha2/katib-controller/rbac.yaml
  manifests/v1alpha2/katib-controller/service.yaml
  manifests/v1alpha2/katib-controller/trialTemplateConfigmap.yaml
  prow_config.yaml
  scripts/v1alpha2/build.sh
  scripts/v1alpha2/deploy.sh
  test/scripts/v1alpha2/build-earlystopping-median.sh
  test/scripts/v1alpha2/build-katib-controller.sh
  test/scripts/v1alpha2/build-manager-rest.sh
  test/scripts/v1alpha2/build-manager.sh
  test/scripts/v1alpha2/build-suggestion-bo.sh
  test/scripts/v1alpha2/build-suggestion-grid.sh
  test/scripts/v1alpha2/build-suggestion-hyperband.sh
  test/scripts/v1alpha2/build-suggestion-nasrl.sh
  test/scripts/v1alpha2/build-suggestion-random.sh
  test/scripts/v1alpha2/build-ui.sh
  test/scripts/v1alpha2/create-cluster.sh
  test/scripts/v1alpha2/delete-cluster.sh
  test/scripts/v1alpha2/get-vendor-packages.sh
  test/scripts/v1alpha2/python-tests.sh
  test/scripts/v1alpha2/run-tests.sh
  test/scripts/v1alpha2/unit-test.sh
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows-v1alpha1.jsonnet
  test/workflows/components/workflows-v1alpha1.libsonnet
  test/workflows/components/workflows-v1alpha2.jsonnet
  test/workflows/components/workflows-v1alpha2.libsonnet
Labels: approved, lgtm, size/XXL

#473 validation and mutating webhook for experiment
  manifests/v1alpha2/katib-controller/katib-controller.yaml
  manifests/v1alpha2/katib-controller/rbac.yaml
  manifests/v1alpha2/katib-controller/secret.yaml
  pkg/api/operators/apis/experiment/v1alpha2/experiment_defaults.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/mutate_webhook.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/controller/v1alpha2/experiment/util/client_util.go
  pkg/controller/v1alpha2/experiment/util/runjob_util.go
  pkg/controller/v1alpha2/experiment/util/template_util.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/controller/v1alpha2/experiment/validation_webhook.go
  scripts/v1alpha2/deploy.sh
  test/e2e/v1alpha2/invalid-experiment.yaml
  test/e2e/v1alpha2/valid-experiment.yaml
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/XL

#477 share one grpc-health-probe
  cmd/manager/v1alpha1/main.go
  cmd/manager/v1alpha2/main.go
  pkg/api/health/Makefile
  pkg/api/health/build.sh
  pkg/api/health/health.pb.go
  pkg/api/health/health.proto
  pkg/api/health/health.swagger.json
  pkg/api/health/python/health_pb2.py
  pkg/api/health/python/health_pb2_grpc.py
  pkg/api/v1alpha1/Makefile
  pkg/api/v1alpha1/build.sh
  pkg/api/v1alpha1/python/health/health_pb2.py
  pkg/api/v1alpha1/python/health/health_pb2_grpc.py
  pkg/api/v1alpha2/Makefile
  pkg/api/v1alpha2/build.sh
  pkg/api/v1alpha2/health/health.pb.go
  pkg/api/v1alpha2/health/health.proto
  pkg/api/v1alpha2/health/health.swagger.json
Labels: approved, lgtm, size/XL

#476 katib manager db error
  pkg/db/v1alpha2/db_init.go
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
Labels: approved, lgtm, size/M

#482 vizier-core does not need any role
  manifests/v1alpha1/vizier/core/deployment.yaml
  manifests/v1alpha1/vizier/core/rbac.yaml
Labels: approved, lgtm, size/M
