Repository kubeflow/katib, pull requests merged in 2019-10, with the labels that each got.

#846 fix: Use namespace to get trial list
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/XS

#850 feat: Set default namespace and template for trial
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
Labels: approved, lgtm, size/XS

#847 fix: Reorder to skip observation collection
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/S

#851 chore: Add dockerignore, enhance liveness for manager
  .dockerignore
  manifests/v1alpha3/manager/deployment.yaml
  pkg/controller.v1alpha3/suggestion/composer/composer.go
Labels: approved, lgtm, size/S

#852 Adding events to trials
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_consts.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/M

#858 fix: Fix docs about metrics collection and suggestion design
  docs/images/suggestion-workflow.png
  docs/proposals/metrics-collector.md
  docs/proposals/suggestion.md
Labels: approved, lgtm, size/XS

#860 Update Readme
  README.md
  docs/images/katib-ui.png
Labels: approved, lgtm, size/L

#861 Finish reconcile only after running trials are complete
  pkg/apis/controller/experiments/v1alpha3/util.go
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
  test/e2e/v1alpha3/run-e2e-experiment.go
  test/scripts/v1alpha3/check-katib-ready.sh
Labels: approved, lgtm, size/M

#853 feat: Show experiment status in json
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/M

#863 Fix worker error silent
  Gopkg.lock
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  pkg/metricscollector/v1alpha3/common/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/M

#864 Adding metric unavailability to events
  manifests/v1alpha3/katib-controller/crd-trial.yaml
  pkg/apis/controller/trials/v1alpha3/util.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_consts.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/M

#844 feat: Add doc about how to add a new kind in trial
  docs/developer-guide.md
  docs/new-algorithm-service.md
  docs/new-trial-kind.md
Labels: approved, lgtm, size/XL

#867 feat: Add doc about algorithm
  docs/algorithm-settings.md
Labels: approved, lgtm, size/M

#869 Remove unused files
  pkg/controller.v1alpha2/trial/metriccollector.go
  pkg/controller.v1alpha3/trial/metriccollector.go
Labels: approved, lgtm, size/M

#871 feat: Add liveness probe for DB
  manifests/v1alpha3/db/deployment.yaml
Labels: approved, lgtm, size/S

#868 feat: Support env in mysql
  pkg/controller.v1alpha3/consts/const.go
  pkg/db/v1alpha3/common/const.go
  pkg/db/v1alpha3/mysql/mysql.go
  pkg/util/v1alpha3/env/env.go
  pkg/util/v1alpha3/env/env_test.go
Labels: approved, lgtm, size/M

#875 fix: Use binary in test
  test/scripts/v1alpha3/run-pytorchjob.sh
  test/scripts/v1alpha3/run-tfjob.sh
Labels: approved, lgtm, size/XS

#870 Add prometheus metrics for experiment and trial
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
  pkg/controller.v1alpha3/trial/prometheus_metrics.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/L

#873 feat: Support random state in random search
  docs/algorithm-settings.md
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
Labels: approved, lgtm, size/M

#865 feat: Refactor to make it easy to extend new kinds
  pkg/common/v1alpha3/common.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
  pkg/job/v1alpha3/consts.go
  pkg/job/v1alpha3/job/job.go
  pkg/job/v1alpha3/kubeflow/kubeflow.go
  pkg/job/v1alpha3/provider.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/pod/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/pod/utils.go
Labels: approved, lgtm, size/L

#876 Remove unused katib-manager-rest
  cmd/manager-rest/v1alpha3/Dockerfile
  cmd/manager-rest/v1alpha3/proxy.go
  manifests/v1alpha3/manager-rest/deployment.yaml
  manifests/v1alpha3/manager-rest/service.yaml
  pkg/apis/manager/v1alpha3/api.pb.go
  pkg/apis/manager/v1alpha3/api.proto
  pkg/apis/manager/v1alpha3/api.swagger.json
  pkg/apis/manager/v1alpha3/gen-doc/index.html
  pkg/apis/manager/v1alpha3/python/api_pb2.py
  scripts/v1alpha3/build.sh
  scripts/v1alpha3/deploy.sh
  scripts/v1alpha3/undeploy.sh
  test/scripts/v1alpha3/build-manager-rest.sh
  test/scripts/v1alpha3/check-katib-ready.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/XL

#880 feat: Add events in experiment
  pkg/controller.v1alpha3/experiment/experiment_consts.go
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/trial/trial_controller.go
Labels: approved, lgtm, size/M

#879 feat: Add event when the reconcile is failed
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_consts.go
Labels: approved, lgtm, size/XS

#881 fix: Use as instead of , to support python 3 in tfevent metrics collector
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py
Labels: approved, lgtm, size/M

#883 fix: Use 64 instead of 32 since we are using float64
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, size/S

#885 Pin operators to 0.7 branch
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/S

#878 feat: Add quick start
  README.md
  docs/images/quickstart-trial.png
  docs/images/quickstart.png
  docs/quick-start.md
Labels: approved, lgtm, size/L

#895 feat: Patch to fix running condition
  pkg/job/v1alpha3/job/job.go
  pkg/job/v1alpha3/kubeflow/kubeflow.go
  prow_config.yaml
  test/scripts/v1alpha3/build-suggestion-chocolate.sh
  test/scripts/v1alpha3/build-suggestion-hyperband.sh
  test/scripts/v1alpha3/build-suggestion-hyperopt.sh
  test/scripts/v1alpha3/build-suggestion-nasrl.sh
  test/scripts/v1alpha3/build-suggestion-skopt.sh
  test/scripts/v1alpha3/check-katib-ready.sh
Labels: approved, lgtm, size/M

#899 Revert env for katib-db
  pkg/db/v1alpha3/mysql/mysql.go
Labels: approved, lgtm, size/S

#900 Fix katib-manager crash in kubeflow cluster
  pkg/db/v1alpha3/common/const.go
  pkg/db/v1alpha3/mysql/mysql.go
Labels: approved, lgtm, size/S

#901 Support restarting training job
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  pkg/metricscollector/v1alpha3/common/const.go
  pkg/metricscollector/v1alpha3/common/pns.go
  pkg/metricscollector/v1alpha3/common/pns.py
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/M
