Repository kubeflow/katib, pull requests merged in 2019-05, with the labels that each got.

#481 Add metrics collector spec to v1alpha2 API
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/api/operators/apis/experiment/v1alpha2/zz_generated.deepcopy.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
Labels: approved, lgtm, size/XXL

#480 Add Katib Client in v1alpha2
  Gopkg.lock
  pkg/api/operators/apis/experiment/v1alpha2/constants.go
  pkg/controller/v1alpha2/experiment/util/client_util.go
  pkg/controller/v1alpha2/experiment/util/template_util.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/util/v1alpha2/katibclient/katib_client.go
Labels: approved, lgtm, size/L

#483 Fix KatibClient name in v1alpha2
  pkg/util/v1alpha2/katibclient/katib_client.go
Labels: approved, lgtm, size/S

#474 Get experiment config from the instance
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
Labels: approved, lgtm, size/XL

#468 Remove outdated TODOs in README.md
  README.md
Labels: approved, lgtm, size/XS

#478 enable test for katib-manager
  cmd/manager-rest/v1alpha2/proxy.go
  manifests/v1alpha2/katib/db/deployment.yaml
  manifests/v1alpha2/katib/db/secret.yaml
  manifests/v1alpha2/katib/db/service.yaml
  manifests/v1alpha2/katib/manager/deployment.yaml
  manifests/v1alpha2/katib/manager/service.yaml
  manifests/v1alpha2/katib/pv/pv.yaml
  manifests/v1alpha2/katib/pv/pvc.yaml
  pkg/db/v1alpha2/interface.go
  scripts/v1alpha2/build.sh
  scripts/v1alpha2/deploy.sh
  test/e2e/v1alpha2/test-katib-manager.py
  test/e2e/v1alpha2/test_requirements.txt
  test/scripts/v1alpha2/build-manager-rest.sh
  test/scripts/v1alpha2/build-manager.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/L

#484 V1alpha2 Metrics collector (part 1)
  cmd/metricscollector/Dockerfile
  cmd/metricscollector/v1alpha2/main.go
  manifests/v1alpha2/katib-controller/mcrbac.yaml
  manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/controller/v1alpha2/experiment/util/runjob_util.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/util/v1alpha2/metricscollector/metricscollector.go
  scripts/v1alpha2/deploy.sh
Labels: approved, lgtm, size/L

#425 NAS Envelopenet Suggestion and Job Example
  cmd/suggestion/nasenvelopenet/Dockerfile
  cmd/suggestion/nasenvelopenet/__init__.py
  cmd/suggestion/nasenvelopenet/main.py
  cmd/suggestion/nasenvelopenet/requirements.txt
  examples/nasjob-example-envelopenet.yaml
  manifests/vizier/suggestion/NAS-Envelopenet/deployment.yaml
  manifests/vizier/suggestion/NAS-Envelopenet/service.yaml
  pkg/suggestion/NAS_Envelopenet/README.md
  pkg/suggestion/NAS_Envelopenet/generate_arch.py
  pkg/suggestion/NAS_Envelopenet/nac_gen.py
  pkg/suggestion/NAS_Envelopenet/operation.py
  pkg/suggestion/NAS_Envelopenet/suggestion_param.py
  pkg/suggestion/nasenvelopenet_service.py
Labels: approved, lgtm, size/XL

#429 Training container for NAS Envelopenet
  examples/NAS-Envelopenet-trainingcontainer/Dockerfile
  examples/NAS-Envelopenet-trainingcontainer/README.md
  examples/NAS-Envelopenet-trainingcontainer/cell.py
  examples/NAS-Envelopenet-trainingcontainer/cell_classification.py
  examples/NAS-Envelopenet-trainingcontainer/cell_init.py
  examples/NAS-Envelopenet-trainingcontainer/cell_main.py
  examples/NAS-Envelopenet-trainingcontainer/cifar10_input.py
  examples/NAS-Envelopenet-trainingcontainer/evaluate.py
  examples/NAS-Envelopenet-trainingcontainer/model_constructor.py
  examples/NAS-Envelopenet-trainingcontainer/net.py
  examples/NAS-Envelopenet-trainingcontainer/requirements.txt
  examples/NAS-Envelopenet-trainingcontainer/run_trial.py
  examples/NAS-Envelopenet-trainingcontainer/test.py
Labels: approved, lgtm, size/XXL

#490 Prune katib OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#489 Add metrics collector spec and objective spec to Trial
  cmd/manager/v1alpha2/main_test.go
  examples/v1alpha2/random-example.yaml
  pkg/api/operators/apis/common/group.go
  pkg/api/operators/apis/common/v1alpha2/common_types.go
  pkg/api/operators/apis/common/v1alpha2/zz_generated.deepcopy.go
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/api/operators/apis/experiment/v1alpha2/zz_generated.deepcopy.go
  pkg/api/operators/apis/trial/v1alpha2/trial_types.go
  pkg/api/operators/apis/trial/v1alpha2/zz_generated.deepcopy.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/controller/v1alpha2/experiment/mutate_webhook.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/controller/v1alpha2/experiment/util/status_util.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/controller/v1alpha2/experiment/validation_webhook.go
  pkg/db/v1alpha2/db_init.go
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
  test/e2e/v1alpha2/invalid-experiment.yaml
  test/e2e/v1alpha2/test-katib-manager.py
  test/e2e/v1alpha2/valid-experiment.yaml
Labels: approved, lgtm, size/XXL

#491 add common package
  pkg/common/v1alpha1/common.go
  pkg/common/v1alpha2/common.go
  pkg/controller/v1alpha1/studyjob/katib_api_util.go
  pkg/controller/v1alpha1/studyjob/manifest_parser.go
  pkg/controller/v1alpha1/studyjob/studyjob_controller.go
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/suggestion/v1alpha1/grid_service.go
  pkg/suggestion/v1alpha1/hyperband_service.go
  pkg/suggestion/v1alpha1/random_service.go
  pkg/ui/ui.go
Labels: approved, lgtm, size/M

#485 Update util for experiment in v1alpha2
  pkg/api/operators/apis/experiment/v1alpha2/util.go
Labels: approved, lgtm, size/S

#496 v1alpha2 metrics collector - controller
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/controller/v1alpha2/trial/trial_controller.go
Labels: approved, lgtm, size/M

#504 Enabled verbose logging for dev guide.
  docs/developer-guide.md
Labels: approved, lgtm, size/XS

#505 Added PR and Issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#516 feat(CI): Run different flow according to version
  prow_config.yaml
Labels: approved, lgtm, size/L

#502 refactor(suggestion): Use interface
  Gopkg.lock
  cmd/katib-controller/v1alpha2/main.go
  pkg/controller/v1alpha2/consts/const.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/suggestion/fake/fake.go
  pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/util/v1alpha2/katibclient/katib_client.go
Labels: approved, lgtm, size/L

#509 create experiment in db
  pkg/common/v1alpha2/common.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/db/v1alpha2/interface.go
Labels: approved, lgtm, size/L

#520 Fix prow to trigger corresponding workflow
  prow_config.yaml
Labels: approved, lgtm, size/S

#521 godep: Remove useless dep
  prow_config.yaml
Labels: approved, lgtm, size/XS

#524 Fix ut test and enable ut-test of v1alpha2
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
  test/scripts/v1alpha2/unit-test.sh
Labels: approved, lgtm, size/M

#512 Support for Custom Job resources
  Gopkg.lock
  examples/v1alpha2/pytorchjob-example.yaml
  pkg/api/operators/apis/addtoscheme_pytorchjob_v1beta2.go
  pkg/api/operators/apis/addtoscheme_tfjob_v1beta2.go
  pkg/common/v1alpha2/common.go
  pkg/controller/v1alpha2/experiment/util/webhook_util.go
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/util/status_util.go
Labels: approved, lgtm, size/L

#519 Delete experiment in DB if in need
  pkg/api/operators/apis/experiment/v1alpha2/util.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
Labels: approved, lgtm, size/M

#529 Fix wrong error-handling logic in db interface
  pkg/db/v1alpha2/interface.go
Labels: approved, lgtm, size/M

#501 feat(api): Add total number of trials
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/controller/v1alpha2/experiment/util/status_util.go
Labels: approved, lgtm, size/S

#534 Update experiment status DB operation
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/controller/v1alpha2/experiment/util/status_util.go
  pkg/db/v1alpha2/interface.go
Labels: approved, lgtm, size/M

#536 Include vendor dir instead of Gopkg in prow config
  prow_config.yaml
Labels: approved, lgtm, size/XS

#532 fix: Avoid side effect
  pkg/controller/v1alpha2/trial/trial_controller.go
Labels: approved, lgtm, size/M

#527 Restructuring docker files to build images per version
  cmd/earlystopping/medianstopping/v1alpha1/Dockerfile
  cmd/katib-controller/v1alpha1/Dockerfile
  cmd/katib-controller/v1alpha2/Dockerfile
  cmd/manager-rest/v1alpha1/Dockerfile
  cmd/manager-rest/v1alpha2/Dockerfile
  cmd/manager/v1alpha1/Dockerfile
  cmd/manager/v1alpha2/Dockerfile
  cmd/metricscollector/v1alpha1/Dockerfile
  cmd/metricscollector/v1alpha2/Dockerfile
  cmd/suggestion/bayesianoptimization/v1alpha1/Dockerfile
  cmd/suggestion/bayesianoptimization/v1alpha1/README.md
  cmd/suggestion/bayesianoptimization/v1alpha1/requirements.txt
  cmd/suggestion/grid/v1alpha1/Dockerfile
  cmd/suggestion/hyperband/v1alpha1/Dockerfile
  cmd/suggestion/nasrl/v1alpha1/Dockerfile
  cmd/suggestion/nasrl/v1alpha1/requirements.txt
  cmd/suggestion/random/v1alpha1/Dockerfile
  cmd/tfevent-metricscollector/v1alpha1/Dockerfile
  manifests/v1alpha2/katib-controller/katib-controller.yaml
  manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
  manifests/v1alpha2/katib/manager/deployment.yaml
  prow_config.yaml
  scripts/v1alpha1/build.sh
  scripts/v1alpha2/build.sh
  test/scripts/v1alpha1/build-earlystopping-median.sh
  test/scripts/v1alpha1/build-manager-rest.sh
  test/scripts/v1alpha1/build-manager.sh
  test/scripts/v1alpha1/build-studyjobctr.sh
  test/scripts/v1alpha1/build-suggestion-bo.sh
  test/scripts/v1alpha1/build-suggestion-grid.sh
  test/scripts/v1alpha1/build-suggestion-hyperband.sh
  test/scripts/v1alpha1/build-suggestion-nasrl.sh
  test/scripts/v1alpha1/build-suggestion-random.sh
  test/scripts/v1alpha1/build-ui.sh
  test/scripts/v1alpha1/python-tests.sh
  test/scripts/v1alpha1/run-tests.sh
  test/scripts/v1alpha2/build-earlystopping-median.sh
  test/scripts/v1alpha2/build-katib-controller.sh
  test/scripts/v1alpha2/build-manager-rest.sh
  test/scripts/v1alpha2/build-manager.sh
  test/scripts/v1alpha2/build-suggestion-bo.sh
  test/scripts/v1alpha2/build-suggestion-grid.sh
  test/scripts/v1alpha2/build-suggestion-hyperband.sh
  test/scripts/v1alpha2/build-suggestion-nasrl.sh
  test/scripts/v1alpha2/build-suggestion-random.sh
  test/scripts/v1alpha2/build-ui.sh
  test/scripts/v1alpha2/python-tests.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/L

#530 Register Trial in DB
  cmd/manager/v1alpha2/main.go
  cmd/manager/v1alpha2/main_test.go
  pkg/api/operators/apis/trial/v1alpha2/util.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/controller/v1alpha2/trial/util/api_util.go
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
  test/e2e/v1alpha2/test-katib-manager.py
Labels: approved, lgtm, size/XL

#538 v1alpha2 TFEvent metrics collector
  cmd/tfevent-metricscollector/v1alpha2/Dockerfile
  cmd/tfevent-metricscollector/v1alpha2/main.py
  examples/v1alpha2/tfjob-example.yaml
  pkg/util/v1alpha2/tfevent-metricscollector/__init__.py
  pkg/util/v1alpha2/tfevent-metricscollector/tfevent_loader.py
  scripts/v1alpha2/build.sh
  test/scripts/v1alpha2/build-katib-controller.sh
Labels: approved, lgtm, size/L

#539 [v1alpha2] Add labels for TFjob and PytorchJob in Metrics Collector
  pkg/common/v1alpha2/common.go
  pkg/util/v1alpha2/metricscollector/metricscollector.go
Labels: approved, lgtm, size/S

#537 Update trial status DB operation
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/common/v1alpha2/common.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/util/api_util.go
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/util/api_util.go
  pkg/controller/v1alpha2/trial/util/status_util.go
Labels: approved, lgtm, size/XXL

#508 fix: Add test cases for validator and manifest generator
  Gopkg.toml
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/manifest/generator.go
  pkg/controller/v1alpha2/experiment/manifest/generator_test.go
  pkg/controller/v1alpha2/experiment/util/template_util.go
  pkg/controller/v1alpha2/experiment/validation_webhook.go
  pkg/controller/v1alpha2/experiment/validator/validator.go
  pkg/controller/v1alpha2/experiment/validator/validator_test.go
  pkg/mock/modelstore/modelstore.go
  pkg/mock/v1alpha1/api/manager.go
  pkg/mock/v1alpha1/api/suggestion.go
  pkg/mock/v1alpha1/db/db.go
  pkg/mock/v1alpha2/api/manager.go
  pkg/mock/v1alpha2/api/suggestion.go
  pkg/mock/v1alpha2/db/db.go
  pkg/mock/v1alpha2/experiment/manifest/producer.go
  pkg/mock/v1alpha2/util/katibclient/katibclient.go
  pkg/util/v1alpha2/katibclient/katib_client.go
  scripts/mockgen.sh
  test/scripts/v1alpha2/unit-test.sh
Labels: approved, lgtm, size/XXL

#540 Adding random suggestion algorithm implementation and manifests
  cmd/suggestion/random/v1alpha2/Dockerfile
  cmd/suggestion/random/v1alpha2/__init__.py
  cmd/suggestion/random/v1alpha2/main.py
  cmd/suggestion/random/v1alpha2/requirements.txt
  manifests/v1alpha2/katib/suggestion/random/deployment.yaml
  manifests/v1alpha2/katib/suggestion/random/service.yaml
  pkg/suggestion/v1alpha2/__init__.py
  pkg/suggestion/v1alpha2/parameter.py
  pkg/suggestion/v1alpha2/parsing_util.py
  pkg/suggestion/v1alpha2/random_service.py
  scripts/v1alpha2/build.sh
  scripts/v1alpha2/deploy.sh
  test/scripts/v1alpha2/build-suggestion-random.sh
Labels: approved, lgtm, size/L

#541 Include suggestion manager based on version in prow
  prow_config.yaml
Labels: approved, lgtm, size/S

#518 fix(status): Define status handler
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_status.go
Labels: approved, lgtm, size/S

#543 Enable suggestion-random image build and push in CI
  test/scripts/v1alpha2/build-suggestion-random.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/XS

#542 Adding manifests for manager rest
  manifests/v1alpha2/katib/manager-rest/deployment.yaml
  manifests/v1alpha2/katib/manager-rest/service.yaml
  scripts/v1alpha2/build.sh
  scripts/v1alpha2/deploy.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/M

#544 Earlystopping changes trigger CI based on version
  prow_config.yaml
Labels: approved, lgtm, size/XS

#545 fix: Fix the conflicts in UI backend
  pkg/ui/v1alpha2/types.go
Labels: approved, lgtm, size/XS

#546 Implement GetSuggestions for general suggestion
  pkg/api/operators/apis/experiment/v1alpha2/experiment_defaults.go
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/api/operators/apis/experiment/v1alpha2/zz_generated.deepcopy.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/suggestion/fake/fake.go
  pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
  pkg/controller/v1alpha2/experiment/util/status_util.go
Labels: approved, lgtm, size/M

#526 Used klog for katib - part 1.
  cmd/earlystopping/medianstopping/v1alpha1/main.go
  cmd/katib-controller/v1alpha1/main.go
  cmd/katib-controller/v1alpha2/main.go
  cmd/manager-rest/v1alpha1/proxy.go
  cmd/manager-rest/v1alpha2/proxy.go
  cmd/manager/v1alpha1/main.go
  cmd/manager/v1alpha2/main.go
  cmd/metricscollector/v1alpha1/main.go
  cmd/metricscollector/v1alpha2/main.go
  cmd/suggestion/grid/v1alpha1/main.go
  cmd/suggestion/hyperband/v1alpha1/main.go
  cmd/suggestion/random/v1alpha1/main.go
  pkg/controller/v1alpha1/studyjob/katib_api_util.go
  pkg/controller/v1alpha1/studyjob/studyjob_controller.go
  pkg/controller/v1alpha1/studyjob/utils.go
  pkg/db/v1alpha1/db_init.go
  pkg/db/v1alpha1/interface.go
  pkg/db/v1alpha2/db_init.go
  pkg/db/v1alpha2/interface.go
  pkg/earlystopping/v1alpha1/medianstopping.go
  pkg/manager/modelstore/modeldb.go
  pkg/manager/v1alpha1/metricscollector/metricscollector.go
  pkg/suggestion/v1alpha1/grid_service.go
  pkg/suggestion/v1alpha1/hyperband_service.go
  pkg/suggestion/v1alpha1/random_service.go
  pkg/ui/v1alpha1/ui.go
  pkg/util/v1alpha2/metricscollector/metricscollector.go
  test/e2e/v1alpha1/test-client.go
Labels: approved, lgtm, size/XL

#547 Fix nil pointer error when create trial
  pkg/common/v1alpha2/common.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/util/status_util.go
Labels: approved, lgtm, size/S

#548 Adding minor styles changes
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
Labels: approved, lgtm, size/XS

#552 Adding test for random suggestion algorithm
  test/e2e/v1alpha2/test-katib-manager.py
Labels: approved, lgtm, size/S

#553 Fix trial requestNumber error
  pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
Labels: approved, lgtm, size/XS

#554 Add NAS RL yaml example for v1alpha2
  examples/v1alpha2/nasjob-example-RL.yaml
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
Labels: approved, lgtm, size/L

#550 Fix default metricsController wrong args
  manifests/v1alpha1/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
Labels: approved, lgtm, size/XS

#555 Add status for experiment and trial in additionalPrinterColumns
  manifests/v1alpha2/katib-controller/crds.yaml
Labels: approved, lgtm, size/S

#528 feat(trial): Refactor trial controller and add basic test cases
  Gopkg.lock
  manifests/v1alpha2/katib-controller/crd-experiment.yaml
  manifests/v1alpha2/katib-controller/crd-trial.yaml
  pkg/controller/v1alpha2/experiment/validator/validator_test.go
  pkg/controller/v1alpha2/trial/managerclient/managerclient.go
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/trial_controller_status.go
  pkg/controller/v1alpha2/trial/trial_controller_suite_test.go
  pkg/controller/v1alpha2/trial/trial_controller_test.go
  pkg/mock/v1alpha2/experiment/manifest/producer.go
  pkg/mock/v1alpha2/trial/managerclient/katibmanager.go
  scripts/mockgen.sh
  scripts/v1alpha1/deploy.sh
  scripts/v1alpha2/deploy.sh
  test/scripts/v1alpha1/unit-test.sh
  test/scripts/v1alpha2/unit-test.sh
  test/unit/v1alpha2/crds/pytorchjob_v1beta2.yaml
  test/unit/v1alpha2/crds/tfjob_v1beta2.yaml
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/ginkgo.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/ginkgo.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
Labels: approved, lgtm, size/XXL

#556 feat(experiment): Add test cases
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/controller/v1alpha2/experiment/experiment_controller_suite_test.go
  pkg/controller/v1alpha2/experiment/experiment_controller_test.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
  pkg/controller/v1alpha2/experiment/manifest/generator.go
  pkg/controller/v1alpha2/experiment/mutate_webhook.go
  pkg/controller/v1alpha2/experiment/util/manifest_util.go
  pkg/controller/v1alpha2/experiment/validation_webhook.go
  pkg/controller/v1alpha2/experiment/validator/validator.go
  pkg/controller/v1alpha2/experiment/validator/validator_test.go
  pkg/controller/v1alpha2/trial/trial_controller_test.go
  pkg/mock/v1alpha2/experiment/managerclient/managerclient.go
  pkg/mock/v1alpha2/experiment/suggestion/suggestion.go
  pkg/mock/v1alpha2/trial/managerclient/katibmanager.go
  pkg/util/v1alpha2/katibclient/katib_client.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/XL

#560 chore: Add code coverage test
  .travis.yml
  Makefile
  README.md
  pkg/api/operators/apis/experiment/v1alpha2/experiment_defaults.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha1/studyjob/manifest_parser.go
  pkg/controller/v1alpha2/experiment/manifest/generator_test.go
  pkg/controller/v1alpha2/trial/trial_controller.go
Labels: approved, lgtm, size/M

#562 Reducing the Prow workflow name length
  prow_config.yaml
Labels: approved, lgtm, size/XS

#559 Added metric name to GetObservationLogRequest
  cmd/manager/v1alpha2/main.go
  cmd/manager/v1alpha2/main_test.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.pb.gw.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/db/v1alpha2/interface.go
  pkg/db/v1alpha2/interface_test.go
  pkg/mock/v1alpha2/db/db.go
Labels: approved, lgtm, size/XL

#566 Change path for yaml file and NAS training containers
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/Dockerfile
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/README.md
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/cell.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/cell_classification.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/cell_init.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/cell_main.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/cifar10_input.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/evaluate.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/model_constructor.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/net.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/requirements.txt
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/run_trial.py
  examples/v1alpha1/NAS-training-containers/Envelopenet-cifar10/test.py
  examples/v1alpha1/NAS-training-containers/RL-cifar10/Dockerfile
  examples/v1alpha1/NAS-training-containers/RL-cifar10/ModelConstructor.py
  examples/v1alpha1/NAS-training-containers/RL-cifar10/RunTrial.py
  examples/v1alpha1/NAS-training-containers/RL-cifar10/op_library.py
  examples/v1alpha1/NAS-training-containers/RL-cifar10/requirements.txt
  examples/v1alpha1/nasjob-example-envelopenet.yaml
Labels: approved, lgtm, size/XS

#561 feat(experiment-validator): Inject client
  pkg/controller/v1alpha2/experiment/manifest/generator.go
  pkg/controller/v1alpha2/experiment/validation_webhook.go
  pkg/controller/v1alpha2/experiment/validator/validator.go
  pkg/mock/v1alpha2/experiment/manifest/producer.go
  pkg/mock/v1alpha2/util/katibclient/katibclient.go
  pkg/util/v1alpha2/katibclient/katib_client.go
Labels: approved, lgtm, size/M

#567 fix: Check if the deletion time is nil or zero
  pkg/api/operators/apis/experiment/v1alpha2/util.go
Labels: approved, lgtm, size/XS

#564 Implement trial observation metrics
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/trial/trial_controller_test.go
  pkg/controller/v1alpha2/trial/util/status_util.go
Labels: approved, lgtm, size/M

#568 refactor: Unify the interface
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/experiment/manifest/generator.go
  pkg/controller/v1alpha2/experiment/manifest/generator_test.go
  pkg/controller/v1alpha2/experiment/validator/validator.go
  pkg/controller/v1alpha2/experiment/validator/validator_test.go
  pkg/mock/v1alpha2/experiment/manifest/producer.go
Labels: approved, lgtm, size/M

#558 Implement GetExperimentInDB
  cmd/manager/v1alpha2/main.go
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.pb.gw.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/api/v1alpha2/python/api_pb2_grpc.py
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
  pkg/controller/v1alpha2/experiment/validator/validator.go
  pkg/controller/v1alpha2/experiment/validator/validator_test.go
  pkg/db/v1alpha2/interface.go
  pkg/mock/v1alpha2/api/manager.go
  pkg/mock/v1alpha2/db/db.go
  pkg/mock/v1alpha2/experiment/managerclient/managerclient.go
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/XXL

#571 Fix finalizer cannot work
  pkg/api/operators/apis/experiment/v1alpha2/util.go
Labels: approved, lgtm, size/XS

#572 Retain for job and metricsCollector
  pkg/api/operators/apis/trial/v1alpha2/trial_types.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/controller/v1alpha2/trial/trial_controller.go
Labels: approved, lgtm, size/M

#573 Adding go tools scripts - part 1
  cmd/manager/v1alpha1/main_test.go
  cmd/manager/v1alpha2/main_test.go
  hack/.golint_failures
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  pkg/common/v1alpha2/common.go
  pkg/common/v1alpha2/katib_manager_util.go
  pkg/controller/v1alpha1/studyjob/studyjob_controller.go
  pkg/db/v1alpha1/interface_test.go
  pkg/db/v1alpha2/interface_test.go
  pkg/suggestion/v1alpha1/hyperband_service_test.go
  test/e2e/v1alpha1/test-client.go
Labels: approved, lgtm, size/L

#569 refactor: Use manager client to get log for test
  pkg/controller/v1alpha2/trial/managerclient/managerclient.go
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/trial_controller_consts.go
  pkg/controller/v1alpha2/trial/trial_controller_test.go
  pkg/controller/v1alpha2/trial/trial_controller_util.go
  pkg/mock/v1alpha2/trial/managerclient/katibmanager.go
Labels: approved, lgtm, size/L

#563 feat(experiment): Add more test cases
  pkg/controller/v1alpha2/consts/const.go
  pkg/controller/v1alpha2/experiment/experiment_controller_test.go
  pkg/controller/v1alpha2/experiment/experiment_util.go
  pkg/mock/v1alpha2/experiment/manifest/generator.go
Labels: approved, lgtm, size/L

#575 Updated makefile by adding more targets for developer.
  Gopkg.lock
  Makefile
  docs/developer-guide.md
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/trial_controller_util.go
  vendor/github.com/awalterschulze/gographviz/CONTRIBUTORS
  vendor/github.com/awalterschulze/gographviz/analyse.go
  vendor/github.com/awalterschulze/gographviz/ast/ast.go
  vendor/github.com/awalterschulze/gographviz/attr.go
  vendor/github.com/awalterschulze/gographviz/escape.go
  vendor/github.com/awalterschulze/gographviz/graph.go
  vendor/github.com/awalterschulze/gographviz/internal/errors/errors.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/acttab.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/lexer.go
  vendor/github.com/awalterschulze/gographviz/internal/lexer/transitiontable.go
  vendor/github.com/awalterschulze/gographviz/internal/parser/parser.go
  vendor/github.com/awalterschulze/gographviz/internal/token/token.go
  vendor/github.com/awalterschulze/gographviz/nodes.go
  vendor/github.com/awalterschulze/gographviz/relations.go
  vendor/github.com/awalterschulze/gographviz/subgraphs.go
Labels: approved, lgtm, size/XXL

#576 Add categories for katib CRDs
  manifests/v1alpha1/studyjobcontroller/crd.yaml
  manifests/v1alpha2/katib-controller/crd-experiment.yaml
  manifests/v1alpha2/katib-controller/crd-trial.yaml
Labels: approved, lgtm, size/S

#570 feat(trial): Add more failure test cases
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/trial_controller_suite_test.go
  pkg/controller/v1alpha2/trial/trial_controller_test.go
Labels: approved, lgtm, size/L

#579 Added undeploy for katib.
  scripts/v1alpha1/undeploy.sh
  scripts/v1alpha2/undeploy.sh
Labels: approved, lgtm, size/M

#587 Change undeploy script
  scripts/v1alpha1/undeploy.sh
  scripts/v1alpha2/undeploy.sh
Labels: approved, lgtm, size/XS

#585 Default make target to v1alpha2.
  Makefile
  docs/developer-guide.md
Labels: approved, lgtm, size/M

#590 feat: Support flags in UI
  cmd/ui/v1alpha2/main.go
Labels: approved, lgtm, size/S

#594 Mini fix for getExperimentConf
  pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
Labels: approved, lgtm, size/S

#592 Reverse logic of Less in hyperband v1alpha1
  pkg/suggestion/v1alpha1/hyperband_service.go
  pkg/suggestion/v1alpha1/hyperband_service_test.go
Labels: approved, lgtm, size/S

#593 doc: Update readme
  README.md
  scripts/update-readme-toc.sh
Labels: approved, lgtm, size/L

#596 Fix issue of hyperband suggestion service cannot move on
  pkg/controller/v1alpha1/studyjob/studyjob_controller.go
  pkg/suggestion/v1alpha1/hyperband_service.go
Labels: approved, lgtm, size/M

#588 Check error in OpenSQLConnection
  pkg/db/v1alpha1/interface.go
  pkg/db/v1alpha2/interface.go
Labels: approved, lgtm, size/XS

#600 Mini fix for v1alpha1 metricsCollector
  pkg/manager/v1alpha1/metricscollector/metricscollector.go
Labels: approved, lgtm, size/XS

#601 Minor changes to metric collector manifest
  manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
Labels: approved, lgtm, size/XS

#603 Fixing latest tag
  test/scripts/v1alpha1/build-earlystopping-median.sh
  test/scripts/v1alpha1/build-manager-rest.sh
  test/scripts/v1alpha1/build-manager.sh
  test/scripts/v1alpha1/build-studyjobctr.sh
  test/scripts/v1alpha1/build-suggestion-bo.sh
  test/scripts/v1alpha1/build-suggestion-grid.sh
  test/scripts/v1alpha1/build-suggestion-hyperband.sh
  test/scripts/v1alpha1/build-suggestion-nasrl.sh
  test/scripts/v1alpha1/build-suggestion-random.sh
  test/scripts/v1alpha1/build-ui.sh
  test/scripts/v1alpha2/build-katib-controller.sh
  test/scripts/v1alpha2/build-manager-rest.sh
  test/scripts/v1alpha2/build-manager.sh
  test/scripts/v1alpha2/build-suggestion-random.sh
  test/scripts/v1alpha2/build-ui.sh
Labels: approved, lgtm, size/M

#602 Restructuring manifests
  manifests/v1alpha2/db/deployment.yaml
  manifests/v1alpha2/db/secret.yaml
  manifests/v1alpha2/db/service.yaml
  manifests/v1alpha2/manager-rest/deployment.yaml
  manifests/v1alpha2/manager-rest/service.yaml
  manifests/v1alpha2/manager/deployment.yaml
  manifests/v1alpha2/manager/service.yaml
  manifests/v1alpha2/pv/pv.yaml
  manifests/v1alpha2/pv/pvc.yaml
  manifests/v1alpha2/suggestion/random/deployment.yaml
  manifests/v1alpha2/suggestion/random/service.yaml
  manifests/v1alpha2/ui/deployment.yaml
  manifests/v1alpha2/ui/rbac.yaml
  manifests/v1alpha2/ui/service.yaml
  scripts/v1alpha2/deploy.sh
  scripts/v1alpha2/undeploy.sh
  test/scripts/v1alpha2/run-tests.sh
Labels: approved, lgtm, size/M

#605 Fine-grained docker image build.
  Makefile
  docs/developer-guide.md
  scripts/v1alpha2/build.sh
Labels: approved, lgtm, size/M

#606 fix make check
  pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
Labels: approved, lgtm, size/XS

#608 Enabled make check in travis.
  .travis.yml
Labels: approved, lgtm, size/XS

#609 Fix nasrl example in v1alpha2
  examples/v1alpha2/nasjob-example-RL.yaml
Labels: approved, lgtm, size/XS

#617 Skip creating trials if add count is zero
  pkg/controller/v1alpha2/experiment/experiment_controller.go
Labels: approved, lgtm, size/S

#618 go unit tests from presubmits
  test/scripts/v1alpha2/run-tests.sh
  test/scripts/v1alpha2/unit-test.sh
  test/workflows/components/workflows-v1alpha2.libsonnet
Labels: approved, lgtm, size/M

#616 Set trial completion status only after metric collection
  pkg/controller/v1alpha2/trial/trial_controller.go
  pkg/controller/v1alpha2/trial/trial_controller_util.go
Labels: approved, lgtm, size/M
