Repository kubeflow/katib, pull requests merged in 2019-12, with the labels that each got.

#947 Implement metrics custom filters
  README.md
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  docs/user-guide.md
  examples/v1alpha3/file-metrics-collector/mnist.py
  examples/v1alpha3/file-metricscollector-example.yaml
  pkg/metricscollector/v1alpha3/common/const.go
  pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/L

#938 Fix: Empty Trial templates in Katib UI
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/S

#937 update deployment api version
  manifests/v1alpha2/db/deployment.yaml
  manifests/v1alpha2/manager-rest/deployment.yaml
  manifests/v1alpha2/manager/deployment.yaml
  manifests/v1alpha2/suggestion/bayesianoptimization/deployment.yaml
  manifests/v1alpha2/suggestion/grid/deployment.yaml
  manifests/v1alpha2/suggestion/hyperband/deployment.yaml
  manifests/v1alpha2/suggestion/nasrl/deployment.yaml
  manifests/v1alpha2/suggestion/random/deployment.yaml
  manifests/v1alpha2/ui/deployment.yaml
  manifests/v1alpha3/db/deployment.yaml
  manifests/v1alpha3/manager/deployment.yaml
  manifests/v1alpha3/ui/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/M

#942 rename counter metrics
  pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
  pkg/controller.v1alpha3/trial/prometheus_metrics.go
Labels: approved, lgtm, ok-to-test, size/S

#951 Update API spec for early stopping
  Gopkg.lock
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/common/v1alpha3/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#949 Use kubeflowkatib repo as image repo of example
  examples/v1alpha3/bayesianoptimization-example.yaml
  examples/v1alpha3/custom-metricscollector-example.yaml
  examples/v1alpha3/file-metricscollector-example.yaml
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/hyperband-example.yaml
  examples/v1alpha3/random-example.yaml
  examples/v1alpha3/tpe-example.yaml
Labels: approved, lgtm, size/S

#894 feat: Support running
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_consts.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
  pkg/job/v1alpha3/job/job.go
  pkg/job/v1alpha3/kubeflow/kubeflow.go
Labels: approved, lgtm, size/M

#954 Add a gauge metric for current experiments
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
Labels: approved, lgtm, ok-to-test, size/L

#952 Resume experiment with extra trials from last checkpoint
  pkg/apis/controller/experiments/v1alpha3/util.go
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/util/v1alpha3/katibclient/katib_client.go
  test/e2e/v1alpha3/resume-e2e-experiment.go
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
Labels: approved, lgtm, size/L

#950 UI: Support namespace selection in experiment monitor
  cmd/ui/v1alpha3/main.go
  manifests/v1alpha3/ui/rbac.yaml
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/actions/nasMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/FilterPanel.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobMonitor.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/FilterPanel.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1alpha3/frontend/src/reducers/nasMonitor.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/XL

#957 Validate experiment
  pkg/controller.v1alpha3/experiment/util/status_util.go
  pkg/webhook/v1alpha3/experiment/validation_webhook.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/M

#967 Use port 8080 for Katib UI
  cmd/ui/v1alpha3/Dockerfile
  manifests/v1alpha3/ui/deployment.yaml
  manifests/v1alpha3/ui/service.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#965 Fix typo in getKabitJob function name
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/pod/utils.go
Labels: approved, lgtm, ok-to-test, size/XS

#962 User root user explicitely for DB readinessProbe
  manifests/v1alpha3/db/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#958 Increase Suggestion memory limit
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/mock/v1alpha3/experiment/manifest/generator.go
  pkg/util/v1alpha3/katibconfig/config.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/L

#969 Remove redundant serviceAccountName assignment
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/XS

#960 Use port higher than 1024 to be able to run as a non-root user
  cmd/katib-controller/v1alpha3/Dockerfile
  cmd/katib-controller/v1alpha3/main.go
  manifests/v1alpha3/katib-controller/katib-controller.yaml
  manifests/v1alpha3/katib-controller/service.yaml
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, ok-to-test, size/S

#974 add metrics for trial
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
  pkg/controller.v1alpha3/trial/prometheus_metrics.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/trial/trial_controller_test.go
  pkg/controller.v1alpha3/trial/trial_controller_util.go
Labels: approved, lgtm, ok-to-test, size/L

#980 feat(config): Add a new config for webhook
  cmd/katib-controller/v1alpha3/main.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/M

#986 feat(experiment_status): Add trial name
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
Labels: approved, lgtm, size/XS

#985 Get dbUser from Env or default('root')
  pkg/db/v1alpha3/common/const.go
  pkg/db/v1alpha3/mysql/mysql.go
Labels: approved, lgtm, ok-to-test, size/S

#989 add disk setting into suggestionConfiguration
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/util/v1alpha3/katibconfig/config.go
Labels: approved, lgtm, ok-to-test, size/M
