Repository kubeflow/katib, pull requests merged in 2019-02, with the labels that each got.

#363 Fix presubmits
  pkg/ui/ui.go
  test/scripts/build-earlystopping-median.sh
  test/scripts/build-manager-rest.sh
  test/scripts/build-manager.sh
  test/scripts/build-studyjobctr.sh
  test/scripts/build-suggestion-bo.sh
  test/scripts/build-suggestion-grid.sh
  test/scripts/build-suggestion-hyperband.sh
  test/scripts/build-suggestion-random.sh
  test/scripts/build-ui.sh
Labels: approved, lgtm, size/S

#368 fix invalid memory address
  pkg/controller/studyjob/manifest_parser.go
Labels: approved, lgtm, size/M

#369 Include go dependencies in developer-guide.md
  docs/developer-guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#360 Properly initialize CI cluster credential
  test/scripts/run-tests.sh
  test/scripts/unit-test.sh
Labels: approved, lgtm, ok-to-test, size/M

#376 Upgrading controller runtime and k8s to 1.11.2
  Gopkg.lock
  Gopkg.toml
  pkg/controller/studyjob/pod_control.go
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, size/L

#378 fix wrong example
  examples/README.md
  examples/gpu-example.yaml
  examples/grid-example.yaml
  examples/hypb-example.yaml
Labels: approved, lgtm, size/L

#379 add studyjob python client
  py/study_job_client.py
Labels: approved, lgtm, size/L

#345 Training Container with Model Constructor for cifar10
  examples/NAS-training-containers/cifar10/Dockerfile
  examples/NAS-training-containers/cifar10/ModelConstructor.py
  examples/NAS-training-containers/cifar10/RunTrial.py
  examples/NAS-training-containers/cifar10/op_library.py
  examples/NAS-training-containers/cifar10/requirements.txt
Labels: approved, lgtm, size/L

#389 show studyjob condition when run kubectl get
  manifests/studyjobcontroller/crd.yaml
Labels: approved, lgtm, size/XS

#391 Delete modeldb from unit tests
  cmd/manager/main_test.go
  pkg/db/interface_test.go
  test/scripts/create-cluster.sh
Labels: approved, lgtm, size/S

#387 Removing Operator specific handling during a StudyJob run
  pkg/controller/studyjob/studyjob_controller.go
  pkg/controller/studyjob/utils.go
Labels: approved, lgtm, size/L

#383 add validating webhook for studyJob
  manifests/studyjobcontroller/rbac.yaml
  manifests/studyjobcontroller/service.yaml
  manifests/studyjobcontroller/studyjobcontroller.yaml
  pkg/controller/studyjob/katib_api_util.go
  pkg/controller/studyjob/studyjob_controller.go
  pkg/controller/studyjob/utils.go
  pkg/controller/studyjob/validating_webhook.go
  test/e2e/invalid-studyjob.yaml
  test/e2e/valid-studyjob.yaml
  test/scripts/run-tests.sh
Labels: approved, lgtm, size/L

#339 Suggestion for Neural Architecture Search with Reinforcement Learning
  cmd/suggestion/nasrl/Dockerfile
  cmd/suggestion/nasrl/requirements.txt
  pkg/suggestion/NAS_Reinforcement_Learning/Controller.py
  pkg/suggestion/NAS_Reinforcement_Learning/LSTM.py
  pkg/suggestion/NAS_Reinforcement_Learning/Operation.py
  pkg/suggestion/NAS_Reinforcement_Learning/README.md
  pkg/suggestion/NAS_Reinforcement_Learning/SuggestionParam.py
  pkg/suggestion/NAS_Reinforcement_Learning/Trainer.py
  pkg/suggestion/NAS_Reinforcement_Learning/example.png
  pkg/suggestion/nasrl_service.py
Labels: approved, lgtm, size/XL

#394 Database APIs for NAS updated
  cmd/manager/main.go
  cmd/manager/main_test.go
  pkg/db/db_init.go
  pkg/db/interface.go
  pkg/db/interface_test.go
  pkg/db/test/test.go
  pkg/earlystopping/medianstopping.go
  pkg/mock/db/db.go
Labels: approved, lgtm, size/L

#401 add build and test for suggestion nasrl
  manifests/vizier/suggestion/nasrl/deployment.yaml
  manifests/vizier/suggestion/nasrl/service.yaml
  scripts/build.sh
  scripts/deploy.sh
  test/scripts/build-suggestion-nasrl.sh
  test/scripts/run-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#409 add latest tag for katib images
  test/scripts/build-earlystopping-median.sh
  test/scripts/build-manager-rest.sh
  test/scripts/build-manager.sh
  test/scripts/build-studyjobctr.sh
  test/scripts/build-suggestion-bo.sh
  test/scripts/build-suggestion-grid.sh
  test/scripts/build-suggestion-hyperband.sh
  test/scripts/build-suggestion-nasrl.sh
  test/scripts/build-suggestion-random.sh
  test/scripts/build-ui.sh
Labels: approved, lgtm, size/S

#405 Metric collector must fail on error
  cmd/metricscollector/main.go
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
Labels: approved, lgtm, size/XS

#410 Add create time to Trial API
  pkg/api/api.pb.go
  pkg/api/api.proto
  pkg/api/api.swagger.json
  pkg/api/gen-doc/api.md
  pkg/api/gen-doc/index.html
  pkg/api/python/api_pb2.py
  pkg/db/interface.go
  pkg/db/interface_test.go
Labels: approved, lgtm, size/XL

#393 Add separable/depthwise convolution, data augmentation and multiple GPU support
  examples/NAS-training-containers/cifar10/ModelConstructor.py
  examples/NAS-training-containers/cifar10/RunTrial.py
  examples/NAS-training-containers/cifar10/op_library.py
  examples/nasjob-example-RL.yaml
Labels: approved, lgtm, size/L

#404 Add support for parallel studyjobs
  pkg/suggestion/NAS_Reinforcement_Learning/Controller.py
  pkg/suggestion/NAS_Reinforcement_Learning/README.md
  pkg/suggestion/nasrl_service.py
Labels: approved, lgtm, size/L
