Repository kubeflow/katib, pull requests merged in 2019-08, with the labels that each got.

#697 API for metricCollector
  pkg/api/operators/apis/addtoscheme_katib_v1alpha2.go
  pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
  pkg/api/operators/apis/experiment/v1alpha2/zz_generated.deepcopy.go
  pkg/api/operators/apis/trial/v1alpha2/trial_types.go
Labels: approved, lgtm, size/L

#711 Refactor webhook organization
  cmd/katib-controller/v1alpha2/main.go
  pkg/controller/v1alpha2/experiment/experiment_controller.go
  pkg/webhook/v1alpha2/experiment/mutate_webhook.go
  pkg/webhook/v1alpha2/experiment/validation_webhook.go
  pkg/webhook/v1alpha2/experiment/validator/validator.go
  pkg/webhook/v1alpha2/experiment/validator/validator_test.go
  pkg/webhook/v1alpha2/webhook.go
Labels: approved, lgtm, size/L

#720 Update test worker image
  test/workflows/components/workflows-v1alpha2.libsonnet
Labels: approved, lgtm, size/XS

#721 Update prow
  prow_config.yaml
Labels: approved, lgtm, size/XS

#729 Inject pod sidecar for specified namespace
  pkg/webhook/v1alpha2/webhook.go
Labels: approved, lgtm, size/S

#731 Fix bayesianoptimization build for ppc64le
  cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
Labels: approved, lgtm, size/XS

#730 fix: Add build for sidecar
  scripts/v1alpha2/build.sh
  test/scripts/v1alpha2/build-katib-controller.sh
Labels: approved, lgtm, size/XS

#733 Inject sidecar only for katib belongs
  pkg/webhook/v1alpha2/pod/inject_webhook.go
  pkg/webhook/v1alpha2/webhook.go
Labels: approved, lgtm, size/M
