Repository kubeflow/katib, pull requests merged in 2019-03, with the labels that each got.

#415 Fix path to API protobuf in developer guide
  docs/developer-guide.md
Labels: approved, lgtm, size/XS

#398 Add validation for NAS job in Katib controller
  cmd/manager/main.go
  pkg/api/api.pb.go
  pkg/api/api.pb.gw.go
  pkg/api/api.proto
  pkg/api/api.swagger.json
  pkg/api/gen-doc/api.md
  pkg/api/gen-doc/index.html
  pkg/api/python/api_pb2.py
  pkg/api/python/api_pb2_grpc.py
  pkg/controller/studyjob/katib_api_util.go
  pkg/mock/api/manager.go
  pkg/mock/api/suggestion.go
  pkg/mock/db/db.go
  pkg/suggestion/NAS_Reinforcement_Learning/Operation.py
  pkg/suggestion/grid_service.go
  pkg/suggestion/hyperband_service.go
  pkg/suggestion/nasrl_service.py
  pkg/suggestion/random_service.go
Labels: approved, lgtm, size/XXL

#418 Fix the package version in training container
  examples/NAS-training-containers/cifar10/requirements.txt
Labels: approved, lgtm, size/XS

#416 Multiple Trials for Reinforcement Learning Suggestion
  examples/nasjob-example-RL.yaml
  pkg/suggestion/NAS_Reinforcement_Learning/Controller.py
  pkg/suggestion/NAS_Reinforcement_Learning/README.md
  pkg/suggestion/NAS_Reinforcement_Learning/SuggestionParam.py
  pkg/suggestion/nasrl_service.py
Labels: approved, lgtm, size/L

#419 Add NAS team as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#381 Katib v1alpha2 API for CRDs
  pkg/api/operators/apis/experiment/v1alpha2/types.go
  pkg/api/operators/apis/trial/v1alpha2/types.go
Labels: approved, lgtm, size/L

#406 Test for Bayesian Optimization Algo
  .gitignore
  pkg/suggestion/__init__.py
  pkg/suggestion/bayesianoptimization/src/acquisition_func.py
  pkg/suggestion/bayesianoptimization/src/acquisition_func/acquisition_func.py
  pkg/suggestion/bayesianoptimization/src/algorithm_manager.py
  pkg/suggestion/bayesianoptimization/src/bayesian_optimization_algorithm.py
  pkg/suggestion/bayesianoptimization/src/global_optimizer.py
  pkg/suggestion/bayesianoptimization/src/model/gp.py
  pkg/suggestion/bayesianoptimization/src/model/rf.py
  pkg/suggestion/bayesianoptimization/src/utils.py
  pkg/suggestion/test_requirements.txt
  pkg/suggestion/tests/__init__.py
  pkg/suggestion/tests/conftest.py
  pkg/suggestion/tests/parameter_values.yaml
  pkg/suggestion/tests/study_config.yaml
  pkg/suggestion/tests/test_acquisition_function.py
  pkg/suggestion/tests/test_algorithm_manager.py
  pkg/suggestion/tests/test_boa.py
  pkg/suggestion/tests/test_global_optimizer.py
  pkg/suggestion/tests/test_models.py
  pkg/suggestion/tests/test_requirements.txt
  setup.py
  test/scripts/python-tests.sh
  test/scripts/run-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/XL

#424 Add fault tolerance support for trial failure
  pkg/suggestion/NAS_Reinforcement_Learning/README.md
  pkg/suggestion/nasrl_service.py
Labels: approved, lgtm, size/M

#434 fix demo link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#432 Change datadir for avoid failure due to lost+found
  manifests/vizier/db/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#436 Remove katibcli
  .gitignore
  cmd/cli/Dockerfile
  cmd/cli/command/create-study.go
  cmd/cli/command/create.go
  cmd/cli/command/get-model.go
  cmd/cli/command/get-study.go
  cmd/cli/command/get.go
  cmd/cli/command/pull-study.go
  cmd/cli/command/pull.go
  cmd/cli/command/push-model.go
  cmd/cli/command/push-study.go
  cmd/cli/command/push.go
  cmd/cli/command/root.go
  cmd/cli/command/type.go
  cmd/cli/katibctl.go
  docs/CLI/katib-cli.md
  docs/CLI/katib-cli_create.md
  docs/CLI/katib-cli_create_study.md
  docs/CLI/katib-cli_get.md
  docs/CLI/katib-cli_get_model.md
  docs/CLI/katib-cli_get_studies.md
  docs/CLI/katib-cli_pull.md
  docs/CLI/katib-cli_pull_studies.md
  docs/CLI/katib-cli_push.md
  docs/CLI/katib-cli_push_study.md
  docs/CLI/katib-cli_stop.md
  docs/CLI/katib-cli_stop_study.md
  examples/README.md
  hack/boilerplate.go.txt
  hack/docgen.go
  hack/gen-doc.sh
  scripts/build.sh
  test/scripts/build-cli.sh
  test/scripts/unit-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/XXL

#427 add v1alpha2 grpc api
  pkg/api/v1alpha2/Makefile
  pkg/api/v1alpha2/api.pb.go
  pkg/api/v1alpha2/api.pb.gw.go
  pkg/api/v1alpha2/api.proto
  pkg/api/v1alpha2/api.swagger.json
  pkg/api/v1alpha2/build.sh
  pkg/api/v1alpha2/gen-doc/Dockerfile
  pkg/api/v1alpha2/gen-doc/api.md
  pkg/api/v1alpha2/gen-doc/index.html
  pkg/api/v1alpha2/health/health.pb.go
  pkg/api/v1alpha2/health/health.proto
  pkg/api/v1alpha2/health/health.swagger.json
  pkg/api/v1alpha2/python/api_pb2.py
  pkg/api/v1alpha2/python/api_pb2_grpc.py
  pkg/api/v1alpha2/python/health/health_pb2.py
  pkg/api/v1alpha2/python/health/health_pb2_grpc.py
  pkg/db/v1alpha2/db_init.go
  pkg/db/v1alpha2/interface.go
Labels: approved, lgtm, size/XXL

#444 Remove redundant lock
  pkg/controller/studyjob/studyjob_controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#446 Updating the pytorch example image
  examples/pytorchjob-example.yaml
Labels: approved, lgtm, size/XS

#447 Fix labels matching the job operator implementation
  pkg/manager/metricscollector/metricscollector.go
Labels: approved, lgtm, size/XS
