Repository kubeflow/katib, pull requests merged in 2019-01, with the labels that each got.

#312 add bestTrialId to statusJob status
  cmd/manager/main.go
  pkg/api/api.pb.go
  pkg/api/api.pb.gw.go
  pkg/api/api.proto
  pkg/api/api.swagger.json
  pkg/api/gen-doc/api.md
  pkg/api/gen-doc/index.html
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
  pkg/api/python/api_pb2.py
  pkg/api/python/api_pb2_grpc.py
  pkg/controller/studyjob/studyjob_controller.go
  pkg/controller/studyjob/utils.go
  pkg/mock/api/manager.go
  pkg/mock/db/db.go
Labels: approved, lgtm, size/XXL

#315 delete obsolete data in db
  cmd/manager/main.go
  pkg/api/api.pb.go
  pkg/api/api.pb.gw.go
  pkg/api/api.proto
  pkg/api/api.swagger.json
  pkg/api/gen-doc/api.md
  pkg/api/gen-doc/index.html
  pkg/api/python/api_pb2.py
  pkg/api/python/api_pb2_grpc.py
  pkg/controller/studyjob/katib_api_util.go
  pkg/controller/studyjob/studyjob_controller.go
  pkg/controller/studyjob/utils.go
  pkg/db/db_init.go
  pkg/mock/api/manager.go
  test/e2e/test-client.go
Labels: approved, lgtm, size/XXL

#307 Minor fixes
  pkg/manager/metricscollector/metricscollector.go
  scripts/deploy.sh
Labels: approved, lgtm, size/XS

#309 Adding distributed pytorch example for katib
  examples/pytorchjob-example.yaml
Labels: approved, lgtm, size/M

#324 katib should be able to be deployed in any namespace
  cmd/metricscollector/main.go
  manifests/studyjobcontroller/metricsControllerConfigMap.yaml
  manifests/studyjobcontroller/studyjobcontroller.yaml
  pkg/controller/studyjob/manifest_parser.go
  pkg/types.go
Labels: approved, lgtm, size/M

#320 Add xgboost example using Bayesian optimization
  examples/xgboost-bayesian-example.yaml
Labels: approved, lgtm, size/M

#330 Fix typo in json API
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
Labels: approved, lgtm, size/XS

#329 Update pytorch example with latest image
  examples/pytorchjob-example.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#336 omit empty fields for studyjob status
  pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
Labels: approved, lgtm, size/XS

#342 only try to delete study info in db when in need
  pkg/controller/studyjob/katib_api_util.go
Labels: approved, lgtm, size/XS

#333 Clarify the example UI is generated by random-example.
  README.md
Labels: approved, lgtm, size/XS

#350 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
