Repository kubeflow/katib, pull requests merged in 2019-11, with the labels that each got.

#904 Validate algorithm
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/mock/v1alpha3/experiment/manifest/generator.go
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/util/v1alpha3/katibclient/katib_client.go
  pkg/util/v1alpha3/katibconfig/config.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  pkg/webhook/v1alpha3/pod/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/L

#907 fix: Add Suggestion into CI
  cmd/suggestion/chocolate/v1alpha3/Dockerfile
  cmd/suggestion/hyperband/v1alpha3/Dockerfile
  cmd/suggestion/hyperopt/v1alpha3/Dockerfile
  cmd/suggestion/nasrl/v1alpha3/Dockerfile
  cmd/suggestion/skopt/v1alpha3/Dockerfile
  test/scripts/v1alpha3/build-suggestion-chocolate.sh
  test/scripts/v1alpha3/build-suggestion-hyperband.sh
  test/scripts/v1alpha3/build-suggestion-hyperopt.sh
  test/scripts/v1alpha3/build-suggestion-nasrl.sh
  test/scripts/v1alpha3/build-suggestion-skopt.sh
Labels: approved, lgtm, size/S

#893 support ppc64le
  cmd/manager/v1alpha3/Dockerfile
  cmd/suggestion/chocolate/v1alpha3/Dockerfile
  cmd/suggestion/hyperband/v1alpha3/Dockerfile
  cmd/suggestion/hyperopt/v1alpha3/Dockerfile
  cmd/suggestion/nasrl/v1alpha3/Dockerfile
  cmd/suggestion/skopt/v1alpha3/Dockerfile
Labels: approved, lgtm, size/M

#908 Support custom metrics collector kind
  cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
  cmd/suggestion/grid/v1alpha2/Dockerfile
  cmd/suggestion/hyperband/v1alpha2/Dockerfile
  cmd/suggestion/random/v1alpha2/Dockerfile
  examples/v1alpha3/custom-metricscollector-example.yaml
  pkg/webhook/v1alpha3/pod/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  test/scripts/v1alpha3/run-custom-metricscollector.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/L

#909 Enhance validation for metrics collector
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/metricscollector/v1alpha3/common/const.go
  pkg/mock/v1alpha3/experiment/manifest/generator.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Labels: approved, lgtm, size/M

#910 feat: Support custom databases
  pkg/db/v1alpha3/common/const.go
  pkg/db/v1alpha3/mysql/mysql.go
Labels: approved, lgtm, size/S

#897 Enable arm64 architecture support for katib images and fix grpc health probe multiarch error.
  cmd/katib-controller/v1alpha2/Dockerfile
  cmd/katib-controller/v1alpha3/Dockerfile
  cmd/manager-rest/v1alpha2/Dockerfile
  cmd/manager/v1alpha2/Dockerfile
  cmd/manager/v1alpha3/Dockerfile
  cmd/metricscollector/v1alpha2/Dockerfile
  cmd/metricscollector/v1alpha3/file-metricscollector/Dockerfile
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile.aarch64
  cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
  cmd/suggestion/chocolate/v1alpha3/Dockerfile
  cmd/suggestion/grid/v1alpha2/Dockerfile
  cmd/suggestion/hyperband/v1alpha2/Dockerfile
  cmd/suggestion/hyperband/v1alpha3/Dockerfile
  cmd/suggestion/hyperopt/v1alpha3/Dockerfile
  cmd/suggestion/nasrl/v1alpha2/Dockerfile.aarch64
  cmd/suggestion/nasrl/v1alpha3/Dockerfile
  cmd/suggestion/nasrl/v1alpha3/Dockerfile.aarch64
  cmd/suggestion/random/v1alpha2/Dockerfile
  cmd/suggestion/skopt/v1alpha3/Dockerfile
  cmd/tfevent-metricscollector/v1alpha2/Dockerfile.aarch64
  cmd/ui/v1alpha2/Dockerfile
  cmd/ui/v1alpha3/Dockerfile
  scripts/v1alpha2/build.sh
  scripts/v1alpha3/build.sh
Labels: approved, lgtm, ok-to-test, size/L

#911 Fix wrong suggestion service endpoint
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
Labels: approved, lgtm, size/XS

#913 Fix grid suggestion ValidateAlgorithmSettings return
  pkg/suggestion/v1alpha3/chocolate_service.py
Labels: approved, lgtm, size/XS

#912 tfevent-metricscollector support ppc64le
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile.ppc64le
  scripts/v1alpha3/build.sh
Labels: approved, lgtm, size/XS

#920 Tfevent metriccollector fails when multiple files exist
  pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py
Labels: approved, lgtm, size/XS

#925 Support multiple metric logs in one line
  examples/v1alpha3/file-metrics-collector/mnist.py
  examples/v1alpha3/file-metricscollector-example.yaml
  pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
Labels: approved, lgtm, size/M

#932 feat: Add limit for suggestion pod
  pkg/controller.v1alpha3/suggestion/composer/composer.go
Labels: approved, lgtm, size/M

#933 Change web failPolicy to fail instead of default ingore
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/XS

#935 Remove katib webhook when undeploy
  scripts/v1alpha3/deploy.sh
  scripts/v1alpha3/undeploy.sh
Labels: approved, lgtm, size/XS
