Repository kubeflow/katib, pull requests merged in 2020-04, with the labels that each got.

#1113 UI: Change style for submit Experiment from YAML
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/YAML.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/YAML.jsx
Labels: approved, lgtm, size/M

#1114 UI: Close menu on click
  docs/developer-guide.md
  pkg/ui/v1alpha3/README.md
  pkg/ui/v1alpha3/frontend/src/components/Menu/Menu.jsx
  pkg/ui/v1alpha3/frontend/src/components/Menu/Snack.jsx
Labels: approved, lgtm, size/M

#1118 Fix Katib e2e tests
  test/scripts/v1alpha3/run-custom-metricscollector.sh
  test/scripts/v1alpha3/run-file-metricscollector.sh
  test/scripts/v1alpha3/run-pytorchjob.sh
  test/scripts/v1alpha3/run-suggestion-bayesian.sh
  test/scripts/v1alpha3/run-suggestion-grid.sh
  test/scripts/v1alpha3/run-suggestion-hyperband.sh
  test/scripts/v1alpha3/run-suggestion-nasrl.sh
  test/scripts/v1alpha3/run-suggestion-random.sh
  test/scripts/v1alpha3/run-suggestion-tpe.sh
  test/scripts/v1alpha3/run-tfjob.sh
Labels: approved, lgtm, size/M

#1117 UI: Remove antd package
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/src/components/App.jsx
  pkg/ui/v1alpha3/frontend/src/components/Common/Create/TabPanel.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HP.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/YAML.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobMonitor.jsx
  pkg/ui/v1alpha3/frontend/src/components/Menu/Header.jsx
  pkg/ui/v1alpha3/frontend/src/components/Menu/Main.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/NAS.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/YAML.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobMonitor.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobStepInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/constants/constants.js
Labels: approved, lgtm, size/L

#1123 Support step for int parameter in Chocolate and Hyperopt Suggestion
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/search_space.py
Labels: approved, lgtm, size/S

#1116 Optimize Chocolate Suggestion
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/chocolate_service.py
Labels: approved, lgtm, size/L

#1121 feat: Add 2020 roadmap
  ROADMAP.md
Labels: approved, lgtm, size/M

#1129 Add ENAS enhancements to ROADMAP
  ROADMAP.md
Labels: approved, lgtm, size/XS

#1130 Fix NotImplementedError for TPE and Random suggestion.
  pkg/suggestion/v1alpha3/hyperopt_service.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1132 Bump up the Go version to 1.14.2 at Travis CI
  .travis.yml
  hack/verify-gofmt.sh
Labels: approved, lgtm, ok-to-test, size/XS

#1138 Fix typo in suggestion packages
  ROADMAP.md
  pkg/suggestion/v1alpha3/chocolate_service.py
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/search_space.py
  pkg/suggestion/v1alpha3/skopt_service.py
Labels: approved, lgtm, size/S

#1137 Refactor file-metricscollector
  cmd/metricscollector/v1alpha3/file-metricscollector/main.go
  pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
Labels: approved, lgtm, size/M

#1139 Remove Anneal from supported algorithms
  docs/proposals/suggestion.md
Labels: approved, lgtm, size/XS

#1133 Fix duplicated imports
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/chocolate_service.py
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/__init__.py
  pkg/suggestion/v1alpha3/internal/constant.py
  pkg/suggestion/v1alpha3/internal/search_space.py
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
  pkg/suggestion/v1alpha3/skopt_service.py
Labels: approved, lgtm, size/M

#1134 Refactor NAS RL Suggestion
  examples/v1alpha3/NAS-training-containers/RL-cifar10/RunTrial.py
  examples/v1alpha3/nasjob-example-RL-cpu.yaml
  examples/v1alpha3/nasjob-example-RL-gpu.yaml
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/AlgorithmSettings.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Controller.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/LSTM.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Operation.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/README.md
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Trainer.py
  pkg/suggestion/v1alpha3/nasrl_service.py
  test/suggestion/v1alpha3/test_nasrl_service.py
Labels: approved, lgtm, size/XXL

#1142 Update ENAS Algorithm Settings in Katib UI
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/AlgorithmSettings.py
  pkg/ui/v1alpha3/frontend/.prettierrc.yaml
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/M

#1143 Change folder structure for NAS algorithms, rename NASRL to ENAS
  .dockerignore
  README.md
  cmd/suggestion/nas/enas/v1alpha3/Dockerfile
  cmd/suggestion/nas/enas/v1alpha3/Dockerfile.aarch64
  cmd/suggestion/nas/enas/v1alpha3/main.py
  cmd/suggestion/nas/enas/v1alpha3/requirements.txt
  docs/new-algorithm-service.md
  examples/v1alpha3/README.md
  examples/v1alpha3/nas/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1alpha3/nas/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1alpha3/nas/enas-cnn-cifar10/ModelConstructor.py
  examples/v1alpha3/nas/enas-cnn-cifar10/RunTrial.py
  examples/v1alpha3/nas/enas-cnn-cifar10/op_library.py
  examples/v1alpha3/nas/enas-cnn-cifar10/requirements-cpu.txt
  examples/v1alpha3/nas/enas-cnn-cifar10/requirements-gpu.txt
  examples/v1alpha3/nas/enas-example-cpu.yaml
  examples/v1alpha3/nas/enas-example-gpu.yaml
  manifests/v1alpha3/katib-controller/katib-config.yaml
  manifests/v1alpha3/katib-controller/trialTemplateConfigmapLabeled.yaml
  pkg/suggestion/v1alpha3/nas/enas/AlgorithmSettings.py
  pkg/suggestion/v1alpha3/nas/enas/Controller.py
  pkg/suggestion/v1alpha3/nas/enas/Operation.py
  pkg/suggestion/v1alpha3/nas/enas/README.md
  pkg/suggestion/v1alpha3/nas/enas/example.png
  pkg/suggestion/v1alpha3/nas/enas_service.py
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
  prow_config.yaml
  scripts/v1alpha3/build.sh
  test/scripts/v1alpha3/build-suggestion-enas.sh
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/python-tests.sh
  test/scripts/v1alpha3/run-suggestion-enas.sh
  test/suggestion/v1alpha3/test_enas_service.py
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/L

#1146 ENAS Check Algorithm Settings in Validate Function
  pkg/suggestion/v1alpha3/nas/enas/AlgorithmSettings.py
  pkg/suggestion/v1alpha3/nas/enas_service.py
Labels: approved, lgtm, size/L

#1141 katib ui: adapt environment in which cluster role is unavailable
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/hp.go
  pkg/ui/v1alpha3/nas.go
  pkg/ui/v1alpha3/util.go
Labels: approved, lgtm, size/M

#1149 Support Categorical string values in Chocolate Suggestion
  examples/v1alpha3/grid-example.yaml
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
Labels: approved, lgtm, size/M

#1153 ENAS enable to add None values in algorithm settings
  pkg/suggestion/v1alpha3/nas/enas/AlgorithmSettings.py
  pkg/suggestion/v1alpha3/nas/enas/Controller.py
  pkg/suggestion/v1alpha3/nas/enas_service.py
Labels: approved, lgtm, size/S

#1155 Add an example of Goptuna suggestion service
  examples/v1alpha3/cmaes-example.yaml
Labels: approved, lgtm, size/M

#1154 Build Goptuna Suggestion image in CI
  manifests/v1alpha3/katib-controller/katib-config.yaml
  prow_config.yaml
  test/scripts/v1alpha3/build-suggestion-goptuna.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/M

#1157 E2E test for CMA-ES Suggestion
  test/scripts/v1alpha3/run-suggestion-cmaes.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/M

#1158 Remove Suggestion Request from Update Suggestion
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_controller_test.go
  pkg/controller.v1alpha3/experiment/suggestion/fake/fake.go
  pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
  pkg/mock/v1alpha3/experiment/suggestion/suggestion.go
Labels: approved, lgtm, size/S

#1145 Add support Kubeflow operators to ROADMAP
  ROADMAP.md
Labels: approved, lgtm, size/XS

#1162 UI: Suggestion view from Experiment page
  cmd/ui/v1alpha3/main.go
  manifests/v1alpha3/ui/rbac.yaml
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/components/Common/ExperimentInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/Common/SuggestionInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/nas.go
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/L

#1161 restructure algorithm configuration for hyperopt_service
  pkg/suggestion/v1alpha3/hyperopt/base_service.py
  pkg/suggestion/v1alpha3/hyperopt/service.py
  test/suggestion/v1alpha3/test_hyperopt_service.py
Labels: approved, lgtm, size/L

#1164 Rename chocolate algorithm names for consistency
  pkg/suggestion/v1alpha3/chocolate/base_service.py
  pkg/suggestion/v1alpha3/chocolate/service.py
Labels: approved, lgtm, size/S

#1172 Fix Cuda version in training container for ENAS
  examples/v1alpha3/nas/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1alpha3/nas/enas-example-cpu.yaml
  examples/v1alpha3/nas/enas-example-gpu.yaml
Labels: approved, lgtm, size/S

#1150 Delete Suggestion deployment after Experiment is finished
  pkg/apis/controller/experiments/v1alpha3/constants.go
  pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/v1alpha3/openapi_generated.go
  pkg/apis/v1alpha3/swagger.json
  pkg/controller.v1alpha3/experiment/experiment_controller.go
  pkg/controller.v1alpha3/experiment/experiment_util.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller_util.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  test/e2e/v1alpha3/resume-e2e-experiment.go
  test/e2e/v1alpha3/run-e2e-experiment.go
Labels: approved, lgtm, size/L
