Repository kubeflow/katib, pull requests merged in 2020-01, with the labels that each got.

#964 Initialize securityContext in injected metrics container
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, ok-to-test, size/XS

#994 feat: Add a flag to control the logic about sc
  cmd/katib-controller/v1alpha3/main.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/M

#982 UI: Select namespace from Kubeflow dashboard
  pkg/ui/v1alpha3/frontend/public/index.html
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/CommonMeta.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/YAML.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/FilterPanel.jsx
  pkg/ui/v1alpha3/frontend/src/components/KubeflowDashboard.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/CommonMeta.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/YAML.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/FilterPanel.jsx
  pkg/ui/v1alpha3/frontend/src/index.js
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1alpha3/frontend/src/reducers/nasMonitor.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
Labels: approved, lgtm, size/L

#996 fix: Ignore the failure
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/XS

#991 feat: Support resource in sidecar
  cmd/katib-controller/v1alpha3/main.go
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/experiment/manifest/generator.go
  pkg/util/v1alpha3/katibconfig/config.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/webhook.go
Labels: approved, lgtm, size/L

#990 Moved some content and added links to Kubeflow docs
  README.md
  docs/algorithm-settings.md
  docs/developer-guide.md
  docs/quick-start.md
  docs/user-guide.md
  docs/workflow-design.md
Labels: approved, lgtm, size/L

#998 fix: Inherit labels and annotations from experiment
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/util/labels.go
Labels: approved, lgtm, size/M

#1001 Fixed a few typos
  docs/workflow-design.md
Labels: approved, lgtm, size/XS

#1003 Updated links to docs/github on Katib dashboard
  pkg/ui/v1alpha3/frontend/src/components/Menu/Main.jsx
Labels: approved, lgtm, size/XS

#999 CPU example for NAS RL cifar10 training container
  .dockerignore
  examples/v1alpha3/NAS-training-containers/RL-cifar10/Dockerfile.cpu
  examples/v1alpha3/NAS-training-containers/RL-cifar10/Dockerfile.gpu
  examples/v1alpha3/NAS-training-containers/RL-cifar10/requirements-cpu.txt
  examples/v1alpha3/NAS-training-containers/RL-cifar10/requirements-gpu.txt
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/nasjob-example-RL.yaml
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/internal/trial.py
  pkg/suggestion/v1alpha3/nasrl_service.py
Labels: approved, lgtm, size/L

#1006 Rename katib DB manager
  README.md
  cmd/db-manager/v1alpha3/Dockerfile
  cmd/db-manager/v1alpha3/main.go
  cmd/db-manager/v1alpha3/main_test.go
  cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
  docs/proposals/metrics-collector.md
  docs/proposals/suggestion.md
  examples/v1alpha3/README.md
  examples/v1alpha3/custom-metricscollector-example.yaml
  manifests/v1alpha3/db-manager/deployment.yaml
  manifests/v1alpha3/db-manager/service.yaml
  manifests/v1alpha3/mysql-db/deployment.yaml
  manifests/v1alpha3/mysql-db/secret.yaml
  manifests/v1alpha3/mysql-db/service.yaml
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/db/v1alpha3/common/const.go
  pkg/ui/v1alpha3/backend.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  prow_config.yaml
  scripts/v1alpha3/build.sh
  scripts/v1alpha3/deploy.sh
  scripts/v1alpha3/undeploy.sh
  test/scripts/v1alpha3/build-manager.sh
  test/scripts/v1alpha3/check-katib-ready.sh
  test/scripts/v1alpha3/create-cluster.sh
Labels: approved, lgtm, size/L

#1009 Fix number of Trials problem in NAS RL Suggestion
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/AlgorithmSettings.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Controller.py
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Trainer.py
  pkg/suggestion/v1alpha3/nasrl_service.py
Labels: approved, lgtm, size/M

#1008 Add NAS RL training container to kubeflowkatib repository
  examples/v1alpha3/README.md
  examples/v1alpha3/nasjob-example-RL.yaml
  test/scripts/v1alpha3/build-tc-nasrl-cifar10.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
Labels: approved, lgtm, size/M

#970 Example with collecting timestamp of the metrics
  examples/v1alpha3/bayesianoptimization-example.yaml
  examples/v1alpha3/grid-example.yaml
  examples/v1alpha3/hyperband-example.yaml
  examples/v1alpha3/mxnet-mnist/Dockerfile
  examples/v1alpha3/mxnet-mnist/README.md
  examples/v1alpha3/mxnet-mnist/common/__init__.py
  examples/v1alpha3/mxnet-mnist/common/fit.py
  examples/v1alpha3/mxnet-mnist/common/utils.py
  examples/v1alpha3/mxnet-mnist/mnist.py
  examples/v1alpha3/mxnet-mnist/symbols/__init__.py
  examples/v1alpha3/mxnet-mnist/symbols/mlp.py
  examples/v1alpha3/random-example.yaml
  examples/v1alpha3/tpe-example.yaml
  manifests/v1alpha3/katib-controller/trialTemplateConfigmap.yaml
  test/e2e/v1alpha3/invalid-experiment.yaml
  test/e2e/v1alpha3/valid-experiment.yaml
  test/scripts/v1alpha3/create-cluster.sh
Labels: approved, lgtm, size/XL

#1011 E2E Test for NAS RL Suggestion
  examples/v1alpha3/nasjob-example-RL-cpu.yaml
  examples/v1alpha3/nasjob-example-RL-gpu.yaml
  test/scripts/v1alpha3/run-suggestion-nasrl.sh
Labels: approved, lgtm, size/L

#1012 fix: Avoid out-of-range exception
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
Labels: approved, lgtm, size/S

#1013 [Feature] Enable imagePullPolicy in Katib Config
  manifests/v1alpha3/katib-controller/katib-config.yaml
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/util/v1alpha3/katibconfig/config.go
  pkg/webhook/v1alpha3/pod/inject_webhook.go
Labels: approved, lgtm, size/M

#1000 Nerual -> Neural
  pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1010 feat: Do not inject sh -c when it exists
  .gitignore
  pkg/webhook/v1alpha3/pod/inject_webhook.go
  pkg/webhook/v1alpha3/pod/inject_webhook_test.go
Labels: approved, lgtm, size/L

#1015 fix: First check failed condition
  pkg/controller.v1alpha3/experiment/util/status_util.go
Labels: approved, lgtm, size/S

#1017 Added version number and TODO descriptions to API proto
  pkg/apis/manager/v1alpha3/api.proto
Labels: approved, lgtm, size/XS

#1019 feat: Add adopters
  docs/community/adopters.md
Labels: approved, lgtm, size/XS

#1022 Updated links and instructions for Katib API docs
  README.md
  pkg/apis/manager/README.md
  pkg/apis/manager/v1alpha3/gen-doc/api.md
Labels: approved, lgtm, size/M

#1025 add antfin into list of adoptors
  docs/community/adopters.md
Labels: approved, lgtm, ok-to-test, size/XS

#1026 Adding cisco in Katib adopters
  docs/community/adopters.md
Labels: approved, lgtm, size/XS

#1020 feat: Add a flag to support removing GRPC probe at runtime
  cmd/katib-controller/v1alpha3/main.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
Labels: approved, lgtm, size/M

#1027 UI: Fix Trial Metric in the Plot
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
Labels: approved, lgtm, size/M

#1028 fix: Ignore trials without metrics
  pkg/suggestion/v1alpha3/internal/trial.py
Labels: approved, lgtm, size/S

#1024 chore: Update docs
  README.md
  docs/developer-guide.md
Labels: approved, lgtm, size/M

#1023 record TrialNames group by stages in ExperimentStatus
  pkg/apis/controller/experiments/v1alpha3/experiment_types.go
  pkg/apis/controller/experiments/v1alpha3/zz_generated.deepcopy.go
  pkg/controller.v1alpha3/experiment/util/status_util.go
Labels: approved, lgtm, ok-to-test, size/M

#1031 UI: Experiment view in the Dialog
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/ExperimentInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
Labels: approved, lgtm, size/L

#1032 UI: Add Trial Status to HP Job Table
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobPlot.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/index.js
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/L
