Repository kubeflow/katib, pull requests merged in 2020-12, with the labels that each got.

#1404 Fix Early Stopped Trials in Goptuna Suggestion
  pkg/suggestion/v1beta1/goptuna/converter.go
  pkg/suggestion/v1beta1/goptuna/sample.go
Labels: approved, lgtm, size/S

#1406 Remove duecredit pkg from the Suggestions
  cmd/suggestion/chocolate/v1beta1/requirements.txt
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/requirements.txt
Labels: approved, lgtm, size/XS

#1403 Add Katib Bundle for Juju
  operators/OWNERS
  operators/README.md
  operators/bundle.yaml
  operators/katib-controller/config.yaml
  operators/katib-controller/files/crds.yaml
  operators/katib-controller/files/defaultTrialTemplate.yaml
  operators/katib-controller/files/early-stopping.json
  operators/katib-controller/files/enasCPUTemplate.yaml
  operators/katib-controller/files/metrics-collector-sidecar.json
  operators/katib-controller/files/pytorchJobTemplate.yaml
  operators/katib-controller/files/suggestion.json
  operators/katib-controller/layer.yaml
  operators/katib-controller/metadata.yaml
  operators/katib-controller/reactive/katib_controller.py
  operators/katib-db-manager/config.yaml
  operators/katib-db-manager/layer.yaml
  operators/katib-db-manager/metadata.yaml
  operators/katib-db-manager/reactive/katib_db_manager.py
  operators/katib-ui/config.yaml
  operators/katib-ui/layer.yaml
  operators/katib-ui/metadata.yaml
  operators/katib-ui/reactive/katib_ui.py
Labels: approved, lgtm, size/XL

#1409 Bump Prettier to 2.2.0 for the Katib UI
  .travis.yml
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialConfigMap.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/KubeflowDashboard.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/AddDialog.jsx
  pkg/ui/v1beta1/frontend/src/sagas/index.js
Labels: approved, lgtm, size/M

#1408 Fix indentation in the OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#1411 Add Juju install commands to operators README
  operators/README.md
Labels: approved, lgtm, size/M
