Repository kubeflow/katib, pull requests merged in 2020-06, with the labels that each got.

#1201 Update doc for training container images with DARTS
  examples/v1alpha3/README.md
  examples/v1beta1/README.md
Labels: approved, lgtm, size/S

#1204 Rename algorithm_setting to algorithm_settings in manager
  docs/proposals/suggestion.md
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/api.swagger.json
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/controller.v1beta1/suggestion/suggestionclient/algorithm_settings.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/suggestion/v1beta1/goptuna/converter.go
  pkg/suggestion/v1beta1/goptuna/service_test.go
  pkg/suggestion/v1beta1/hyperband/service.py
  pkg/suggestion/v1beta1/hyperopt/service.py
  pkg/suggestion/v1beta1/nas/darts/service.py
  pkg/suggestion/v1beta1/nas/enas/service.py
  pkg/suggestion/v1beta1/skopt/service.py
  test/suggestion/v1beta1/test_darts_service.py
  test/suggestion/v1beta1/test_hyperband_service.py
  test/suggestion/v1beta1/test_hyperopt_service.py
  test/suggestion/v1beta1/test_skopt_service.py
Labels: approved, lgtm, size/L

#1210 Add citation information
  README.md
Labels: approved, lgtm, size/S

#1140 extracting metric value in multiple ways
  examples/v1beta1/metric-strategy-example.yaml
  pkg/apis/controller/common/v1beta1/common_types.go
  pkg/apis/controller/common/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/experiment/util/status_util.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/managerclient/managerclient.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  test/e2e/v1beta1/resume-e2e-experiment.go
  test/e2e/v1beta1/run-e2e-experiment.go
Labels: approved, lgtm, size/XL

#1215 New Trial Template validation
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/experiment/manifest/generator.go
  pkg/mock/v1beta1/experiment/manifest/generator.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  test/e2e/v1beta1/invalid-experiment.yaml
Labels: approved, lgtm, size/XXL

#1216 Add more test cases for Generator
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
Labels: approved, lgtm, size/L

#1218 Modify metric strategies example for new Trial Template
  examples/v1beta1/metric-strategy-example.yaml
Labels: approved, lgtm, size/M

#1219 UI: Show all namespaces in experiment list
  pkg/ui/v1beta1/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1beta1/frontend/src/reducers/nasMonitor.js
Labels: approved, lgtm, size/S

#1224 UI: Add Trial Parameters to submit experiment page
  pkg/ui/v1beta1/backend.go
  pkg/ui/v1beta1/frontend/src/actions/generalActions.js
  pkg/ui/v1beta1/frontend/src/actions/templateActions.js
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/MetricsCollector.jsx
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialConfigMap.jsx
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialTemplate.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Objective.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Trial.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Objective.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Trial.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/AddDialog.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/DeleteDialog.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/EditDialog.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/FilterPanel.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/TemplateList.jsx
  pkg/ui/v1beta1/frontend/src/components/Templates/Common/TemplatePanel.jsx
  pkg/ui/v1beta1/frontend/src/reducers/general.js
  pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
  pkg/ui/v1beta1/frontend/src/reducers/template.js
  pkg/ui/v1beta1/frontend/src/sagas/index.js
  pkg/ui/v1beta1/types.go
  pkg/ui/v1beta1/util.go
Labels: approved, lgtm, size/XXL

#1225 Fix Trial template config map in v1beta1
  manifests/v1beta1/katib-controller/trial-template-configmap.yaml
Labels: approved, lgtm, size/M

#1226 Fix default metrics strategies
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
Labels: approved, lgtm, size/S

#1231 Not validate Trial template resources
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: approved, lgtm, size/S

#1237 Rename Ant Financial to Ant Group
  docs/community/adopters.md
Labels: approved, lgtm, size/XS

#1240 Delete fake Suggestion interfaces
  cmd/katib-controller/v1beta1/main.go
  pkg/controller.v1beta1/experiment/experiment_controller.go
  pkg/controller.v1beta1/experiment/suggestion/fake/fake.go
  pkg/controller.v1beta1/suggestion/suggestionclient/fake/fake.go
Labels: approved, lgtm, size/M

#1238 Update unit tests for Suggestion client
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/mock/v1beta1/api/manager.go
  scripts/mockgen.sh
Labels: approved, lgtm, size/XL

#1246 Fix Trial parameter name for v1beta1 DARTS example
  examples/v1beta1/nas/darts-example-gpu.yaml
Labels: approved, lgtm, size/XS

#1243 Validation for parameters in HP Experiments
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: approved, lgtm, size/L

#1235 chore: Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1230 Add hints to obtain Kubeflow and Minikube version
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, ok-to-test, size/XS

#1245 String type for metric values
  pkg/apis/controller/common/v1beta1/common_types.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/experiment/util/status_util.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  test/e2e/v1beta1/resume-e2e-experiment.go
  test/e2e/v1beta1/run-e2e-experiment.go
Labels: approved, lgtm, size/L
