Repository kubeflow/katib, pull requests merged in 2020-09, with the labels that each got.

#1316 Update CI test cluster version to 1.16
  test/scripts/v1alpha3/create-cluster.sh
  test/scripts/v1beta1/create-cluster.sh
  test/workflows/components/workflows-v1alpha3.libsonnet
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/S

#1306 Fix restart check in controller for completed experiments
  pkg/controller.v1beta1/experiment/experiment_controller.go
Labels: approved, lgtm, size/XS

#1302 Custom CRD: Set dynamic watch from controller flags
  cmd/katib-controller/v1beta1/main.go
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/util/flag_util.go
  pkg/controller.v1beta1/trial/util/prometheus_metrics.go
Labels: approved, lgtm, size/M

#1305 Custom CRD: Add primary pod labels
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/controller/experiments/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/controller/trials/v1beta1/zz_generated.deepcopy.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/experiment/experiment_util.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  sdk/python/v1beta1/docs/V1beta1SuggestionSpec.md
  sdk/python/v1beta1/docs/V1beta1TrialSpec.md
  sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_suggestion_spec.py
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
Labels: approved, lgtm, size/L

#1315 Fix problem with Hyperopt Out of Range error
  pkg/suggestion/v1beta1/hyperopt/base_service.py
Labels: approved, lgtm, size/S

#1303 Fix Pod's ownership to inject metrics collector
  pkg/webhook/v1beta1/pod/const.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
Labels: approved, lgtm, size/XL

#1323 Update generate script with SDK
  Makefile
  README.md
  docs/developer-guide.md
  hack/gen-python-sdk/gen-sdk.sh
Labels: approved, lgtm, size/S

#1327 [Adopters] change adopter of Ant Group
  docs/community/adopters.md
Labels: approved, lgtm, size/XS

#1308 Custom CRD: Add primary container name
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/experiment/experiment_util.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  sdk/python/v1beta1/docs/V1beta1TrialSpec.md
  sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
Labels: approved, lgtm, size/L

#1307 Custom CRD: Support dynamic Trial's jobs conditions
  Gopkg.lock
  Gopkg.toml
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/experiment/experiment_util.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/controller.v1beta1/trial/util/job_util.go
  pkg/controller.v1beta1/trial/util/job_util_test.go
  sdk/python/v1beta1/docs/V1beta1TrialSpec.md
  sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/pretty.go
Labels: approved, lgtm, size/XXL

#1326 Run post-submit image build in kubeflow-ci project
  prow_config.yaml
  test/scripts/v1alpha3/build-katib-controller.sh
  test/scripts/v1alpha3/build-manager.sh
  test/scripts/v1alpha3/build-suggestion-chocolate.sh
  test/scripts/v1alpha3/build-suggestion-darts.sh
  test/scripts/v1alpha3/build-suggestion-enas.sh
  test/scripts/v1alpha3/build-suggestion-goptuna.sh
  test/scripts/v1alpha3/build-suggestion-hyperband.sh
  test/scripts/v1alpha3/build-suggestion-hyperopt.sh
  test/scripts/v1alpha3/build-suggestion-nasenvelopenet.sh
  test/scripts/v1alpha3/build-suggestion-skopt.sh
  test/scripts/v1alpha3/build-ui.sh
  test/scripts/v1beta1/build-file-metrics-collector.sh
  test/scripts/v1beta1/build-katib-controller.sh
  test/scripts/v1beta1/build-manager.sh
  test/scripts/v1beta1/build-suggestion-chocolate.sh
  test/scripts/v1beta1/build-suggestion-darts.sh
  test/scripts/v1beta1/build-suggestion-enas.sh
  test/scripts/v1beta1/build-suggestion-goptuna.sh
  test/scripts/v1beta1/build-suggestion-hyperband.sh
  test/scripts/v1beta1/build-suggestion-hyperopt.sh
  test/scripts/v1beta1/build-suggestion-nasenvelopenet.sh
  test/scripts/v1beta1/build-suggestion-skopt.sh
  test/scripts/v1beta1/build-tfevent-metrics-collector.sh
  test/scripts/v1beta1/build-ui.sh
Labels: approved, lgtm, size/L

#1337 Add SDK examples for v1beta1
  sdk/python/v1beta1/README.md
  sdk/python/v1beta1/examples/cmaes-and-resume-policies.ipynb
  sdk/python/v1beta1/examples/nas-with-darts.ipynb
Labels: approved, lgtm, size/XXL

#1335 Upload python SDK version
  hack/gen-python-sdk/post_gen.py
  sdk/python/v1alpha3/README.md
  sdk/python/v1alpha3/kubeflow/katib/__init__.py
  sdk/python/v1beta1/README.md
  sdk/python/v1beta1/docs/KatibClient.md
  sdk/python/v1beta1/kubeflow/katib/__init__.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
  sdk/python/v1beta1/setup.py
Labels: approved, lgtm, size/XL

#1340 feat: Ignore pb files in update gofmt
  .travis.yml
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: approved, lgtm, size/XS

#1312 fix(metrics-collector): allow user to nuke ephemeral-storage requests
  pkg/util/v1beta1/katibconfig/config.go
Labels: approved, lgtm, ok-to-test, size/XS

#1319 Add trial metadata substitution example
  examples/v1beta1/trial-metadata-substitution.yaml
Labels: approved, lgtm, size/M
