Repository kubeflow/katib, pull requests merged in 2020-11, with the labels that each got.

#1373 UI: Add early stopping to submit Experiment by parameters
  pkg/ui/v1beta1/frontend/src/actions/generalActions.js
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/EarlyStopping.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Monitor/HPJobTable.jsx
  pkg/ui/v1beta1/frontend/src/reducers/general.js
Labels: approved, lgtm, size/L

#1370 Bump Tensorflow from 1.15.2 to 1.15.4
  cmd/suggestion/nas/enas/v1alpha3/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1alpha3/nas/enas-cnn-cifar10/requirements-cpu.txt
  examples/v1alpha3/nas/enas-cnn-cifar10/requirements-gpu.txt
  examples/v1beta1/nas/enas-cnn-cifar10/requirements-cpu.txt
  examples/v1beta1/nas/enas-cnn-cifar10/requirements-gpu.txt
Labels: approved, lgtm, size/S

#1372 Change image registry to docker.io/kubeflowkatib
  docs/new-algorithm-service.md
  examples/v1beta1/bayesianoptimization-example.yaml
  examples/v1beta1/cmaes-example.yaml
  examples/v1beta1/custom-metricscollector-example.yaml
  examples/v1beta1/early-stopping/median-stop.yaml
  examples/v1beta1/file-metricscollector-example.yaml
  examples/v1beta1/grid-example.yaml
  examples/v1beta1/hyperband-example.yaml
  examples/v1beta1/metric-strategy-example.yaml
  examples/v1beta1/nas/darts-example-cpu.yaml
  examples/v1beta1/nas/darts-example-gpu.yaml
  examples/v1beta1/nas/enas-example-cpu.yaml
  examples/v1beta1/nas/enas-example-gpu.yaml
  examples/v1beta1/random-example.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/resume-experiment/never-resume.yaml
  examples/v1beta1/tekton/README.md
  examples/v1beta1/tekton/pipeline-run.yaml
  examples/v1beta1/tpe-example.yaml
  examples/v1beta1/trial-metadata-substitution.yaml
  manifests/v1beta1/db-manager/deployment.yaml
  manifests/v1beta1/katib-controller/katib-config.yaml
  manifests/v1beta1/katib-controller/katib-controller.yaml
  manifests/v1beta1/katib-controller/trial-template-configmap.yaml
  manifests/v1beta1/ui/deployment.yaml
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
  scripts/v1beta1/release.sh
  sdk/python/v1beta1/examples/cmaes-and-resume-policies.ipynb
  sdk/python/v1beta1/examples/nas-with-darts.ipynb
  test/e2e/v1beta1/invalid-experiment.yaml
  test/e2e/v1beta1/valid-experiment.yaml
  test/scripts/v1beta1/setup-katib.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/L

#1375 Add example with ConfigMap source for the Trial template
  examples/v1beta1/trial-configmap-source.yaml
Labels: approved, lgtm, size/M

#1378 Update Python SDK version to 0.10.0
  prow_config.yaml
  sdk/python/v1beta1/README.md
  sdk/python/v1beta1/setup.py
  setup.py
Labels: approved, lgtm, size/S

#1380 Fix: Add taskruns to Katib controller role to run Tekton Pipelines
  manifests/v1beta1/katib-controller/rbac.yaml
  pkg/webhook/v1beta1/pod/inject_webhook.go
Labels: approved, lgtm, size/XS

#1386 Fix compare step for the early stopping
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  examples/v1beta1/early-stopping/median-stop.yaml
Labels: approved, lgtm, size/S

#1388 Remove new Trial kind doc
  docs/developer-guide.md
  docs/new-trial-kind.md
Labels: approved, lgtm, size/M

#1390 Add Stale config to close inactivity issues
  .github/stale.yml
Labels: approved, lgtm, size/S

#1391 Move Adopters file
  ADOPTERS.md
  README.md
Labels: approved, lgtm, size/XS

#1393 Add recreate strategy to MySQL deployment
  manifests/v1beta1/mysql-db/deployment.yaml
Labels: approved, lgtm, size/XS

#1394 Feature/waitallprocesses config
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  cmd/metricscollector/v1beta1/tfevent-metricscollector/main.py
  pkg/metricscollector/v1beta1/common/const.go
  pkg/metricscollector/v1beta1/common/const.py
  pkg/util/v1beta1/katibconfig/config.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1401 Adding to ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#1392 Update docs for Katib 0.10
  README.md
  docs/algorithm-settings.md
  docs/images/quickstart-trial.png
  docs/images/quickstart.png
  docs/quick-start.md
  docs/user-guide.md
  docs/workflow-design.md
Labels: approved, lgtm, size/XXL
