Repository kubeflow/katib, pull requests merged in 2020-10, with the labels that each got.

#1333 Enhancement for Custom CRD
  pkg/apis/controller/trials/v1beta1/util.go
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/controller.v1beta1/trial/util/job_util.go
  pkg/controller.v1beta1/util/annotations.go
  pkg/db/v1beta1/mysql/mysql.go
  pkg/db/v1beta1/mysql/mysql_test.go
  pkg/metricscollector/v1beta1/common/const.py
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  test/e2e/v1beta1/invalid-experiment.yaml
Labels: approved, lgtm, size/L

#1342 Add MPI operator horovod example
  examples/v1beta1/README.md
  examples/v1beta1/mpijob-horovod.yaml
  manifests/v1beta1/katib-controller/katib-controller.yaml
  manifests/v1beta1/katib-controller/rbac.yaml
Labels: approved, lgtm, size/L

#1361 Improve Katib README
  README.md
Labels: approved, lgtm, size/XS

#1355 Clean up code for custom CRD
  examples/v1beta1/bayesianoptimization-example.yaml
  examples/v1beta1/cmaes-example.yaml
  examples/v1beta1/custom-metricscollector-example.yaml
  examples/v1beta1/file-metricscollector-example.yaml
  examples/v1beta1/fpga/xgboost-example.yaml
  examples/v1beta1/grid-example.yaml
  examples/v1beta1/hyperband-example.yaml
  examples/v1beta1/metric-strategy-example.yaml
  examples/v1beta1/nas/darts-example-cpu.yaml
  examples/v1beta1/nas/darts-example-gpu.yaml
  examples/v1beta1/nas/enas-example-cpu.yaml
  examples/v1beta1/nas/enas-example-gpu.yaml
  examples/v1beta1/pytorchjob-example.yaml
  examples/v1beta1/random-example.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/resume-experiment/never-resume.yaml
  examples/v1beta1/tfjob-example.yaml
  examples/v1beta1/tpe-example.yaml
  examples/v1beta1/trial-metadata-substitution.yaml
  manifests/v1beta1/katib-controller/katib-controller.yaml
  pkg/apis/controller/experiments/v1beta1/constants.go
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/experiment/experiment_consts.go
  pkg/controller.v1beta1/experiment/experiment_controller.go
  pkg/controller.v1beta1/experiment/experiment_controller_status.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/experiment/experiment_controller_util.go
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/experiment/util/status_util.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_status.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_consts.go
  pkg/controller.v1beta1/trial/trial_controller_status.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/job/v1beta1/job.go
  pkg/job/v1beta1/kubeflow.go
  pkg/job/v1beta1/provider.go
  pkg/ui/v1beta1/backend.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  test/e2e/v1beta1/invalid-experiment.yaml
  test/e2e/v1beta1/valid-experiment.yaml
Labels: approved, size/XXL

#1338 Remove istio sidecar annotation from all examples
  examples/v1beta1/bayesianoptimization-example.yaml
  examples/v1beta1/cmaes-example.yaml
  examples/v1beta1/custom-metricscollector-example.yaml
  examples/v1beta1/file-metricscollector-example.yaml
  examples/v1beta1/fpga/xgboost-example.yaml
  examples/v1beta1/grid-example.yaml
  examples/v1beta1/metric-strategy-example.yaml
  examples/v1beta1/random-example.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/tpe-example.yaml
  examples/v1beta1/trial-metadata-substitution.yaml
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/util/annotations.go
Labels: approved, lgtm, size/L

#1339 Add Tekton Pipeline example
  examples/v1beta1/tekton/README.md
  examples/v1beta1/tekton/pipeline-run.yaml
  manifests/v1beta1/katib-controller/katib-controller.yaml
  manifests/v1beta1/katib-controller/rbac.yaml
Labels: approved, lgtm, size/L

#1363 UI: Support new parameters in Trial template
  pkg/ui/v1beta1/frontend/src/actions/generalActions.js
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/MetricsCollector.jsx
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialTemplate.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1beta1/frontend/src/constants/constants.js
  pkg/ui/v1beta1/frontend/src/reducers/general.js
  pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
  pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/XL

#1364 UI: Support metrics strategies to submit Experiment by parameters
  pkg/ui/v1beta1/frontend/src/actions/hpCreateActions.js
  pkg/ui/v1beta1/frontend/src/actions/nasCreateActions.js
  pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Algorithm.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonMeta.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonSpec.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Objective.jsx
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Parameters.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Algorithm.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonMeta.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonSpec.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/NASConfig.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Objective.jsx
  pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
  pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/XL

#1362 UI: Add resume policy to submit Experiment by parameters
  pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonSpec.jsx
  pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonSpec.jsx
  pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
  pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/L

#1349 fix typo in crd-experiment
  manifests/v1beta1/katib-controller/crd-experiment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1368 Remove default values for Trial template
  pkg/apis/controller/experiments/v1beta1/constants.go
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: approved, lgtm, size/M

#1371 Add Katib release script
  Gopkg.lock
  Makefile
  docs/developer-guide.md
  prow_config.yaml
  scripts/v1beta1/build.sh
  scripts/v1beta1/deploy.sh
  scripts/v1beta1/release.sh
  test/scripts/v1beta1/build-file-metrics-collector.sh
  test/scripts/v1beta1/build-katib-controller.sh
  test/scripts/v1beta1/build-manager.sh
  test/scripts/v1beta1/build-suggestion-chocolate.sh
  test/scripts/v1beta1/build-suggestion-darts.sh
  test/scripts/v1beta1/build-suggestion-enas.sh
  test/scripts/v1beta1/build-suggestion-goptuna.sh
  test/scripts/v1beta1/build-suggestion-hyperband.sh
  test/scripts/v1beta1/build-suggestion-hyperopt.sh
  test/scripts/v1beta1/build-suggestion-skopt.sh
  test/scripts/v1beta1/build-tfevent-metrics-collector.sh
  test/scripts/v1beta1/build-ui.sh
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows-v1beta1-release.jsonnet
  test/workflows/components/workflows-v1beta1-release.libsonnet
Labels: approved, lgtm, size/XXL
