Repository kubeflow/katib, pull requests merged in 2020-02, with the labels that each got.

#1038 Update adopter
  docs/community/adopters.md
Labels: approved, lgtm, size/XS

#1046 Adding Babylon Health as adopter
  docs/community/adopters.md
Labels: approved, lgtm, ok-to-test, size/XS

#1047 UI: Fix problem with equal time in different Trial metrics
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/XS

#1048 UI: The best metrics in Trial table
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/S

#1050 Disable istio sidecar injection in Suggestion and Training Jobs
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/controller.v1alpha3/util/annotations.go
Labels: approved, lgtm, size/L

#1054 openAPI generation for katib resources
  Gopkg.lock
  Gopkg.toml
  hack/swagger/main.go
  hack/update-openapigen.sh
  pkg/apis/controller/common/v1alpha3/doc.go
  pkg/apis/controller/common/v1alpha3/register.go
  pkg/apis/v1alpha3/openapi_generated.go
  pkg/apis/v1alpha3/swagger.json
  vendor/k8s.io/code-generator/cmd/openapi-gen/args/args.go
  vendor/k8s.io/code-generator/cmd/openapi-gen/main.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
Labels: approved, lgtm, ok-to-test, size/XXL

#1053 Adding error propagation for K8s client creation in KatibClient
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, ok-to-test, size/XS

#1056 MXNet -> Apache MXNet
  README.md
Labels: approved, lgtm, size/XS

#1055 Change tell method for BO Suggestion
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
Labels: approved, lgtm, size/S

#1059 Add missing GRPC health probe for arm64 to db-manager
  cmd/db-manager/v1alpha3/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1057 Create Optimizer in BO Suggestion only for the first run
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
  pkg/suggestion/v1alpha3/skopt_service.py
Labels: approved, lgtm, size/L

#1064 Update adopters
  docs/community/adopters.md
Labels: approved, lgtm, ok-to-test, size/XS

#1068 UI: Show best metrics in the Trial metrics information plot
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/hp.go
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/L

#1066 Update Katib docs
  README.md
  ROADMAP.md
  docs/community/adopters.md
  docs/developer-guide.md
  docs/new-algorithm-service.md
  docs/new-trial-kind.md
  docs/proposals/metrics-collector.md
  docs/proposals/suggestion.md
  docs/quick-start.md
  docs/workflow-design.md
Labels: approved, lgtm, size/L

#1063 Fix TPE Suggestion
  cmd/suggestion/hyperopt/v1alpha3/requirements.txt
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
Labels: approved, lgtm, size/L

#1070 UI: Update supported algorithms
  pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/XS

#1069 dynamic jobProvider and suggestionComposer registration
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/controller.v1alpha3/suggestion/suggestion_controller.go
  pkg/controller.v1alpha3/trial/trial_controller.go
  pkg/job/v1alpha3/consts.go
  pkg/job/v1alpha3/job.go
  pkg/job/v1alpha3/kubeflow.go
  pkg/job/v1alpha3/provider.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/pod/inject_webhook_test.go
  pkg/webhook/v1alpha3/pod/utils.go
Labels: approved, lgtm, ok-to-test, size/L

#1071 Add more unit tests in Katib
  cmd/db-manager/v1alpha3/main_test.go
  pkg/db/v1alpha3/mysql/mysql_test.go
  pkg/webhook/v1alpha3/experiment/validator/validator.go
  pkg/webhook/v1alpha3/experiment/validator/validator_test.go
  pkg/webhook/v1alpha3/pod/inject_webhook_test.go
Labels: approved, lgtm, size/XL
