Repository kubeflow/katib, pull requests merged in 2020-03, with the labels that each got.

#1072 fix annotations
  pkg/apis/controller/common/v1alpha3/common_types.go
  pkg/apis/controller/common/v1alpha3/zz_generated.deepcopy.go
  pkg/apis/v1alpha3/openapi_generated.go
  pkg/apis/v1alpha3/swagger.json
  pkg/controller.v1alpha3/util/annotations.go
Labels: approved, lgtm, ok-to-test, size/M

#1074 Adding Karrot as adopter
  docs/community/adopters.md
Labels: approved, lgtm, ok-to-test, size/XS

#1077 UI: Add Experiment view for NAS Jobs
  cmd/ui/v1alpha3/main.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
  pkg/ui/v1alpha3/frontend/src/components/Common/ExperimentInfoDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/hp.go
Labels: approved, lgtm, size/L

#1096 UI: Add Metrics Collector Spec to Submit Experiment
  pkg/ui/v1alpha3/frontend/package.json
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpCreateActions.js
  pkg/ui/v1alpha3/frontend/src/actions/nasCreateActions.js
  pkg/ui/v1alpha3/frontend/src/components/Common/Create/Params/MetricsCollector.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1alpha3/frontend/src/constants/constants.js
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
Labels: approved, lgtm, size/XXL

#1097 Fix Chocolate mocmaes algorithm name in Suggestion
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
Labels: approved, lgtm, size/XS

#1083 UI: Support Trial Templates in all namespaces and all configMaps
  .travis.yml
  cmd/ui/v1alpha3/main.go
  manifests/v1alpha3/katib-controller/trialTemplateConfigmapLabeled.yaml
  pkg/controller.v1alpha3/consts/const.go
  pkg/mock/v1alpha3/util/katibclient/katibclient.go
  pkg/ui/v1alpha3/backend.go
  pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
  pkg/ui/v1alpha3/frontend/src/actions/hpCreateActions.js
  pkg/ui/v1alpha3/frontend/src/actions/nasCreateActions.js
  pkg/ui/v1alpha3/frontend/src/actions/templateActions.js
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/NASParameters.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobMonitor.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/AddDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/DeleteDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/EditDialog.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/FilterPanel.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/TemplateList.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Common/TemplatePanel.jsx
  pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
  pkg/ui/v1alpha3/frontend/src/reducers/general.js
  pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
  pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
  pkg/ui/v1alpha3/frontend/src/reducers/template.js
  pkg/ui/v1alpha3/frontend/src/sagas/index.js
  pkg/ui/v1alpha3/types.go
  pkg/ui/v1alpha3/util.go
  pkg/util/v1alpha3/katibclient/katib_client.go
Labels: approved, lgtm, size/XXL

#1065 Enable to run Experiment without Goal
  pkg/controller.v1alpha3/experiment/util/status_util.go
  pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
  test/e2e/v1alpha3/resume-e2e-experiment.go
  test/e2e/v1alpha3/run-e2e-experiment.go
Labels: approved, lgtm, size/M

#1101 Add ghalton package to Chocolate Suggestion
  cmd/suggestion/chocolate/v1alpha3/requirements.txt
Labels: approved, lgtm, size/XS

#1092 Enable to add Service Account Name in Katib config
  pkg/controller.v1alpha3/consts/const.go
  pkg/controller.v1alpha3/suggestion/composer/composer.go
  pkg/util/v1alpha3/katibconfig/config.go
Labels: approved, lgtm, size/M

#1103 Add myself to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#1107 Refactor python files of suggestion services
  pkg/suggestion/v1alpha3/base_health_service.py
  pkg/suggestion/v1alpha3/hyperband_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
  pkg/suggestion/v1alpha3/nasrl_service.py
  pkg/suggestion/v1alpha3/parameter.py
Labels: approved, lgtm, ok-to-test, size/S

#1102 Fix custom Katib DB Manager env variables
  pkg/common/v1alpha3/katib_manager_util.go
  pkg/controller.v1alpha3/consts/const.go
  pkg/ui/v1alpha3/backend.go
Labels: approved, lgtm, size/M

#1106 Refactor suggestion-internal-modules
  pkg/suggestion/v1alpha3/internal/search_space.py
  pkg/suggestion/v1alpha3/internal/trial.py
Labels: approved, lgtm, ok-to-test, size/S

#1108 Fix logger namespace
  pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
  pkg/suggestion/v1alpha3/chocolate_service.py
  pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
  pkg/suggestion/v1alpha3/hyperopt_service.py
  pkg/suggestion/v1alpha3/internal/search_space.py
  pkg/suggestion/v1alpha3/internal/trial.py
  pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
  pkg/suggestion/v1alpha3/skopt_service.py
Labels: approved, lgtm, ok-to-test, size/S

#1109 Update prow config with the latest folders
  prow_config.yaml
Labels: approved, lgtm, size/M

#1105 Refactor python files in cmd/suggestion
  cmd/suggestion/chocolate/v1alpha3/__init__.py
  cmd/suggestion/hyperband/v1alpha3/__init__.py
  cmd/suggestion/hyperopt/v1alpha3/__init__.py
  cmd/suggestion/hyperopt/v1alpha3/main.py
  cmd/suggestion/nasrl/v1alpha3/__init__.py
  cmd/suggestion/nasrl/v1alpha3/main.py
  cmd/suggestion/skopt/v1alpha3/__init__.py
  cmd/suggestion/skopt/v1alpha3/main.py
Labels: approved, lgtm, ok-to-test, size/XS
