Repository kubeflow/katib, pull requests merged in 2021-11, with the labels that each got.

#1713 Support leader election for katib-controller
  cmd/katib-controller/v1beta1/main.go
  docs/developer-guide.md
  manifests/v1beta1/installs/katib-leader-election/kustomization.yaml
  manifests/v1beta1/installs/katib-leader-election/leader-election-rbac.yaml
  manifests/v1beta1/installs/katib-leader-election/patches/controller.yaml
  test/e2e/v1beta1/scripts/setup-katib.sh
Labels: lgtm, approved, size/M

#1720 fix: close mysql statement and rows resources when sql exec end
  pkg/db/v1beta1/mysql/mysql.go
Labels: size/XS, lgtm, approved, ok-to-test

#1701 Fix same set for HyperParameters in Bayesian Optimization algorithm
  pkg/suggestion/v1beta1/skopt/base_service.py
Labels: size/XS, lgtm, approved, ok-to-test

#1729 Allow to remove each resource in Katib config
  pkg/util/v1beta1/katibconfig/config.go
Labels: lgtm, approved, size/S

#1728 Modify gRPC API with Current Request Number
  docs/new-algorithm-service.md
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/suggestion/v1beta1/chocolate/base_service.py
  pkg/suggestion/v1beta1/chocolate/service.py
  pkg/suggestion/v1beta1/goptuna/service.go
  pkg/suggestion/v1beta1/goptuna/service_test.go
  pkg/suggestion/v1beta1/hyperband/service.py
  pkg/suggestion/v1beta1/hyperopt/base_service.py
  pkg/suggestion/v1beta1/hyperopt/service.py
  pkg/suggestion/v1beta1/nas/darts/service.py
  pkg/suggestion/v1beta1/nas/enas/service.py
  pkg/suggestion/v1beta1/optuna/service.py
  pkg/suggestion/v1beta1/skopt/base_service.py
  pkg/suggestion/v1beta1/skopt/service.py
  test/unit/v1beta1/suggestion/test_chocolate_service.py
  test/unit/v1beta1/suggestion/test_darts_service.py
  test/unit/v1beta1/suggestion/test_enas_service.py
  test/unit/v1beta1/suggestion/test_hyperband_service.py
  test/unit/v1beta1/suggestion/test_hyperopt_service.py
  test/unit/v1beta1/suggestion/test_optuna_service.py
  test/unit/v1beta1/suggestion/test_skopt_service.py
Labels: lgtm, approved, size/XL

#1726 fix: check if parameter references exist in experiment parameters
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/M, ok-to-test

#1732 Fix Range for Int and Double values in Grid
  pkg/suggestion/v1beta1/chocolate/base_service.py
  pkg/suggestion/v1beta1/internal/search_space.py
Labels: lgtm, approved, size/S

#1740 Change namespace label for metrics collector injection
  docs/proposals/metrics-collector.md
  examples/v1beta1/argo/README.md
  manifests/v1beta1/components/namespace/namespace.yaml
  manifests/v1beta1/components/webhook/webhooks.yaml
  operators/katib-controller/src/webhooks.yaml
  pkg/metricscollector/v1beta1/common/const.go
  pkg/webhook/v1beta1/common/const.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/pod/const.go
  pkg/webhook/v1beta1/pod/utils.go
Labels: lgtm, approved, size/S

#1741 docs: Argo -> Argo Workflows
  examples/v1beta1/argo/README.md
Labels: size/XS, lgtm, approved

#1709 Implement validation for early stopping
  README.md
  docs/developer-guide.md
  pkg/apis/manager/README.md
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2_grpc.py
  pkg/controller.v1beta1/experiment/manifest/generator.go
  pkg/controller.v1beta1/suggestion/suggestion_controller.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/mock/v1beta1/api/earlystopping.go
  pkg/mock/v1beta1/experiment/manifest/generator.go
  pkg/mock/v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  test/unit/v1beta1/earlystopping/test_medianstop_service.py
  test/unit/v1beta1/earlystopping/utils.py
Labels: lgtm, size/XXL, approved

#1749 Add Akuity to list of adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1751 Update links for issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: lgtm, approved, size/M

#1753 docs: Add my presentations that include Katib
  docs/presentations.md
Labels: size/XS, lgtm, approved
