Repository kubeflow/katib, pull requests merged in 2021-02, with the labels that each got.

#1426 Change roles to clusterroles for operators
  operators/OWNERS
  operators/katib-controller/reactive/katib_controller.py
  operators/katib-ui/reactive/katib_ui.py
Labels: approved, lgtm, ok-to-test, size/XS

#1445 Verify nil objective in Experiment defaults
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
Labels: approved, lgtm, size/M

#1446 Add Katib presentations and community information
  README.md
  docs/presentations.md
  scripts/update-readme-toc.sh
Labels: approved, lgtm, size/M

#1442 Enhance katib client by adding get_success_trial_details()
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: approved, lgtm, ok-to-test, size/M

#1449 Add katib controller flags to developers guide
  docs/developer-guide.md
Labels: approved, lgtm, ok-to-test, size/S
