Repository kubeflow/katib, pull requests merged in 2021-09, with the labels that each got.

#1652 UI: Handle missing TrialTemplates
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: lgtm, approved, size/S

#1654 [bugfix]: increase test timeout
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
Labels: size/XS, lgtm, approved

#1657 cherry-pick: UI fix for handling missing params
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: lgtm, approved, size/S

#1659 Remove README toc script
  scripts/update-readme-toc.sh
Labels: lgtm, approved, size/S

#1658 Add mockgen version to gen script
  go.mod
  go.sum
  hack/update-mockgen.sh
  pkg/mock/v1beta1/api/earlystopping.go
  pkg/mock/v1beta1/api/suggestion.go
  pkg/mock/v1beta1/db/db.go
  pkg/mock/v1beta1/experiment/manifest/generator.go
  pkg/mock/v1beta1/experiment/suggestion/suggestion.go
  pkg/mock/v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/mock/v1beta1/trial/managerclient/katibmanager.go
  pkg/mock/v1beta1/util/katibclient/katibclient.go
Labels: lgtm, approved, size/M

#1661 Add Changelog for Katib 0.12.0-rc.1 release
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#1662 Reimplement katib-cert-generator in Go
  cmd/cert-generator/v1beta1/Dockerfile
  cmd/cert-generator/v1beta1/main.go
  docs/developer-guide.md
  go.mod
  go.sum
  hack/cert-generator.sh
  manifests/v1beta1/components/cert-generator/cert-generator.yaml
  manifests/v1beta1/components/cert-generator/rbac.yaml
  manifests/v1beta1/components/webhook/webhooks.yaml
  pkg/cert-generator/v1beta1/cert-generator.go
  pkg/cert-generator/v1beta1/consts/const.go
  pkg/cert-generator/v1beta1/generate/certificate.go
  pkg/cert-generator/v1beta1/generate/generate.go
  pkg/cert-generator/v1beta1/generate/generate_test.go
Labels: lgtm, size/XXL, approved, ok-to-test

#1669 Add Cert Generator to prow include dirs
  prow_config.yaml
Labels: size/XS, lgtm, approved

#1660 Bump Katib Python SDK to 0.12.0rc1 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1675 Change the minimal kustomize version in the developer guide
  docs/developer-guide.md
Labels: size/XS, lgtm, approved, ok-to-test

#1671 Use golangci-lint as linter for Go
  Makefile
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  hack/.golint_failures
  hack/verify-golangci-lint.sh
  hack/verify-golint.sh
  pkg/apis/controller/common/v1beta1/common_types.go
  pkg/apis/controller/experiments/v1beta1/util.go
  pkg/controller.v1beta1/experiment/experiment_controller.go
  pkg/controller.v1beta1/experiment/experiment_controller_suite_test.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/experiment/manifest/generator.go
  pkg/controller.v1beta1/experiment/util/status_util.go
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_suite_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/managerclient/managerclient.go
  pkg/controller.v1beta1/trial/trial_controller_suite_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/db/v1beta1/mysql/mysql_test.go
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
  pkg/new-ui/v1beta1/backend.go
  pkg/new-ui/v1beta1/hp.go
  pkg/new-ui/v1beta1/nas.go
  pkg/new-ui/v1beta1/types.go
  pkg/new-ui/v1beta1/util.go
  pkg/ui/v1beta1/backend.go
  pkg/ui/v1beta1/hp.go
  pkg/ui/v1beta1/nas.go
  pkg/ui/v1beta1/types.go
  pkg/ui/v1beta1/util.go
  pkg/util/v1beta1/katibclient/katib_client.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: lgtm, approved, size/XL, ok-to-test

#1667 Refactor README
  README.md
  docs/images/katib-ui.png
Labels: lgtm, approved, size/L

#1674 Create Python script to run e2e Argo Workflow
  prow_config.yaml
  test/e2e/v1beta1/argo_workflow.py
  test/e2e/v1beta1/scripts/python-tests.sh
  test/e2e/v1beta1/scripts/run-e2e-experiment.sh
  test/e2e/v1beta1/scripts/setup-katib.sh
  test/e2e/v1beta1/test_requirements.txt
  test/workflows/.ksonnet/registries/incubator/422d521c05aa905df949868143b26445f5e4eda5.yaml
  test/workflows/.ksonnet/registries/kubeflow/61c7da4756c8ba149637bf4a9e1805258fbead96.yaml
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows-v1beta1.jsonnet
  test/workflows/components/workflows-v1beta1.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/releasing/.metadata/k.libsonnet
  test/workflows/environments/releasing/.metadata/k8s.libsonnet
  test/workflows/environments/releasing/.metadata/swagger.json
  test/workflows/environments/releasing/main.jsonnet
  test/workflows/environments/releasing/params.libsonnet
  test/workflows/environments/test/.metadata/k.libsonnet
  test/workflows/environments/test/.metadata/k8s.libsonnet
  test/workflows/environments/test/.metadata/swagger.json
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: lgtm, size/XXL, approved

#1676 [bugfix]: absolute value and typo
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/hyper-parameters/hyper-parameters.component.ts
Labels: size/XS, lgtm, approved

#1678 Add envtest to check `reconcileRBAC`
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
Labels: lgtm, approved, size/M, ok-to-test

#1681 Add OWNERS file for the new ui
  pkg/new-ui/v1beta1/OWNERS
Labels: size/XS, lgtm, approved

#1683 Update Go version to 1.17
  .github/workflows/test-go.yaml
  Makefile
  docs/developer-guide.md
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  hack/update-openapigen.sh
  pkg/apis/controller/common/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/experiments/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/suggestions/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1beta1/zz_generated.deepcopy.go
  pkg/apis/v1beta1/openapi_generated.go
Labels: lgtm, approved, size/L

#1684 Add Python test requirements file
  .github/workflows/test-python.yaml
  test/unit/v1beta1/requirements.txt
Labels: size/XS, lgtm, approved

#1685 Update FPGA examples
  examples/v1beta1/fpga/OWNERS
  examples/v1beta1/fpga/README.md
  examples/v1beta1/fpga/xgboost-example.yaml
Labels: lgtm, approved, size/M, ok-to-test

#1687 Fix readme in examples directory
  examples/v1beta1/README.md
Labels: lgtm, approved, size/S
