Repository kubeflow/katib, pull requests merged in 2021-06, with the labels that each got.

#1541 feat: add naming regex check on validating webhook
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1545 Fix gofmt to validate Experiment name
  pkg/webhook/v1beta1/experiment/validator/validator.go
Labels: approved, lgtm, size/XS

#1552 Disable default PV for Experiment with resume from volume
  .github/workflows/test-go.yaml
  go.sum
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_util.go
  pkg/util/v1beta1/katibconfig/config.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  test/e2e/v1beta1/run-e2e-experiment.go
Labels: approved, lgtm, size/L

#1555 Switch to sdi
  operators/katib-controller/requirements.txt
  operators/katib-db-manager/requirements.txt
  operators/katib-ui/metadata.yaml
  operators/katib-ui/requirements.txt
  operators/katib-ui/src/charm.py
Labels: approved, lgtm, size/M

#1556 Adds docs on how to use within KF
  operators/README.md
Labels: approved, lgtm, size/XS

#1557 fix typo in operators/README
  operators/README.md
Labels: approved, lgtm, size/XS

#1564 Allow empty resources for CPU and Memory in Katib config
  pkg/util/v1beta1/katibconfig/config.go
Labels: approved, lgtm, size/S
