Repository kubeflow/katib, pull requests merged in 2021-03, with the labels that each got.

#1451 add adopter
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#1432 Katib: Move manifests development upstream
  manifests/v1beta1/components/katib-controller/application.yaml
  manifests/v1beta1/components/katib-controller/katib-configmap.yaml
  manifests/v1beta1/components/katib-controller/katib-controller-deployment.yaml
  manifests/v1beta1/components/katib-controller/katib-controller-rbac.yaml
  manifests/v1beta1/components/katib-controller/katib-controller-secret.yaml
  manifests/v1beta1/components/katib-controller/katib-controller-service.yaml
  manifests/v1beta1/components/katib-controller/katib-ui-deployment.yaml
  manifests/v1beta1/components/katib-controller/katib-ui-rbac.yaml
  manifests/v1beta1/components/katib-controller/katib-ui-service.yaml
  manifests/v1beta1/components/katib-controller/katib-ui-virtual-service.yaml
  manifests/v1beta1/components/katib-controller/kustomization.yaml
  manifests/v1beta1/components/katib-controller/params.yaml
  manifests/v1beta1/components/katib-controller/trial-template-configmap.yaml
  manifests/v1beta1/components/katib-crds/application.yaml
  manifests/v1beta1/components/katib-crds/experiment-crd.yaml
  manifests/v1beta1/components/katib-crds/kustomization.yaml
  manifests/v1beta1/components/katib-crds/suggestion-crd.yaml
  manifests/v1beta1/components/katib-crds/trial-crd.yaml
  manifests/v1beta1/components/katib-db-manager/katib-db-manager-deployment.yaml
  manifests/v1beta1/components/katib-db-manager/katib-db-manager-service.yaml
  manifests/v1beta1/components/katib-db-manager/kustomization.yaml
  manifests/v1beta1/components/katib-db-mysql/katib-mysql-deployment.yaml
  manifests/v1beta1/components/katib-db-mysql/katib-mysql-pvc.yaml
  manifests/v1beta1/components/katib-db-mysql/katib-mysql-secret.yaml
  manifests/v1beta1/components/katib-db-mysql/katib-mysql-service.yaml
  manifests/v1beta1/components/katib-db-mysql/kustomization.yaml
  manifests/v1beta1/installs/katib-external-db/katib-db-manager-deployment.yaml
  manifests/v1beta1/installs/katib-external-db/kustomization.yaml
  manifests/v1beta1/installs/katib-external-db/secrets.env
  manifests/v1beta1/installs/katib-standalone-ibm/katib-mysql-deployment.yaml
  manifests/v1beta1/installs/katib-standalone-ibm/kustomization.yaml
  manifests/v1beta1/installs/katib-standalone/kustomization.yaml
Labels: approved, lgtm, size/XXL

#1456 Re-enable Github Actions
  .github/workflows/test-charmed-katib.yaml
Labels: approved, lgtm, size/XS

#1458 Add cert generator build to the CI
  cmd/cert-generator/v1beta1/Dockerfile
  scripts/v1beta1/build.sh
  scripts/v1beta1/release.sh
  test/scripts/v1beta1/setup-katib.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/M

#1457 Add Trial images build to the CI
  .dockerignore
  examples/v1beta1/README.md
  examples/v1beta1/custom-metricscollector-example.yaml
  examples/v1beta1/file-metrics-collector/Dockerfile
  examples/v1beta1/file-metricscollector-example.yaml
  examples/v1beta1/mxnet-mnist/Dockerfile
  examples/v1beta1/nas/darts-cnn-cifar10/Dockerfile
  examples/v1beta1/nas/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/nas/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/nas/enas-cnn-cifar10/requirements-cpu.txt
  examples/v1beta1/nas/enas-cnn-cifar10/requirements-gpu.txt
  examples/v1beta1/nas/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/pytorch-mnist/Dockerfile
  examples/v1beta1/pytorch-mnist/mnist.py
  examples/v1beta1/pytorchjob-example.yaml
  manifests/v1beta1/components/katib-controller/trial-template-configmap.yaml
  manifests/v1beta1/katib-controller/trial-template-configmap.yaml
  operators/katib-controller/files/pytorchJobTemplate.yaml
  scripts/v1beta1/build.sh
  scripts/v1beta1/update-trial-images.sh
  test/scripts/v1beta1/setup-katib.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/L

#1460 Update new algorithm service doc
  docs/new-algorithm-service.md
Labels: approved, lgtm, size/L

#1463 Add missing form fields to new UI
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
  pkg/new-ui/v1beta1/frontend/src/app/models/experiment.k8s.model.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-thresholds/trial-thresholds.component.html
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: approved, lgtm, size/XL

#1459 Remove completed TODOs for Katib config
  hack/update-openapigen.sh
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/suggestion_controller.go
  pkg/util/v1beta1/katibconfig/config.go
Labels: approved, lgtm, size/S

#1470 Update Trial images to v1beta1-45c5727
  examples/v1beta1/bayesianoptimization-example.yaml
  examples/v1beta1/cmaes-example.yaml
  examples/v1beta1/custom-metricscollector-example.yaml
  examples/v1beta1/early-stopping/median-stop.yaml
  examples/v1beta1/file-metricscollector-example.yaml
  examples/v1beta1/grid-example.yaml
  examples/v1beta1/hyperband-example.yaml
  examples/v1beta1/metric-strategy-example.yaml
  examples/v1beta1/nas/darts-example-cpu.yaml
  examples/v1beta1/nas/darts-example-gpu.yaml
  examples/v1beta1/nas/enas-example-cpu.yaml
  examples/v1beta1/nas/enas-example-gpu.yaml
  examples/v1beta1/pytorchjob-example.yaml
  examples/v1beta1/random-example.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/resume-experiment/never-resume.yaml
  examples/v1beta1/tekton/pipeline-run.yaml
  examples/v1beta1/tpe-example.yaml
  examples/v1beta1/trial-metadata-substitution.yaml
  manifests/v1beta1/components/controller/trial-templates.yaml
  operators/katib-controller/src/defaultTrialTemplate.yaml
  operators/katib-controller/src/enasCPUTemplate.yaml
  operators/katib-controller/src/pytorchJobTemplate.yaml
  test/e2e/v1beta1/invalid-experiment.yaml
  test/e2e/v1beta1/run-e2e-experiment.go
  test/e2e/v1beta1/valid-experiment.yaml
Labels: approved, lgtm, size/M

#1473 Add release process script
  Makefile
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  scripts/v1beta1/release.sh
Labels: approved, lgtm, size/L

#1477 fix broken links to kubeflow website
  docs/developer-guide.md
  examples/v1beta1/tekton/README.md
  pkg/ui/v1beta1/README.md
  pkg/ui/v1beta1/frontend/src/components/Menu/Main.jsx
Labels: approved, lgtm, size/S

#1478 Add new UI image to release scripts
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/S

#1480 Remove legacy controller flags from the developer guide
  docs/developer-guide.md
Labels: approved, lgtm, size/S

#1482 Update documentation for SDK Katib Client
  sdk/python/v1beta1/README.md
  sdk/python/v1beta1/docs/KatibClient.md
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: approved, lgtm, size/L

#1485 Update Prow with the latest folder structure
  prow_config.yaml
Labels: approved, lgtm, size/XS

#1481 Update Trial tag to v1beta1-45c5727 in SDK examples
  examples/v1beta1/sdk/README.md
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/sdk/nas-with-darts.ipynb
  sdk/python/v1beta1/README.md
  test/e2e/v1beta1/run-e2e-experiment.go
Labels: approved, lgtm, size/M

#1483 new-ui: Show the Namespace Selector when app is deployed as standalone
  cmd/new-ui/v1beta1/Dockerfile
  pkg/new-ui/v1beta1/README.md
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
Labels: approved, lgtm, size/S

#1476 Manifests for the new UI
  README.md
  docs/images/katib-new-ui.png
Labels: approved, lgtm, size/S

#1487 Add Blog Posts in the README
  README.md
  scripts/update-readme-toc.sh
Labels: approved, lgtm, size/S

#1492 Fix gRPC manager build script
  pkg/apis/manager/health/Makefile
  pkg/apis/manager/health/build.sh
  pkg/apis/manager/health/health.swagger.json
  pkg/apis/manager/v1beta1/Makefile
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/api.swagger.json
  pkg/apis/manager/v1beta1/build.sh
  pkg/apis/manager/v1beta1/python/api_pb2.py
Labels: approved, lgtm, size/XL

#1486 Add Katib webhook documentation
  docs/developer-guide.md
Labels: approved, lgtm, size/M

#1493 Fix release script to replace Katib image tags
  scripts/v1beta1/release.sh
  test/e2e/v1beta1/run-e2e-experiment.go
Labels: approved, lgtm, size/S
