Repository kubeflow/katib, pull requests merged in 2021-01, with the labels that each got.

#1407 Add Github Actions CI for charm operators
  .github/workflows/test-charmed-katib.yaml
  operators/bundle-edge.yaml
Labels: approved, lgtm, size/L

#1402 Fix SDK examples for 0.10 version
  sdk/python/v1beta1/examples/cmaes-and-resume-policies.ipynb
  sdk/python/v1beta1/examples/nas-with-darts.ipynb
Labels: approved, lgtm, size/XL

#1417 Invalid example url
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
Labels: approved, lgtm, ok-to-test, size/XS

#1414 Add SVG logo traced from bitmap logo
  README.md
  docs/images/Katib_Logo.png
  docs/images/logo-title.png
  docs/images/logo-title.svg
  docs/images/logo.png
  docs/images/logo.svg
  operators/katib-controller/icon.svg
  operators/katib-db-manager/icon.svg
  operators/katib-ui/icon.svg
Labels: approved, lgtm, size/M

#1423 Migrate katib to new test-infra
  prow_config.yaml
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: approved, lgtm, size/S
