Repository kubeflow/katib, pull requests merged in 2021-08, with the labels that each got.

#1599 Remove Kubeflow Training dependencies from Katib
  go.mod
  go.sum
  pkg/apis/controller/addtoscheme_pytorchjob_v1.go
  pkg/apis/controller/addtoscheme_tfjob_v1.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/util/job_util.go
  pkg/controller.v1beta1/trial/util/job_util_test.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: approved, lgtm, size/XXL

#1594 fix mysql version in docker image
  manifests/v1beta1/components/mysql/mysql.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1603 Add support for XGBoost Operator with LightGBM example
  README.md
  examples/v1beta1/README.md
  examples/v1beta1/xgboost-lightgbm.yaml
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/controller/rbac.yaml
Labels: approved, lgtm, size/L

#1600 [enh]: validate for bayesian optimization algorithm settings
  pkg/suggestion/v1beta1/skopt/service.py
  test/suggestion/v1beta1/test_skopt_service.py
Labels: approved, lgtm, ok-to-test, size/L

#1605 Add Support for Argo Workflows
  README.md
  docs/new-algorithm-service.md
  docs/presentations.md
  examples/v1beta1/argo/README.md
  examples/v1beta1/argo/argo-workflow.yaml
  examples/v1beta1/nas/darts-cnn-cifar10/architect.py
  examples/v1beta1/tekton/README.md
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/controller/rbac.yaml
Labels: lgtm, approved, size/L

#1609 Remove TFJob and PyTorchJob CRDs from unit tests
  pkg/controller.v1beta1/experiment/experiment_controller_suite_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_suite_test.go
  pkg/controller.v1beta1/trial/trial_controller_suite_test.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  prow_config.yaml
  test/unit/v1beta1/crds/pytorchjob_v1.yaml
  test/unit/v1beta1/crds/tfjob_v1.yaml
Labels: lgtm, approved, size/M

#1610 Upgrade CRDs to apiextensions.k8s.io/v1
  .github/workflows/test-go.yaml
  manifests/v1beta1/components/crd/experiment.yaml
  manifests/v1beta1/components/crd/suggestion.yaml
  manifests/v1beta1/components/crd/trial.yaml
Labels: lgtm, approved, size/L

#1608 Change the default image for the new Katib UI
  README.md
  docs/images/katib-new-ui.png
  docs/images/katib-ui.png
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: lgtm, approved, size/M

#1205 Validate possible operations for Grid suggestion
  pkg/suggestion/v1beta1/chocolate/service.py
  test/suggestion/v1beta1/test_chocolate_service.py
  test/suggestion/v1beta1/test_hyperopt_service.py
  test/suggestion/v1beta1/test_skopt_service.py
  test/suggestion/v1beta1/utils.py
Labels: lgtm, approved, size/L

#1611 Modify Labels for Katib Components
  examples/v1beta1/trial-configmap-source.yaml
  manifests/v1beta1/components/cert-generator/cert-generator.yaml
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/controller/service.yaml
  manifests/v1beta1/components/controller/trial-templates.yaml
  manifests/v1beta1/components/db-manager/db-manager.yaml
  manifests/v1beta1/components/db-manager/service.yaml
  manifests/v1beta1/components/mysql/mysql.yaml
  manifests/v1beta1/components/mysql/service.yaml
  manifests/v1beta1/components/ui/service.yaml
  manifests/v1beta1/components/ui/ui.yaml
  pkg/controller.v1beta1/consts/const.go
Labels: lgtm, approved, size/M

#1615 Add AutoML and Training WG Summit July 2021
  README.md
  docs/presentations.md
Labels: size/XS, lgtm, approved

#1614 Fix Metrics Collector error in case of non-existing Process
  pkg/metricscollector/v1beta1/common/pns.go
  pkg/metricscollector/v1beta1/common/pns.py
Labels: lgtm, approved, size/M

#1621 Modify labels for controller resources
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/util/annotations.go
Labels: lgtm, approved, size/S

#1623 Modify XGBoostJob example for the new Controller
  examples/v1beta1/xgboost-lightgbm.yaml
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/controller/rbac.yaml
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
  pkg/controller.v1beta1/consts/const.go
Labels: lgtm, approved, size/M

#1613 Add Optuna based suggestion service
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/main.py
  cmd/suggestion/optuna/v1beta1/requirements.txt
  examples/v1beta1/multivariate-tpe-example.yaml
  pkg/suggestion/v1beta1/optuna/service.py
  scripts/v1beta1/build.sh
  test/scripts/v1beta1/python-tests.sh
  test/suggestion/v1beta1/test_optuna_service.py
Labels: lgtm, approved, size/XL, ok-to-test

#1625 Add Multivariate TPE to Katib UI
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: lgtm, approved, size/S

#1624 Add Optuna Suggestion to Katib CI
  README.md
  manifests/v1beta1/components/controller/katib-config.yaml
  pkg/suggestion/v1beta1/optuna/service.py
  prow_config.yaml
  scripts/v1beta1/push.sh
  test/scripts/v1beta1/setup-katib.sh
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: lgtm, approved, size/M

#1626 Update Katib UI with Optuna Algorithm Settings
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
  pkg/suggestion/v1beta1/goptuna/converter.go
  pkg/suggestion/v1beta1/optuna/service.py
  test/suggestion/v1beta1/test_optuna_service.py
Labels: lgtm, approved, size/M

#1634 Adding tests in multiple steps
  test/workflows/components/workflows-v1beta1.libsonnet
Labels: size/XS, lgtm, approved

#1633 Reconcile semantics for Suggestion Algorithms
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/suggestion/v1beta1/chocolate/base_service.py
  pkg/suggestion/v1beta1/chocolate/service.py
  test/suggestion/v1beta1/test_chocolate_service.py
Labels: lgtm, approved, size/L

#1629 new-ui: Add devDependency - prettier
  .github/workflows/test-node.yaml
  Makefile
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metadata/metadata.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/details/experiment-details-tab.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/overview/experiment-overview.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph/d3.parcoords.js
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph/trials-graph.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/optimal-trial/utils.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/add-modal/add-modal.component.html
Labels: lgtm, approved, size/XL, ok-to-test

#1630 SDK: change list apis to return objects as default
  hack/gen-python-sdk/post_gen.py
  hack/gen-python-sdk/swagger_config.json
  sdk/python/v1beta1/docs/KatibClient.md
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/models/__init__.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
Labels: lgtm, approved, size/M, ok-to-test

#1642 Update Changelog for Katib 0.12.0-rc.0 release
  CHANGELOG.md
Labels: lgtm, approved, size/M
