Repository kubeflow/katib, pull requests merged in 2021-12, with the labels that each got.

#1704 [Bug Fix - new ui] : Fix bug on list type hp
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/parameter/parameter.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/params-list.component.html
Labels: lgtm, approved, size/M, ok-to-test

#1721 Enhance/UI feasible space
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/add-modal/add-modal.component.html
  pkg/new-ui/v1beta1/frontend/src/app/shared/utils.ts
Labels: lgtm, approved, size/M, ok-to-test

#1743 Fix Status Handling in Charmed Operators
  .github/workflows/test-charmed-katib.yaml
  operators/katib-controller/src/charm.py
  operators/katib-db-manager/src/charm.py
  operators/katib-ui/src/charm.py
Labels: lgtm, approved, size/L

#1755 Fix the default Metrics Collector regex
  pkg/metricscollector/v1beta1/common/const.go
Labels: size/XS, lgtm, approved

#1746 Add Workflow to Publish Katib Images
  .github/workflows/publish-algorithm-images.yaml
  .github/workflows/publish-core-images.yaml
  .github/workflows/publish-trial-images.yaml
  .github/workflows/template-publish-image/action.yaml
Labels: lgtm, approved, size/L

#1759 katib/operators: removes unrecognized keys from metadata.yaml
  operators/katib-controller/metadata.yaml
  operators/katib-db-manager/metadata.yaml
  operators/katib-ui/metadata.yaml
Labels: lgtm, approved, size/S

#1757 Use release tags for Trial images
  Makefile
  docs/images-location.md
  examples/v1beta1/argo/argo-workflow.yaml
  examples/v1beta1/early-stopping/median-stop.yaml
  examples/v1beta1/hp-tuning/bayesian-optimization.yaml
  examples/v1beta1/hp-tuning/cma-es.yaml
  examples/v1beta1/hp-tuning/grid.yaml
  examples/v1beta1/hp-tuning/hyperband.yaml
  examples/v1beta1/hp-tuning/multivariate-tpe.yaml
  examples/v1beta1/hp-tuning/random.yaml
  examples/v1beta1/hp-tuning/sobol.yaml
  examples/v1beta1/hp-tuning/tpe.yaml
  examples/v1beta1/kubeflow-pipelines/early-stopping.ipynb
  examples/v1beta1/kubeflow-training-operator/pytorchjob-mnist.yaml
  examples/v1beta1/metrics-collector/custom-metrics-collector.yaml
  examples/v1beta1/metrics-collector/file-metrics-collector.yaml
  examples/v1beta1/metrics-collector/metrics-collection-strategy.yaml
  examples/v1beta1/nas/darts-cpu.yaml
  examples/v1beta1/nas/darts-gpu.yaml
  examples/v1beta1/nas/enas-cpu.yaml
  examples/v1beta1/nas/enas-gpu.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/resume-experiment/never-resume.yaml
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/sdk/nas-with-darts.ipynb
  examples/v1beta1/tekton/pipeline-run.yaml
  examples/v1beta1/trial-template/trial-metadata-substitution.yaml
  manifests/v1beta1/components/controller/trial-templates.yaml
  operators/katib-controller/src/defaultTrialTemplate.yaml
  operators/katib-controller/src/enasCPUTemplate.yaml
  operators/katib-controller/src/pytorchJobTemplate.yaml
  scripts/v1beta1/release.sh
  scripts/v1beta1/update-images.sh
  scripts/v1beta1/update-trial-images.sh
  test/e2e/v1beta1/invalid-experiment.yaml
  test/e2e/v1beta1/scripts/setup-katib.sh
  test/e2e/v1beta1/valid-experiment.yaml
Labels: lgtm, approved, size/L

#1731 Bump Python version to 3.9
  .github/workflows/publish-trial-images.yaml
  .github/workflows/test-python.yaml
  .gitignore
  Makefile
  cmd/earlystopping/medianstop/v1beta1/Dockerfile
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile.aarch64
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile.ppc64le
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/requirements.txt
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile.aarch64
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/requirements.txt
  docs/developer-guide.md
  docs/images-location.md
  examples/v1beta1/README.md
  examples/v1beta1/kubeflow-training-operator/tfjob-mnist-with-summaries.yaml
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  examples/v1beta1/trial-images/tf-mnist-with-summaries/README.md
  examples/v1beta1/trial-images/tf-mnist-with-summaries/mnist.py
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  pkg/suggestion/v1beta1/nas/enas/Controller.py
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  scripts/v1beta1/update-images.sh
  test/e2e/v1beta1/argo_workflow.py
  test/unit/v1beta1/metricscollector/test_tfevent_metricscollector.py
  test/unit/v1beta1/metricscollector/utils.py
  test/unit/v1beta1/suggestion/test_chocolate_service.py
  test/unit/v1beta1/suggestion/test_enas_service.py
  test/unit/v1beta1/suggestion/utils.py
Labels: lgtm, approved, size/XL
