Repository kubeflow/katib, pull requests merged in 2022-12, with the labels that each got.

#2040 frontend: Make trials table support pagination/sorting/filtering
  pkg/new-ui/v1beta1/frontend/COMMIT
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
Labels: lgtm, approved, size/L

#2042 frontend: Migrate from tslint to eslint in KWA
  .github/workflows/test-node.yaml
  pkg/new-ui/v1beta1/frontend/.eslintrc.json
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-graph/nas-graph.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph-echarts/trials-graph-echarts.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/trial-overview.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/list-input/list-input.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/parameter/parameter.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/params-list.component.ts
Labels: lgtm, size/XXL, approved

#2038 add resources to earlystopping container
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/util/v1beta1/katibconfig/config.go
  pkg/util/v1beta1/katibconfig/config_test.go
Labels: lgtm, approved, size/M

#2047 Add Trial Labels During Pod Mutation
  pkg/controller.v1beta1/consts/const.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
Labels: lgtm, approved, size/M

#2004 [Fix] add early stopped trials in converter
  pkg/apis/controller/trials/v1beta1/util.go
  pkg/controller.v1beta1/experiment/experiment_controller.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/suggestion/v1beta1/internal/trial.py
  pkg/suggestion/v1beta1/skopt/base_service.py
Labels: lgtm, approved, size/L

#2045 Remove Certificate Chain from Cert Generator
  docs/developer-guide.md
  pkg/cert-generator/v1beta1/consts/const.go
  pkg/cert-generator/v1beta1/generate/generate.go
  pkg/cert-generator/v1beta1/generate/generate_test.go
Labels: lgtm, approved, size/L

#2017 frontend: Enable sorting in KWA's main table
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
Labels: size/XS, lgtm, approved

#2048 Add Conformance Program Doc for AutoML and Training WG
  docs/images/conformance-crd-test.png
  docs/proposals/conformance-test.md
Labels: lgtm, approved, size/L

#2050 [SDK] Get Trial Metrics from Katib DB
  sdk/python/v1beta1/.gitignore
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/L

#2056 Update Owners file
  OWNERS
Labels: size/XS, lgtm, approved

#2064 Upgrade the actions-setup-minikube version to v2.7.2
  .github/workflows/template-setup-e2e-test/action.yaml
Labels: size/XS, lgtm, approved

#2070 Pin the NumPy version with v1.23.5 in some images
  cmd/suggestion/skopt/v1beta1/requirements.txt
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/mxnet-mnist/requirements.txt
Labels: lgtm, approved, size/S

#2060 Support for grid search algorithm in Optuna Suggestion Service
  manifests/v1beta1/components/controller/katib-config.yaml
  pkg/suggestion/v1beta1/internal/search_space.py
  pkg/suggestion/v1beta1/optuna/base_service.py
  pkg/suggestion/v1beta1/optuna/service.py
  test/unit/v1beta1/suggestion/test_optuna_service.py
Labels: lgtm, approved, size/L

#2039 Backend for getting logs of a trial
  cmd/new-ui/v1beta1/main.go
  manifests/v1beta1/components/ui/rbac.yaml
  manifests/v1beta1/installs/katib-with-kubeflow/kubeflow-katib-roles.yaml
  pkg/new-ui/v1beta1/backend.go
Labels: lgtm, approved, size/L
