Repository kubeflow/katib, pull requests merged in 2022-09, with the labels that each got.

#1947 Support arm64 in darts-cnn-cifar10 image
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/S

#1948 Support for arm64 in simple-pbt image
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/M

#1950 Update the katib version in docs
  README.md
Labels: size/XS, lgtm, approved

#1953 Drop Kuberenetes v1.21 and introduce Kubernetes v1.24
  .github/workflows/darts-cifar10-e2e-test.yaml
  .github/workflows/enas-cifar10-e2e-test.yaml
  .github/workflows/katib-ui-e2e-test.yaml
  .github/workflows/mxnet-mnist-e2e-test.yaml
  .github/workflows/pytorch-mnist-e2e-test.yaml
  .github/workflows/test-go.yaml
  .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
  Makefile
  README.md
  examples/v1beta1/kind-cluster/README.md
  examples/v1beta1/kind-cluster/deploy.sh
  go.mod
  go.sum
  pkg/client/controller/clientset/versioned/clientset.go
Labels: lgtm, approved, size/L

#1956 Add the CI to build multi-platform container images
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish-algorithm-images.yaml
  .github/workflows/publish-core-images.yaml
  .github/workflows/publish-trial-images.yaml
  .github/workflows/template-e2e-test/action.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
Labels: lgtm, approved, size/L

#1958 Add the license to pbt
  examples/v1beta1/trial-images/simple-pbt/pbt_test.py
Labels: lgtm, approved, size/S

#1966 Improve UI API/controller logging to ease troubleshooting
  pkg/new-ui/v1beta1/hp.go
Labels: size/XS, lgtm, approved
