Repository kubeflow/katib, pull requests merged in 2022-01, with the labels that each got.

#1752 manifests: Upgrade cert-manager API from v1alpha2 to v1
  manifests/v1beta1/installs/katib-cert-manager/certificate.yaml
  manifests/v1beta1/installs/katib-cert-manager/kustomization.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#1712 [new-ui] Bump angular version to 12
  cmd/new-ui/v1beta1/Dockerfile
  pkg/new-ui/v1beta1/README.md
  pkg/new-ui/v1beta1/frontend/.browserslistrc
  pkg/new-ui/v1beta1/frontend/.gitignore
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/e2e/tsconfig.json
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
  pkg/new-ui/v1beta1/frontend/src/app/app-routing.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/app.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/hyper-parameters/hyper-parameters.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metadata/metadata.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-graph/nas-graph.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/nas-operations.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/operation/operation.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/objective/objective.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/objective/objective.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-thresholds/trial-thresholds.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/details/experiment-details-tab.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/overview/experiment-overview.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph/trials-graph.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/optimal-trial/experiment-optimal-trial.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/optimal-trial/experiment-optimal-trial.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/list-input/list-input.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/list-key-value/list-key-value.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/add-modal/add-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/parameter/parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/params-list.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/params-list.module.ts
  pkg/new-ui/v1beta1/frontend/src/environments/environment.ts
  pkg/new-ui/v1beta1/frontend/src/polyfills.ts
  pkg/new-ui/v1beta1/frontend/src/test.ts
  pkg/new-ui/v1beta1/frontend/tsconfig.app.json
  pkg/new-ui/v1beta1/frontend/tsconfig.json
Labels: lgtm, size/XXL, approved, ok-to-test

#1779 Bump `alpine` version to 3.15
  cmd/db-manager/v1beta1/Dockerfile
  cmd/katib-controller/v1beta1/Dockerfile
  cmd/metricscollector/v1beta1/file-metricscollector/Dockerfile
  cmd/new-ui/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/ui/v1beta1/Dockerfile
Labels: lgtm, approved, size/S

#1781 Bump grpc_health_probe version to v0.4.6
  cmd/db-manager/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
Labels: lgtm, approved, size/S

#1786 Fix a link for GRPC API documentation
  pkg/apis/manager/README.md
Labels: size/XS, lgtm, approved

#1791 Add CPU architecture to release scripts
  Makefile
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/M

#1793 Bump Katib Python SDK to 0.13.0rc0 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1797 Update supported Python version for kubeflow-katib SDK
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1798 [cherry-pick] Update supported Python version for kubeflow-katib SDK
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1794 Update Changelog for Katib v0.13.0-rc.0 release
  CHANGELOG.md
Labels: lgtm, approved, size/M
