Repository kubeflow/katib, pull requests merged in 2022-08, with the labels that each got.

#1924 Implement validation for optuna suggestion service
  pkg/suggestion/v1beta1/optuna/base_service.py
  pkg/suggestion/v1beta1/optuna/service.py
  test/unit/v1beta1/suggestion/test_optuna_service.py
Labels: lgtm, approved, size/XL

#1925 [chore] Upgrade Go version to v1.18
  .github/workflows/test-go.yaml
  Makefile
  docs/developer-guide.md
  go.mod
  go.sum
  hack/swagger/main.go
  hack/verify-golangci-lint.sh
  test/e2e/v1beta1/hack/aws/run-e2e-experiment.go
  test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go
Labels: lgtm, approved, size/M

#1926 Implement validations for darts suggestion service
  pkg/suggestion/v1beta1/nas/common/validation.py
  pkg/suggestion/v1beta1/nas/darts/README.md
  pkg/suggestion/v1beta1/nas/darts/service.py
  pkg/suggestion/v1beta1/nas/enas/service.py
  test/unit/v1beta1/suggestion/test_darts_service.py
  test/unit/v1beta1/suggestion/test_enas_service.py
  test/unit/v1beta1/suggestion/test_nas_common.py
Labels: lgtm, approved, size/L

#1931 Update Katib SDK version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1932 Update CHANGELOG for v0.14.0 release
  CHANGELOG.md
Labels: lgtm, approved, size/M

#1933 Update training operator image in CI
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: size/XS, lgtm, approved

#1935 Introduce Automatic platform ARGs
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
  .github/workflows/test-charmed-katib.yaml
  cmd/cert-generator/v1beta1/Dockerfile
  cmd/db-manager/v1beta1/Dockerfile
  cmd/earlystopping/medianstop/v1beta1/Dockerfile
  cmd/katib-controller/v1beta1/Dockerfile
  cmd/metricscollector/v1beta1/file-metricscollector/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/new-ui/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
  cmd/ui/v1beta1/Dockerfile
  docs/developer-guide.md
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
  examples/v1beta1/trial-images/simple-pbt/Dockerfile
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  scripts/v1beta1/build.sh
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
Labels: lgtm, approved, size/L

#1936 Add validation webhooks for maxFailedTrialCount and parallelTrialCount
  .github/workflows/template-setup-e2e-test/action.yaml
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/M

#1937 Add --connect-timeout flag to katib-db-manager
  cmd/db-manager/v1beta1/Dockerfile
  cmd/db-manager/v1beta1/main.go
  docs/developer-guide.md
  pkg/db/v1beta1/common/const.go
  pkg/db/v1beta1/db.go
  pkg/db/v1beta1/mysql/mysql.go
  pkg/db/v1beta1/postgres/postgres.go
Labels: lgtm, approved, size/M

#1942 Upgrade Optuna from v2.x.x to v3.0.0
  cmd/suggestion/optuna/v1beta1/requirements.txt
  pkg/suggestion/v1beta1/optuna/base_service.py
Labels: size/XS, lgtm, approved

#1940 Support for arm64 in mxnet-mnist image
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/mxnet-mnist/install-arm-performance-libraries.sh
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/M

#1943 Support for arm64 in pytorch-mnist image
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/S

#1944 Support for arm64 in enas-cnn-cifar10 image
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/S
