Repository kubeflow/katib, pull requests merged in 2022-05, with the labels that each got.

#1849 Bump kubeflow-katib and kfp version in notebook examples
  README.md
  examples/v1beta1/kubeflow-pipelines/README.md
  examples/v1beta1/kubeflow-pipelines/early-stopping.ipynb
  examples/v1beta1/kubeflow-pipelines/kubeflow-e2e-mnist.ipynb
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/sdk/nas-with-darts.ipynb
Labels: lgtm, approved, size/L

#1867 operators/katib-*: pins pip and setuptools versions to avoid installation issues
  operators/katib-controller/charmcraft.yaml
  operators/katib-db-manager/charmcraft.yaml
  operators/katib-ui/charmcraft.yaml
Labels: size/XS, lgtm, approved

#1866 Fix kubeflowkatib/mxnet-mnist image
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
Labels: size/XS, lgtm, approved

#1865 Update FPGA XGBoost example
  examples/v1beta1/fpga/xgboost-example.yaml
Labels: size/XS, lgtm, approved

#1861 Upgrade the kubebuilder to v3.2.0 and Kubernetes Go libraries to v1.22.2
  .github/workflows/test-go.yaml
  Makefile
  PROJECT
  go.mod
  go.sum
  hack/swagger/main.go
  hack/update-mockgen.sh
  pkg/apis/v1beta1/openapi_generated.go
  pkg/client/controller/clientset/versioned/fake/clientset_generated.go
  pkg/controller.v1beta1/experiment/experiment_controller_suite_test.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_suite_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_suite_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  test/e2e/v1beta1/scripts/setup-katib.sh
Labels: lgtm, approved, size/XL

#1869 Upgrade the Kubernetes Python client to 22.6.0
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
Labels: size/XS, lgtm, approved

#1874 additional metric names should not include objective metric name
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/S, ok-to-test

#1875 Upgrade the grpc_health_probe version to v0.4.11 to resolve security vulnerability CVE-2022-27191
  cmd/db-manager/v1beta1/Dockerfile
  cmd/katib-controller/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
  examples/v1beta1/kubeflow-training-operator/tfjob-mnist-with-summaries.yaml
Labels: lgtm, approved, size/M
