Repository kubeflow/katib, pull requests merged in 2022-02, with the labels that each got.

#1758 Add Kubernetes version to AWS CI
  test/e2e/v1beta1/argo_workflow.py
Labels: size/XS, lgtm, approved

#1804 Add min-juju-version element to operators prevent excess PVC creation
  operators/katib-controller/metadata.yaml
  operators/katib-db-manager/metadata.yaml
  operators/katib-ui/metadata.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#1808 Fix default label for Training Operators
  docs/proposals/metrics-collector.md
  docs/proposals/trial-custom-crd.md
  examples/v1beta1/kubeflow-training-operator/mxjob-byteps.yaml
  pkg/apis/controller/experiments/v1beta1/constants.go
  pkg/ui/v1beta1/frontend/src/reducers/general.js
  test/e2e/v1beta1/argo_workflow.py
  test/e2e/v1beta1/scripts/setup-katib.sh
Labels: lgtm, approved, size/S

#1813 Automated cherry pick of #1808: Fix default label for Training Operators on release-0.13
  docs/proposals/metrics-collector.md
  docs/proposals/trial-custom-crd.md
  examples/v1beta1/kubeflow-training-operator/mxjob-byteps.yaml
  pkg/apis/controller/experiments/v1beta1/constants.go
  pkg/ui/v1beta1/frontend/src/reducers/general.js
  test/e2e/v1beta1/argo_workflow.py
  test/e2e/v1beta1/scripts/setup-katib.sh
Labels: lgtm, approved, size/S

#1814 Bump Katib Python SDK to 0.13.0rc1 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#1815 Update Changelog for Katib v0.13.0-rc.1 release
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#1819 Add more reviewers to Katib OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1822 Fix the Dockerfile for API documentation generation
  pkg/apis/manager/v1beta1/gen-doc/Dockerfile
  pkg/apis/manager/v1beta1/gen-doc/api.md
Labels: lgtm, approved, size/L
