Repository kubeflow/katib, pull requests merged in 2022-10, with the labels that each got.

#1934 [feat] health check for katib-controller
  cmd/katib-controller/v1beta1/main.go
  docs/developer-guide.md
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/controller/service.yaml
  pkg/webhook/v1beta1/webhook.go
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: lgtm, approved, size/M

#1980 [SDK] Remove Final Keyword from constants
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/S

#1981 [SDK] Fix namespace parameter in tune API
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: size/XS, lgtm, approved

#1978 Add the documentation for simple-pbt
  examples/v1beta1/trial-images/simple-pbt/README.md
  examples/v1beta1/trial-images/simple-pbt/pbt_test.py
Labels: lgtm, approved, size/M

#1977 UI: Fix unit tests
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
  pkg/new-ui/v1beta1/frontend/src/app/app.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/app.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/models/trial.k8s.model.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/hyper-parameters/hyper-parameters.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metadata/metadata.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-graph/nas-graph.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/nas-operations.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/operation/operation.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/objective/objective.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-thresholds/trial-thresholds.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/details/experiment-details-tab.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/overview/experiment-overview.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/trial-modal-overview.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/optimal-trial/experiment-optimal-trial.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/list-input/list-input.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/list-key-value/list-key-value.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/add-modal/add-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/parameter/parameter.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/params-list.component.spec.ts
  pkg/new-ui/v1beta1/frontend/tsconfig.json
Labels: lgtm, approved, size/XL

#1982 UI: Make KWA's main table responsive and add toolbar
  cmd/new-ui/v1beta1/Dockerfile
  pkg/new-ui/v1beta1/README.md
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.module.ts
Labels: lgtm, approved, size/M
