Repository kubeflow/katib, pull requests merged in 2022-11, with the labels that each got.

#1987 Use the katib-new-ui for Charmed gh-actions
  .github/workflows/test-charmed-katib.yaml
Labels: size/XS, lgtm, approved

#1995 [chore] Upgrade Go version to v1.19
  Makefile
  cmd/katib-controller/v1beta1/main.go
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  docs/developer-guide.md
  examples/v1beta1/trial-images/simple-pbt/README.md
  go.mod
  hack/verify-golangci-lint.sh
  pkg/client/controller/clientset/versioned/fake/register.go
  pkg/client/controller/clientset/versioned/scheme/register.go
  pkg/metricscollector/v1beta1/common/pns.go
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
  pkg/new-ui/v1beta1/backend.go
  pkg/ui/v1beta1/backend.go
  test/e2e/v1beta1/hack/aws/run-e2e-experiment.go
  test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go
Labels: lgtm, approved, size/M

#1990 [kwa-show-status-first] Show the trials table's status column first
  pkg/new-ui/v1beta1/hp.go
Labels: size/XS, lgtm, approved

#1994 Remove deprecated variable from GRPC definitions
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
Labels: lgtm, approved, size/L

#1996 [chore] Upgrade docker/metadata-action, actions/checkout, and actions/setup-python version
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/darts-cifar10-e2e-test.yaml
  .github/workflows/enas-cifar10-e2e-test.yaml
  .github/workflows/katib-ui-e2e-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/mxnet-mnist-e2e-test.yaml
  .github/workflows/pytorch-mnist-e2e-test.yaml
  .github/workflows/simple-pbt-e2e-test.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/test-charmed-katib.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-node.yaml
  .github/workflows/test-python.yaml
  .github/workflows/test-shell-script.yaml
  .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
Labels: lgtm, approved, size/M

#1997 Support for k8s v1.25 in CI
  .github/workflows/darts-cifar10-e2e-test.yaml
  .github/workflows/enas-cifar10-e2e-test.yaml
  .github/workflows/katib-ui-e2e-test.yaml
  .github/workflows/mxnet-mnist-e2e-test.yaml
  .github/workflows/pytorch-mnist-e2e-test.yaml
  .github/workflows/simple-pbt-e2e-test.yaml
  .github/workflows/test-go.yaml
  .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
  Makefile
  README.md
  examples/v1beta1/kind-cluster/deploy.sh
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#1989 UI: Rename and right align the age column
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
Labels: size/XS, lgtm, approved

#1988 Fix main process retrieve logic for early stopping
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
Labels: size/XS, lgtm, approved

#2009 Add More Katib Presentations 2022
  docs/presentations.md
Labels: lgtm, approved, size/M

#1998 gh-actions: Extend action to run Frontend Unit tests
  .github/workflows/darts-cifar10-e2e-test.yaml
  .github/workflows/enas-cifar10-e2e-test.yaml
  .github/workflows/mxnet-mnist-e2e-test.yaml
  .github/workflows/publish-algorithm-images.yaml
  .github/workflows/publish-core-images.yaml
  .github/workflows/publish-katib-ui-image.yaml
  .github/workflows/publish-trial-images.yaml
  .github/workflows/pytorch-mnist-e2e-test.yaml
  .github/workflows/simple-pbt-e2e-test.yaml
  .github/workflows/test-charmed-katib.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-node.yaml
  .github/workflows/test-python.yaml
  .github/workflows/test-shell-script.yaml
  .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
  pkg/new-ui/v1beta1/frontend/package.json
Labels: lgtm, approved, size/L

#1991 [kwa-kfp-component] Introduce KWA's frontend component for kfp links
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.ts
Labels: lgtm, approved, size/M

#2001 frontend: Fix 500 error after detail page refresh (#1967)
  pkg/new-ui/v1beta1/frontend/src/app/app-routing.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
Labels: lgtm, approved, size/M

#2010 Add CERN to adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#2023 KWA: Use new Editor component (Monaco)
  pkg/new-ui/v1beta1/frontend/COMMIT
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/karma.conf.js
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
  pkg/new-ui/v1beta1/frontend/proxy.conf.json
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/yaml/experiment-yaml.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.spec.ts
Labels: lgtm, approved, size/L

#2027 [bugfix] Fix value passing bug in New Experiment form
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: lgtm, approved, size/M

#1983 Add authorization mechanisms in new Katib UI backend
  cmd/new-ui/v1beta1/main.go
  pkg/controller.v1beta1/consts/const.go
  pkg/new-ui/v1beta1/README.md
  pkg/new-ui/v1beta1/authzn.go
  pkg/new-ui/v1beta1/backend.go
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
  pkg/new-ui/v1beta1/hp.go
  pkg/new-ui/v1beta1/util.go
Labels: lgtm, approved, size/L

#2034 Dedicated yaml tab for Trials
  pkg/new-ui/v1beta1/frontend/src/app/app-routing.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/metrics/metrics.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/metrics/metrics.component.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/metrics/metrics.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/metrics/metrics.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/trial-overview.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/trial-overview.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/trial-overview.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-overview/trial-overview.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-yaml/trial-yaml.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-yaml/trial-yaml.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-yaml/trial-yaml.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-yaml/trial-yaml.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-yaml/trial-yaml.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
Labels: lgtm, approved, size/L
