Repository kubeflow/katib, pull requests merged in 2022-06, with the labels that each got.

#1870 Upgrade the Tensorflow version to address some security issues
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
Labels: lgtm, approved, size/M

#1884 Fix `HAS_SHELLCHECK` and `HAS_SETUP_ENVTEST` in Makefile
  Makefile
Labels: size/XS, lgtm, approved

#1885 Add semicolon when using `command` command in Makefile
  Makefile
  examples/v1beta1/kind-cluster/deploy.sh
  hack/verify-gofmt.sh
  hack/verify-golangci-lint.sh
  hack/verify-shellcheck.sh
Labels: lgtm, approved, size/S

#1886 Fix errors when running the test on Apple Silicon M1
  Makefile
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  go.mod
  go.sum
  pkg/metricscollector/v1beta1/common/pns.go
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
Labels: lgtm, approved, size/M

#1888 chore: Upgrade Go libraries to resolve some security issues in the katib-controller
  Makefile
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  go.mod
  go.sum
  pkg/client/controller/clientset/versioned/clientset.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/common_client.go
  pkg/client/controller/clientset/versioned/typed/experiments/v1beta1/experiments_client.go
  pkg/client/controller/clientset/versioned/typed/experiments/v1beta1/fake/fake_experiment.go
  pkg/client/controller/clientset/versioned/typed/suggestions/v1beta1/fake/fake_suggestion.go
  pkg/client/controller/clientset/versioned/typed/suggestions/v1beta1/suggestions_client.go
  pkg/client/controller/clientset/versioned/typed/trials/v1beta1/fake/fake_trial.go
  pkg/client/controller/clientset/versioned/typed/trials/v1beta1/trials_client.go
  pkg/common/v1beta1/katib_manager_util.go
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/new-ui/v1beta1/backend.go
  pkg/ui/v1beta1/backend.go
  test/unit/v1beta1/requirements.txt
Labels: lgtm, size/XXL, approved

#1877 Include MetricsUnavailable condition to Complete in Trial
  .github/workflows/test-go.yaml
  Makefile
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/controller/experiments/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/controller/trials/v1beta1/util.go
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/experiment/util/status_util.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_util.go
  pkg/controller.v1beta1/trial/util/prometheus_metrics.go
  sdk/python/v1beta1/docs/V1beta1ExperimentStatus.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_experiment_status.py
  test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go
Labels: lgtm, approved, size/XL

#1891 Upgrade tensorflow-aarch64 version to v2.9.1
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
Labels: lgtm, approved, size/S

#1894 Add CyberAgent to adopters
  ADOPTERS.md
Labels: lgtm, approved, size/S

#1897 Upgrade mysql version to v8.0.29
  manifests/v1beta1/components/mysql/mysql.yaml
Labels: size/XS, lgtm, approved

#1833 Population based training
  .github/workflows/publish-algorithm-images.yaml
  .github/workflows/publish-trial-images.yaml
  .github/workflows/simple-pbt-e2e-test.yaml
  Makefile
  README.md
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/main.py
  cmd/suggestion/pbt/v1beta1/requirements.txt
  docs/new-algorithm-service.md
  examples/v1beta1/README.md
  examples/v1beta1/hp-tuning/simple-pbt.yaml
  examples/v1beta1/trial-images/simple-pbt/Dockerfile
  examples/v1beta1/trial-images/simple-pbt/pbt_test.py
  examples/v1beta1/trial-images/simple-pbt/requirements.txt
  manifests/v1beta1/components/controller/katib-config.yaml
  pkg/apis/controller/suggestions/v1beta1/suggestion_types.go
  pkg/apis/controller/suggestions/v1beta1/zz_generated.deepcopy.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/controller/trials/v1beta1/zz_generated.deepcopy.go
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/gen-doc/api.md
  pkg/apis/manager/v1beta1/gen-doc/index.html
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/experiment/experiment_controller_util.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/suggestion/v1beta1/internal/trial.py
  pkg/suggestion/v1beta1/pbt/__init__.py
  pkg/suggestion/v1beta1/pbt/service.py
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  scripts/v1beta1/update-images.sh
  sdk/python/v1beta1/docs/V1beta1TrialAssignment.md
  sdk/python/v1beta1/docs/V1beta1TrialSpec.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_assignment.py
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
  test/e2e/v1beta1/hack/aws/argo_workflow.py
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
Labels: lgtm, size/XXL, approved, ok-to-test

#1901 Linting for K8s YAML files
  .github/workflows/lint.yaml
  Makefile
  hack/verify-yamllint.sh
Labels: lgtm, approved, size/M

#1906 Upgrade Python and Pytorch versions for some examples
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/utils.py
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile
  examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
  hack/verify-yamllint.sh
Labels: lgtm, approved, size/M

#1909 Add PBT to experiment creation form
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
  pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
Labels: lgtm, approved, size/S

#1910 Updating the training operator image in CI
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: size/XS, lgtm, approved

#1911 Fix push script to include new images
  scripts/v1beta1/push.sh
Labels: size/XS, lgtm, approved

#1912 Fix push script to include new images
  scripts/v1beta1/push.sh
Labels: size/XS, lgtm, approved
