Repository kubeflow/katib, pull requests merged in 2023-01, with the labels that each got.

#2071 Remove Chocolate Suggestion Service
  .github/workflows/publish-algorithm-images.yaml
  Makefile
  README.md
  cmd/suggestion/chocolate/v1beta1/Dockerfile
  cmd/suggestion/chocolate/v1beta1/main.py
  cmd/suggestion/chocolate/v1beta1/requirements.txt
  docs/images-location.md
  pkg/suggestion/v1beta1/chocolate/__init__.py
  pkg/suggestion/v1beta1/chocolate/base_service.py
  pkg/suggestion/v1beta1/chocolate/service.py
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  test/e2e/v1beta1/hack/aws/argo_workflow.py
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
  test/unit/v1beta1/suggestion/test_chocolate_service.py
Labels: lgtm, approved, size/XL

#2057 Upgrade Python version to 3.10
  cmd/earlystopping/medianstop/v1beta1/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
  docs/developer-guide.md
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/simple-pbt/Dockerfile
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/M

#2079 Upgrade Tensorflow version
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/S

#2063 frontend: Show message in case of uncompleted trial instead of the graph
  pkg/new-ui/v1beta1/frontend/COMMIT
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
Labels: lgtm, approved, size/M

#2065 frontend: Enable actions in experiment graph
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph-echarts/trials-graph-echarts.component.ts
Labels: size/XS, lgtm, approved

#2075 [SDK] Use Katib SDK for E2E Tests
  .github/workflows/template-e2e-test/action.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/sdk/nas-with-darts.ipynb
  examples/v1beta1/sdk/tune-train-from-func.ipynb
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
  sdk/python/v1beta1/setup.py
  test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.sh
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: lgtm, size/XXL, approved

#2082 Upgrade PyTorch version to v1.13.0
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
  examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
Labels: lgtm, approved, size/M

#2093 Upgrade grpc-health-probe version to fix some security issues
  cmd/db-manager/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
Labels: lgtm, approved, size/S

#2096 Add a --prefer-binary flag to 'pip install' command
  .github/workflows/template-setup-e2e-test/action.yaml
  Makefile
  cmd/earlystopping/medianstop/v1beta1/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile.ppc64le
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
  examples/v1beta1/trial-images/simple-pbt/Dockerfile
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
Labels: lgtm, approved, size/M

#2041 Update manifests to enable authorization check mechanisms for katib-UI in kubeflow mode
  manifests/v1beta1/installs/katib-with-kubeflow/istio-authorizationpolicy.yaml
  manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml
  manifests/v1beta1/installs/katib-with-kubeflow/patches/enable-ui-authz-checks.yaml
  manifests/v1beta1/installs/katib-with-kubeflow/patches/istio-sidecar-injection.yaml
  manifests/v1beta1/installs/katib-with-kubeflow/patches/ui-rbac.yaml
  pkg/new-ui/v1beta1/backend.go
Labels: lgtm, approved, size/M

#2094 Upgrade Go libraries to resolve security issues
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#2098 [SDK] Use Katib Client without Kube Config
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/M

#2091 Narrow down RBAC rules
  examples/v1beta1/argo/README.md
  examples/v1beta1/tekton/README.md
  manifests/v1beta1/components/controller/rbac.yaml
Labels: lgtm, approved, size/M

#2000 More container fields for SuggestionConfig
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/util/v1beta1/katibconfig/config.go
  pkg/util/v1beta1/katibconfig/config_test.go
Labels: lgtm, approved, size/L

#2088 kwa(front): Add UI tests with Cypress
  .github/workflows/test-node.yaml
  pkg/new-ui/v1beta1/frontend/.gitignore
  pkg/new-ui/v1beta1/frontend/README.md
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/cypress.config.ts
  pkg/new-ui/v1beta1/frontend/cypress/e2e/form-page.cy.ts
  pkg/new-ui/v1beta1/frontend/cypress/e2e/index-page.cy.ts
  pkg/new-ui/v1beta1/frontend/cypress/fixtures/experiments.json
  pkg/new-ui/v1beta1/frontend/cypress/fixtures/namespaces.json
  pkg/new-ui/v1beta1/frontend/cypress/fixtures/settings.json
  pkg/new-ui/v1beta1/frontend/cypress/fixtures/trial-template.json
  pkg/new-ui/v1beta1/frontend/cypress/support/commands.ts
  pkg/new-ui/v1beta1/frontend/cypress/support/e2e.ts
  pkg/new-ui/v1beta1/frontend/e2e/protractor.conf.js
  pkg/new-ui/v1beta1/frontend/e2e/src/app.e2e-spec.ts
  pkg/new-ui/v1beta1/frontend/e2e/src/app.po.ts
  pkg/new-ui/v1beta1/frontend/e2e/tsconfig.json
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/package.json
Labels: lgtm, size/XXL, approved

#2089 frontend: Rework the trial graph using ECharts in KWA
  pkg/new-ui/v1beta1/frontend/angular.json
  pkg/new-ui/v1beta1/frontend/package-lock.json
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.module.ts
  pkg/new-ui/v1beta1/frontend/src/assets/css/d3.parcoords.css
Labels: lgtm, approved, size/L

#2090 [kwa-actual-links-in-tables] Make links in KWA's tables actual links
  pkg/new-ui/v1beta1/frontend/COMMIT
  pkg/new-ui/v1beta1/frontend/src/app/models/experiment.model.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
Labels: lgtm, approved, size/L

#2103 Update Training operator Image in CI
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: size/XS, lgtm, approved

#2104 Fix Release Script for Updating SDK Version
  scripts/v1beta1/release.sh
Labels: size/XS, lgtm, approved

#2105 Bump Katib Python SDK to 0.15.0rc0 version
  docs/release/README.md
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved
