Repository kubeflow/katib, pull requests merged in 2023-08, with the labels that each got.

#2188 Allow install binaries for the arm64 in the envtest
  .github/workflows/test-go.yaml
  Makefile
Labels: size/XS, lgtm, approved

#2189 Replace grpc_health_probe with the built-in gRPC container probe feature
  cmd/db-manager/v1beta1/Dockerfile
  cmd/suggestion/goptuna/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/skopt/v1beta1/Dockerfile
  manifests/v1beta1/components/db-manager/db-manager.yaml
  pkg/controller.v1beta1/consts/const.go
  pkg/controller.v1beta1/suggestion/composer/composer.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
Labels: lgtm, approved, size/L

#2190 Upgrade Go version to v1.20
  Makefile
  docs/developer-guide.md
  go.mod
  hack/verify-golangci-lint.sh
  pkg/db/v1beta1/mysql/mysql.go
  pkg/db/v1beta1/mysql/mysql_test.go
  pkg/db/v1beta1/postgres/postgres.go
  pkg/db/v1beta1/postgres/postgres_test.go
Labels: lgtm, approved, size/M

#2195 Default Resume Policy to never from UI
  pkg/ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: size/XS, lgtm, approved

#2185 Consolidate the katib-cert-generator to the katib-controller
  .github/workflows/publish-core-images.yaml
  README.md
  cmd/cert-generator/v1beta1/Dockerfile
  cmd/cert-generator/v1beta1/main.go
  cmd/katib-controller/v1beta1/main.go
  docs/developer-guide.md
  docs/images-location.md
  examples/v1beta1/argo/README.md
  examples/v1beta1/kind-cluster/README.md
  examples/v1beta1/tekton/README.md
  go.mod
  go.sum
  manifests/v1beta1/components/cert-generator/cert-generator.yaml
  manifests/v1beta1/components/cert-generator/kustomization.yaml
  manifests/v1beta1/components/cert-generator/rbac.yaml
  manifests/v1beta1/components/controller/rbac.yaml
  manifests/v1beta1/components/webhook/kustomization.yaml
  manifests/v1beta1/components/webhook/secret.yaml
  manifests/v1beta1/installs/katib-external-db/katib-config.yaml
  manifests/v1beta1/installs/katib-external-db/kustomization.yaml
  manifests/v1beta1/installs/katib-leader-election/katib-config.yaml
  manifests/v1beta1/installs/katib-standalone-postgres/katib-config.yaml
  manifests/v1beta1/installs/katib-standalone-postgres/kustomization.yaml
  manifests/v1beta1/installs/katib-standalone/katib-config.yaml
  manifests/v1beta1/installs/katib-standalone/kustomization.yaml
  pkg/apis/config/v1beta1/defaults.go
  pkg/apis/config/v1beta1/defaults_test.go
  pkg/apis/config/v1beta1/types.go
  pkg/apis/config/v1beta1/zz_generated.deepcopy.go
  pkg/cert-generator/v1beta1/consts/const.go
  pkg/cert-generator/v1beta1/generate/generate.go
  pkg/cert-generator/v1beta1/generate/generate_test.go
  pkg/certgenerator/v1beta1/certificate.go
  pkg/certgenerator/v1beta1/const.go
  pkg/certgenerator/v1beta1/generator.go
  pkg/certgenerator/v1beta1/generator_test.go
  pkg/controller.v1beta1/consts/const.go
  pkg/util/v1beta1/katibconfig/config_test.go
  pkg/webhook/v1beta1/webhook.go
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  test/e2e/v1beta1/hack/aws/argo_workflow.py
  test/e2e/v1beta1/scripts/aws/setup-katib.sh
  test/e2e/v1beta1/scripts/gh-actions/build-load.sh
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: lgtm, size/XXL, approved

#2018 Change failurePolicy to Fail for Katib Webhooks
  manifests/v1beta1/components/webhook/webhooks.yaml
Labels: size/XS, lgtm, approved

#2192 [SDK] Enable resource specification for trial containers
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/M

#2196 Sending an empty data to the certsReady channel
  cmd/katib-controller/v1beta1/main.go
  docs/developer-guide.md
  pkg/certgenerator/v1beta1/generator.go
Labels: lgtm, approved, size/S

#2205 Bump Katib Python SDK to 0.16.0rc0 version
  docs/release/README.md
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/S

#2203 Skip to inject the metrics-collector pods to the katib controller
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/webhook/webhooks.yaml
Labels: lgtm, approved, size/S

#2202 E2E: Add additional checks to verify if the components are ready
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: size/XS, lgtm, approved

#2198 Bug: Wait for the certs to be mounted inside the container
  pkg/certgenerator/v1beta1/generator.go
  pkg/certgenerator/v1beta1/generator_test.go
Labels: lgtm, approved, size/L

#2207 Remove a katib-webhook-cert Secret from components
  manifests/v1beta1/components/webhook/kustomization.yaml
  manifests/v1beta1/components/webhook/secret.yaml
  manifests/v1beta1/installs/katib-external-db/kustomization.yaml
  manifests/v1beta1/installs/katib-standalone-postgres/kustomization.yaml
  manifests/v1beta1/installs/katib-standalone/kustomization.yaml
Labels: lgtm, approved, size/S

#2209 Start waiting for certs to be ready before sending data to the channel
  cmd/katib-controller/v1beta1/main.go
Labels: size/XS, lgtm, approved

#2201 Upgrade Tensorflow version to v2.13.0
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/S

#2211 Automated cherry pick of #2203: Skip to inject the metrics-collector pods to the katib controller
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/webhook/webhooks.yaml
Labels: lgtm, approved, size/S

#2212 Automated cherry pick of #2202: E2E: Add additional checks to verify if the components are ready
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Labels: size/XS, lgtm, approved

#2215 Automated cherry pick of #2209: Start waiting for certs to be ready before sending data to the channel
  cmd/katib-controller/v1beta1/main.go
Labels: size/XS, lgtm, approved

#2216 Automated cherry pick of #2201: Upgrade Tensorflow version to v2.13.0
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/S

#2204 Add Changelog for Katib v0.16.0-rc.0
  CHANGELOG.md
  docs/release/changelog.py
Labels: lgtm, approved, size/L

#2218 Add Changelog for Katib v0.16.0-rc.1
  CHANGELOG.md
Labels: lgtm, approved, size/S

#2219 Use the controller-runtime logger in the cert-generator
  pkg/certgenerator/v1beta1/generator.go
Labels: lgtm, approved, size/S

#2220 Add Stale GitHub Action
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: lgtm, approved, size/M

#2221 Run Stale Action Every 5th Hour
  .github/workflows/stale.yaml
Labels: size/XS, lgtm, approved

#2222 Update Ubuntu to 22.04 for E2E Tests
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-mxnet-mnist.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/stale.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-lint.yaml
  .github/workflows/test-node.yaml
  .github/workflows/test-python.yaml
  examples/v1beta1/trial-images/mxnet-mnist/install-arm-performance-libraries.sh
Labels: lgtm, approved, size/M

#2153 Add Katib ROADMAP 2022/2023
  ROADMAP.md
Labels: lgtm, approved, size/M
