Repository kubeflow/katib, pull requests merged in 2023-04, with the labels that each got.

#2140 Relax dependencies restriction for the gRPC libraries
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  cmd/suggestion/optuna/v1beta1/requirements.txt
  cmd/suggestion/pbt/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/requirements.txt
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/M

#2138 Namespace and trial pod annotations as CLI argument
  examples/v1beta1/hp-tuning/random.yaml
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.sh
Labels: lgtm, approved, size/M

#2146 Containerize tests for katib-conformance
  .github/workflows/publish-conformance-images.yaml
  Dockerfile.conformance
  conformance/run.sh
Labels: lgtm, approved, size/M

#2147 Fix conformance docker image
  Dockerfile.conformance
Labels: size/XS, lgtm, approved

#2148 SDK: Import all Kubernetes Models
  hack/gen-python-sdk/post_gen.py
  sdk/python/v1beta1/kubeflow/katib/models/__init__.py
Labels: lgtm, approved, size/S
