Repository kubeflow/katib, pull requests merged in 2023-02, with the labels that each got.

#2114 Reformat katib-operators
  operators/katib-ui/src/charm.py
Labels: size/XS, lgtm, approved

#2115 Automated cherry pick of #2114: Reformat katib-operators
  operators/katib-ui/src/charm.py
Labels: size/XS, lgtm, approved

#2101 [kwa-trials-logs] Create the LOGS tab of Trial's details page in KWA
  pkg/new-ui/v1beta1/backend.go
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
Labels: lgtm, approved, size/L

#2117 Automated cherry pick of #2101: Create the LOGS tab of Trial's details page in KWA
  pkg/new-ui/v1beta1/backend.go
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.html
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.scss
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
Labels: lgtm, approved, size/L

#2121 Bump Katib Python SDK to 0.15.0rc1 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#2116 UI: Remove an unsed import, EventV1beta1Api
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/operation/operation.component.ts
Labels: size/XS, lgtm, approved

#2113 kwa(front): Update the use of SnackBarService
  pkg/new-ui/v1beta1/frontend/COMMIT
  pkg/new-ui/v1beta1/frontend/src/app/app.module.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Labels: lgtm, approved, size/M

#2106 Add Changelog for Katib v0.15.0-rc.0
  CHANGELOG.md
  docs/release/changelog.py
Labels: lgtm, approved, size/L

#2123 Add Changelog for Katib v0.15.0-rc.1
  CHANGELOG.md
Labels: lgtm, approved, size/S

#2119 kwa(front): Support all namespaces
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/delete-modal-config.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.spec.ts
  pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
  pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
Labels: lgtm, approved, size/L
