Repository kubeflow/katib, pull requests merged in 2024-01, with the labels that each got.

#2251 Install typing-extensions v4.6.3 for Optuna
  Makefile
Labels: size/XS, lgtm, approved

#2250 Add Technical and style guide to the contribution guide
  docs/developer-guide.md
Labels: lgtm, approved, size/S

#2245 DB: Add environment variable option to skip DB table creationˆ
  pkg/db/v1beta1/common/const.go
  pkg/db/v1beta1/mysql/init.go
  pkg/db/v1beta1/postgres/init.go
  pkg/util/v1beta1/env/env.go
Labels: lgtm, approved, size/M
