Repository kubeflow/katib, pull requests merged in 2024-05, with the labels that each got.

#2324 Update outdated actions
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-lint.yaml
  .github/workflows/test-node.yaml
  .github/workflows/test-python.yaml
Labels: lgtm, approved, size/M

#2319 Add Changelog for Katib v0.17.0-rc.0
  CHANGELOG.md
Labels: lgtm, approved, size/M

#2336 Fix Scikit-Learn Version for Skopt Tests
  cmd/suggestion/skopt/v1beta1/requirements.txt
Labels: size/XS, lgtm, approved

#2335 Update GitHub template to better triage Issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: lgtm, approved, size/L

#2330 fix katib use crds token pipeline trail template guide
  examples/v1beta1/tekton/README.md
Labels: lgtm, approved, size/S

#2337 Drop Python 3.7 and Support Python 3.11 in the SDK
  .github/workflows/e2e-test-darts-cifar10.yaml
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved
