Repository kubeflow/katib, pull requests merged in 2024-03, with the labels that each got.

#2267 Remove MXNet examples
  .github/workflows/e2e-test-mxnet-mnist.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/publish-trial-images.yaml
  docs/images-location.md
  examples/v1beta1/README.md
  examples/v1beta1/argo/argo-workflow.yaml
  examples/v1beta1/early-stopping/median-stop.yaml
  examples/v1beta1/hp-tuning/bayesian-optimization.yaml
  examples/v1beta1/hp-tuning/cma-es.yaml
  examples/v1beta1/hp-tuning/grid.yaml
  examples/v1beta1/hp-tuning/hyperband.yaml
  examples/v1beta1/hp-tuning/multivariate-tpe.yaml
  examples/v1beta1/hp-tuning/random.yaml
  examples/v1beta1/hp-tuning/sobol.yaml
  examples/v1beta1/hp-tuning/tpe.yaml
  examples/v1beta1/kind-cluster/README.md
  examples/v1beta1/kubeflow-pipelines/early-stopping.ipynb
  examples/v1beta1/metrics-collector/metrics-collection-strategy.yaml
  examples/v1beta1/resume-experiment/from-volume-resume.yaml
  examples/v1beta1/resume-experiment/long-running-resume.yaml
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/tekton/pipeline-run.yaml
  examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
  examples/v1beta1/trial-images/mxnet-mnist/README.md
  examples/v1beta1/trial-images/mxnet-mnist/common/__init__.py
  examples/v1beta1/trial-images/mxnet-mnist/common/fit.py
  examples/v1beta1/trial-images/mxnet-mnist/common/utils.py
  examples/v1beta1/trial-images/mxnet-mnist/install-arm-performance-libraries.sh
  examples/v1beta1/trial-images/mxnet-mnist/mnist.py
  examples/v1beta1/trial-images/mxnet-mnist/requirements.txt
  examples/v1beta1/trial-images/mxnet-mnist/symbols/__init__.py
  examples/v1beta1/trial-images/mxnet-mnist/symbols/mlp.py
  examples/v1beta1/trial-template/trial-metadata-substitution.yaml
  hack/boilerplate/update-boilerplate.sh
  manifests/v1beta1/components/controller/trial-templates.yaml
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/ui/v1beta1/frontend/cypress/fixtures/trial-template.json
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  scripts/v1beta1/build.sh
  scripts/v1beta1/push.sh
  scripts/v1beta1/update-images.sh
  test/e2e/v1beta1/hack/aws/argo_workflow.py
  test/e2e/v1beta1/testdata/invalid-experiment.yaml
  test/e2e/v1beta1/testdata/valid-experiment.yaml
Labels: lgtm, size/XXL, approved

#2252 Upgrade google/go-containerregistry/pkg/authn/k8schain
  go.mod
  go.sum
Labels: lgtm, size/XXL, approved

#2266 Add environment variable option to set postgres ssl mode
  pkg/db/v1beta1/common/const.go
  pkg/db/v1beta1/postgres/postgres.go
  pkg/db/v1beta1/postgres/postgres_test.go
Labels: lgtm, approved, size/M

#2273 Fix tensor devices for DARTS Trial
  examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
Labels: lgtm, approved, size/S

#2279 Upgrade PyTorch version to v2.2.1
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
  examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/S

#2274 chore: add unit testcases for files in Text format.
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
Labels: lgtm, approved, size/L

#2278 Upgrade Python version to 3.11
  .github/workflows/test-python.yaml
  Makefile
  cmd/earlystopping/medianstop/v1beta1/Dockerfile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
  cmd/suggestion/hyperband/v1beta1/Dockerfile
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/Dockerfile
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/Dockerfile
  cmd/suggestion/nas/enas/v1beta1/Dockerfile
  cmd/suggestion/optuna/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/Dockerfile
  cmd/suggestion/pbt/v1beta1/requirements.txt
  docs/developer-guide.md
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/simple-pbt/Dockerfile
  examples/v1beta1/trial-images/simple-pbt/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
  manifests/v1beta1/installs/katib-cert-manager/katib-config.yaml
  manifests/v1beta1/installs/katib-external-db/katib-config.yaml
  manifests/v1beta1/installs/katib-leader-election/katib-config.yaml
  manifests/v1beta1/installs/katib-openshift/katib-config.yaml
  manifests/v1beta1/installs/katib-standalone-postgres/katib-config.yaml
  manifests/v1beta1/installs/katib-standalone/katib-config.yaml
Labels: lgtm, approved, size/M
