Repository kubeflow/katib, pull requests merged in 2024-07, with the labels that each got.

#2371 [GSoC] New Interface `report_metrics` in Python SDK
  sdk/python/v1beta1/kubeflow/katib/__init__.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
Labels: lgtm, approved, size/L

#2375 Replaced hpcloud with nxadm for tail package in Go
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#2380 Add Changelog for Katib v0.17.0
  CHANGELOG.md
Labels: lgtm, approved, size/M

#2379 Bump Katib Python SDK to 0.17.0 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#2385 Add command to re-run GitHub Actions tests
  .github/workflows/trigger-rerun-test.yaml
Labels: lgtm, approved, size/S

#2387 docs: update suggestion.md
  docs/proposals/suggestion.md
Labels: size/XS, lgtm, approved, ok-to-test

#2382 Update Instructions for Argo Workflows
  examples/v1beta1/argo/README.md
Labels: lgtm, approved, size/S

#2242 Begin enabling pre-commit hooks
  .github/workflows/test-lint.yaml
  .pre-commit-config.yaml
  cmd/earlystopping/medianstop/v1beta1/main.py
  cmd/metricscollector/v1beta1/tfevent-metricscollector/main.py
  cmd/suggestion/hyperband/v1beta1/main.py
  cmd/suggestion/hyperopt/v1beta1/main.py
  cmd/suggestion/nas/darts/v1beta1/main.py
  cmd/suggestion/nas/enas/v1beta1/main.py
  cmd/suggestion/optuna/v1beta1/main.py
  cmd/suggestion/pbt/v1beta1/main.py
  cmd/suggestion/skopt/v1beta1/main.py
  docs/developer-guide.md
  docs/release/changelog.py
  examples/v1beta1/kubeflow-pipelines/mpi-job-horovod.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/model.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/operations.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/search_space.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/op_library.py
  examples/v1beta1/trial-images/pytorch-mnist/mnist.py
  examples/v1beta1/trial-images/simple-pbt/pbt_test.py
  examples/v1beta1/trial-images/tf-mnist-with-summaries/mnist.py
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/metricscollector/v1beta1/common/pns.py
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  pkg/suggestion/v1beta1/hyperband/parsing_util.py
  pkg/suggestion/v1beta1/hyperband/service.py
  pkg/suggestion/v1beta1/hyperopt/base_service.py
  pkg/suggestion/v1beta1/hyperopt/service.py
  pkg/suggestion/v1beta1/internal/search_space.py
  pkg/suggestion/v1beta1/internal/trial.py
  pkg/suggestion/v1beta1/nas/darts/service.py
  pkg/suggestion/v1beta1/nas/enas/Controller.py
  pkg/suggestion/v1beta1/nas/enas/Operation.py
  pkg/suggestion/v1beta1/nas/enas/service.py
  pkg/suggestion/v1beta1/optuna/base_service.py
  pkg/suggestion/v1beta1/optuna/service.py
  pkg/suggestion/v1beta1/pbt/service.py
  pkg/suggestion/v1beta1/skopt/base_service.py
  pkg/suggestion/v1beta1/skopt/service.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
  sdk/python/v1beta1/kubeflow/katib/api/search.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
  sdk/python/v1beta1/setup.py
  test/e2e/v1beta1/hack/aws/argo_workflow.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py
  test/unit/v1beta1/earlystopping/test_medianstop_service.py
  test/unit/v1beta1/metricscollector/test_tfevent_metricscollector.py
  test/unit/v1beta1/metricscollector/utils.py
  test/unit/v1beta1/suggestion/test_darts_service.py
  test/unit/v1beta1/suggestion/test_enas_service.py
  test/unit/v1beta1/suggestion/test_hyperband_service.py
  test/unit/v1beta1/suggestion/test_hyperopt_service.py
  test/unit/v1beta1/suggestion/test_optuna_service.py
  test/unit/v1beta1/suggestion/test_skopt_service.py
Labels: lgtm, approved, size/L

#2369 [GSoC] Add New Parameter in `tune`
  hack/gen-python-sdk/post_gen.py
  pkg/apis/controller/common/v1beta1/common_types.go
  pkg/controller.v1beta1/consts/const.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/L, area/gsoc

#2391 fix: remove the dependency of `protocmp` in `google.golang.org/protobuf/testing/protocmp`.
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
Labels: size/XS, lgtm, approved

#2333 [GSoC] Create LLM Hyperparameters Optimization API Proposal
  docs/proposals/images/design_api.jpg
  docs/proposals/llm-hyperparameter-optimization-api.md
Labels: lgtm, approved, size/L, area/gsoc

#2397 added `Distribution` field to feasibleSpace in `api.proto`
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2.pyi
  sdk/python/v1beta1/kubeflow/katib/__init__.py
Labels: lgtm, size/XXL, approved, area/gsoc

#2377 [GSoC] Added `DistributionType` to Experiment API
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/client/controller/applyconfiguration/experiments/v1beta1/feasiblespace.go
  sdk/python/v1beta1/docs/V1beta1FeasibleSpace.md
  sdk/python/v1beta1/kubeflow/katib/models/v1beta1_feasible_space.py
Labels: lgtm, approved, size/M, area/gsoc

#2334 [GSOC] Support for various Parameter distributions in Katib
  docs/proposals/parameter-distribution.md
Labels: lgtm, approved, size/L, area/gsoc
