Repository kubeflow/katib, pull requests merged in 2024-06, with the labels that each got.

#2342 Fix apple silicon rosetta error when building images from the source code
  docs/developer-guide.md
Labels: size/XS, lgtm, approved

#2349 Update Slack Invitation
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: size/XS, lgtm, approved

#2351 Cherry pick of #2324 #2336 #2337 into release-0.17 branch
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-lint.yaml
  .github/workflows/test-node.yaml
  .github/workflows/test-python.yaml
  cmd/suggestion/skopt/v1beta1/requirements.txt
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/M

#2345 Migrate KatibCertGenerator to OPA CertController
  go.mod
  go.sum
  manifests/v1beta1/components/controller/rbac.yaml
  pkg/certgenerator/v1beta1/certificate.go
  pkg/certgenerator/v1beta1/const.go
  pkg/certgenerator/v1beta1/generator.go
  pkg/certgenerator/v1beta1/generator_test.go
Labels: lgtm, approved, size/XL

#2354 [SDK] Explain Python version support cycle
  sdk/python/v1beta1/README.md
Labels: size/XS, lgtm, approved

#2350 Fix TestReconcileBatchJob
  pkg/controller.v1beta1/trial/trial_controller_test.go
Labels: lgtm, approved, size/L

#2355 Use cache-dependency-path in actions/setup-go for CI workflow
  .github/workflows/test-go.yaml
Labels: size/XS, lgtm, approved

#2357 Replace already closed github.com/golang/mock with go.uber.org/mock
  Makefile
  cmd/db-manager/v1beta1/main_test.go
  go.mod
  go.sum
  hack/update-mockgen.sh
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/mock/v1beta1/api/earlystopping.go
  pkg/mock/v1beta1/api/suggestion.go
  pkg/mock/v1beta1/db/db.go
  pkg/mock/v1beta1/experiment/manifest/generator.go
  pkg/mock/v1beta1/experiment/suggestion/suggestion.go
  pkg/mock/v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/mock/v1beta1/trial/managerclient/katibmanager.go
  pkg/mock/v1beta1/util/katibclient/katibclient.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/L

#2344 Replace gRPC code generation tool from Znly/protoc to Buf
  Makefile
  cmd/metricscollector/v1beta1/tfevent-metricscollector/main.py
  go.mod
  hack/update-proto.sh
  pkg/apis/manager/health/buf.gen.yaml
  pkg/apis/manager/health/build.sh
  pkg/apis/manager/health/health.pb.go
  pkg/apis/manager/health/health.proto
  pkg/apis/manager/health/health_grpc.pb.go
  pkg/apis/manager/health/python/health_pb2.py
  pkg/apis/manager/health/python/health_pb2.pyi
  pkg/apis/manager/health/python/health_pb2_grpc.py
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/api_grpc.pb.go
  pkg/apis/manager/v1beta1/buf.gen.yaml
  pkg/apis/manager/v1beta1/build.sh
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2.pyi
  pkg/apis/manager/v1beta1/python/api_pb2_grpc.py
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
  test/__init__.py
  test/conftest.py
Labels: lgtm, size/XXL, approved

#2358 Upgrade the protobuf version to >=4.21.12,<5
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  cmd/suggestion/optuna/v1beta1/requirements.txt
  cmd/suggestion/pbt/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/requirements.txt
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/S

#2360 [SDK] Fix empty list for env variables and numpy version
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/S

#2362 Cherry pick of #2350 #2355 #2357 #2344 #2358 #2360 into release-0.17 branch
  .github/workflows/test-go.yaml
  Makefile
  cmd/db-manager/v1beta1/main_test.go
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
  cmd/metricscollector/v1beta1/tfevent-metricscollector/main.py
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  cmd/suggestion/optuna/v1beta1/requirements.txt
  cmd/suggestion/pbt/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/requirements.txt
  examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
  examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
  examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
  go.mod
  go.sum
  hack/update-mockgen.sh
  hack/update-proto.sh
  pkg/apis/manager/health/buf.gen.yaml
  pkg/apis/manager/health/build.sh
  pkg/apis/manager/health/health.pb.go
  pkg/apis/manager/health/health.proto
  pkg/apis/manager/health/health_grpc.pb.go
  pkg/apis/manager/health/python/health_pb2.py
  pkg/apis/manager/health/python/health_pb2.pyi
  pkg/apis/manager/health/python/health_pb2_grpc.py
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/api_grpc.pb.go
  pkg/apis/manager/v1beta1/buf.gen.yaml
  pkg/apis/manager/v1beta1/build.sh
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2.pyi
  pkg/apis/manager/v1beta1/python/api_pb2_grpc.py
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
  pkg/mock/v1beta1/api/earlystopping.go
  pkg/mock/v1beta1/api/suggestion.go
  pkg/mock/v1beta1/db/db.go
  pkg/mock/v1beta1/experiment/manifest/generator.go
  pkg/mock/v1beta1/experiment/suggestion/suggestion.go
  pkg/mock/v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/mock/v1beta1/trial/managerclient/katibmanager.go
  pkg/mock/v1beta1/util/katibclient/katibclient.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/setup.py
  test/__init__.py
  test/conftest.py
Labels: lgtm, size/XXL, approved

#2363 Remove code generation from release script
  Makefile
  scripts/v1beta1/release.sh
Labels: size/XS, lgtm, approved

#2325 Add unit test for `create_experiment` in the `katib_client` module
  Makefile
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/constants/constants.py
Labels: lgtm, approved, size/L

#2364 Cherry pick: Remove code generation from release script (#2363)
  Makefile
  scripts/v1beta1/release.sh
Labels: size/XS, lgtm, approved

#2365 Bump Katib Python SDK to 0.17.0rc1 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#2368 Remove default caBundle value
  manifests/v1beta1/components/webhook/webhooks.yaml
Labels: size/XS, lgtm, approved

#2370 Add Changelog for Katib v0.17.0-rc.1
  CHANGELOG.md
Labels: lgtm, approved, size/S

#2329 Use ErrorList for experiment validator
  pkg/webhook/v1beta1/experiment/validation_webhook.go
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/XL

#2328 [GSoC] KEP for Project 6: Push-based Metrics Collection for Katib
  docs/images/push-based-metrics-collection.png
  docs/proposals/push-based-metrics-collection.md
Labels: lgtm, approved, size/L, area/gsoc
