Repository kubeflow/katib, pull requests merged in 2024-08, with the labels that each got.

#2407 Enhance pre-commit hooks with flake8 and black
  .flake8
  .pre-commit-config.yaml
  examples/v1beta1/kubeflow-pipelines/mpi-job-horovod.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/model.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/operations.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/search_space.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/utils.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/op_library.py
  examples/v1beta1/trial-images/pytorch-mnist/mnist.py
  examples/v1beta1/trial-images/tf-mnist-with-summaries/mnist.py
  hack/gen-python-sdk/post_gen.py
  sdk/python/v1beta1/kubeflow/__init__.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
  sdk/python/v1beta1/kubeflow/katib/api/search.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
Labels: lgtm, size/XXL, approved

#2401 [Test] Refactor `inject_webhook_test.go` according to the Developer Guide
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: lgtm, approved, size/L

#2403 [GSOC] added Unknown distribution and convertDistribution in suggestion client
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2.pyi
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
Labels: lgtm, approved, size/L

#2289 Introduced error constants and replaced reflect with cmp
  pkg/controller.v1beta1/experiment/manifest/generator.go
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/trial/util/job_util_test.go
  pkg/suggestion/v1beta1/goptuna/converter_test.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
  pkg/webhook/v1beta1/pod/utils.go
Labels: lgtm, approved, size/XL

#2413 Changes isort profile to black, to be fully compatible and adds 'pkg' dir for black and flake8
  .pre-commit-config.yaml
  cmd/earlystopping/medianstop/v1beta1/main.py
  cmd/metricscollector/v1beta1/tfevent-metricscollector/main.py
  cmd/suggestion/hyperband/v1beta1/main.py
  cmd/suggestion/hyperopt/v1beta1/main.py
  cmd/suggestion/nas/darts/v1beta1/main.py
  cmd/suggestion/nas/enas/v1beta1/main.py
  cmd/suggestion/optuna/v1beta1/main.py
  cmd/suggestion/pbt/v1beta1/main.py
  cmd/suggestion/skopt/v1beta1/main.py
  examples/v1beta1/kubeflow-pipelines/mpi-job-horovod.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/model.py
  examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/op_library.py
  examples/v1beta1/trial-images/pytorch-mnist/mnist.py
  examples/v1beta1/trial-images/tf-mnist-with-summaries/mnist.py
  pkg/earlystopping/v1beta1/medianstop/service.py
  pkg/metricscollector/v1beta1/common/pns.py
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  pkg/suggestion/v1beta1/hyperband/parameter.py
  pkg/suggestion/v1beta1/hyperband/parsing_util.py
  pkg/suggestion/v1beta1/hyperband/service.py
  pkg/suggestion/v1beta1/hyperopt/base_service.py
  pkg/suggestion/v1beta1/hyperopt/service.py
  pkg/suggestion/v1beta1/internal/base_health_service.py
  pkg/suggestion/v1beta1/internal/search_space.py
  pkg/suggestion/v1beta1/internal/trial.py
  pkg/suggestion/v1beta1/nas/common/validation.py
  pkg/suggestion/v1beta1/nas/darts/service.py
  pkg/suggestion/v1beta1/nas/enas/AlgorithmSettings.py
  pkg/suggestion/v1beta1/nas/enas/Controller.py
  pkg/suggestion/v1beta1/nas/enas/Operation.py
  pkg/suggestion/v1beta1/nas/enas/service.py
  pkg/suggestion/v1beta1/optuna/base_service.py
  pkg/suggestion/v1beta1/optuna/service.py
  pkg/suggestion/v1beta1/pbt/service.py
  pkg/suggestion/v1beta1/skopt/base_service.py
  pkg/suggestion/v1beta1/skopt/service.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-tune-api.py
  test/e2e/v1beta1/scripts/gh-actions/verify.py
  test/unit/v1beta1/suggestion/test_darts_service.py
Labels: lgtm, size/XXL, approved

#2398 [SDK] fix grpc related bugs in Python SDK
  Makefile
  hack/gen-python-sdk/post_gen.py
  sdk/python/v1beta1/.gitignore
  sdk/python/v1beta1/kubeflow/katib/__init__.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
  sdk/python/v1beta1/kubeflow/katib/api/report_metrics_test.py
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/L
