Repository kubeflow/katib, pull requests merged in 2024-04, with the labels that each got.

#2272 Python SDK - Generate Name functionality for creating experiments.
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/S

#2297 CI: Enable parallel mode for the coveralls
  .github/workflows/test-go.yaml
Labels: lgtm, approved, size/S

#2282 Upgrade TensorFlow version to v2.16.1
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
  examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
  examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
Labels: lgtm, approved, size/S

#2285 fix: clean up UTs for file metrics collector
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
Labels: lgtm, approved, size/L

#2304 [SDK] Fix env per Trial parameter in tune API
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Labels: lgtm, approved, size/M

#2303 Drop Kubernetes v1.25, and Support Kubernetes v1.28
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/test-go.yaml
  Makefile
  README.md
  cmd/katib-controller/v1beta1/main.go
  examples/v1beta1/kind-cluster/README.md
  examples/v1beta1/kind-cluster/deploy.sh
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/client/controller/clientset/versioned/doc.go
  pkg/client/controller/informers/externalversions/factory.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: lgtm, approved, size/L

#2308 Drop Kubernetes v1.26, and support Kubernetes v1.29
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/test-go.yaml
  Makefile
  README.md
  cmd/katib-controller/v1beta1/main.go
  examples/v1beta1/kind-cluster/README.md
  examples/v1beta1/kind-cluster/deploy.sh
  go.mod
  go.sum
  pkg/apis/config/v1beta1/defaults_test.go
  pkg/apis/v1beta1/openapi_generated.go
  pkg/apis/v1beta1/swagger.json
  pkg/certgenerator/v1beta1/generator_test.go
  pkg/client/controller/informers/externalversions/factory.go
  pkg/controller.v1beta1/suggestion/composer/composer_test.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/util/v1beta1/katibconfig/config_test.go
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/L

#2315 Support ARM64 arch for release images
  Makefile
  docs/developer-guide.md
  docs/release/README.md
  scripts/v1beta1/build.sh
Labels: lgtm, approved, size/M

#2318 Bump Katib Python SDK to 0.17.0rc0 Version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#2316 Make test fields private in Go unit tests
  pkg/controller.v1beta1/experiment/manifest/generator_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
  pkg/webhook/v1beta1/pod/inject_webhook_test.go
Labels: lgtm, size/XXL, approved
