Repository kubeflow/katib, pull requests merged in 2024-10, with the labels that each got.

#2438 Update README and out-of-date docs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/images-location.md
  docs/images/SystemFlow.png
  docs/new-algorithm-service.md
  docs/proposals/1214-custom-crd-in-trial/README.md
  docs/proposals/2044-conformance-program/README.md
  docs/proposals/2044-conformance-program/conformance-crd-test.png
  docs/proposals/2339-hpo-for-llm-fine-tuning/README.md
  docs/proposals/2340-push-based-metrics-collector/README.md
  docs/proposals/2340-push-based-metrics-collector/push-based-metrics-collection.png
  docs/proposals/2374-parameter-distribution/README.md
  docs/proposals/507-suggestion-crd/README.md
  docs/proposals/685-metrics-collector/README.md
  docs/proposals/685-metrics-collector/metrics-collector-design.png
  docs/release/README.md
  docs/workflow-design.md
Labels: lgtm, approved, size/XL

#2439 Promote @Electronic-Waste and @helenxie-bit as Katib reviewers
  OWNERS
  sdk/python/v1beta1/OWNERS
Labels: size/XS, lgtm, approved

#2443 docs: remove katib workflow
  docs/images/katib-workflow.png
  docs/workflow-design.md
Labels: lgtm, approved, size/L, ok-to-test
