Repository kubeflow/katib, pull requests merged in 2025-01, with the labels that each got.

#2472 [DOCS] move llm hyperparameter optimisation design image to the proposal directory and rename it
  docs/proposals/2339-hpo-for-llm-fine-tuning/README.md
  docs/proposals/2339-hpo-for-llm-fine-tuning/hp-optimization-api-design.jpg
Labels: size/XS, lgtm, approved

#2463 Upgrade Kubernetes to v1.30.7
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-tune-api.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/test-go.yaml
  Makefile
  examples/v1beta1/kind-cluster/README.md
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  hack/update-openapigen.sh
  hack/violation_exception_v1beta1.list
  pkg/apis/v1beta1/zz_generated.openapi.go
  pkg/client/controller/applyconfiguration/common/v1beta1/algorithmsetting.go
  pkg/client/controller/applyconfiguration/common/v1beta1/algorithmspec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/collectorspec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/earlystoppingrule.go
  pkg/client/controller/applyconfiguration/common/v1beta1/earlystoppingsetting.go
  pkg/client/controller/applyconfiguration/common/v1beta1/earlystoppingspec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/filesystempath.go
  pkg/client/controller/applyconfiguration/common/v1beta1/filterspec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/metric.go
  pkg/client/controller/applyconfiguration/common/v1beta1/metricscollectorspec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/metricstrategy.go
  pkg/client/controller/applyconfiguration/common/v1beta1/objectivespec.go
  pkg/client/controller/applyconfiguration/common/v1beta1/observation.go
  pkg/client/controller/applyconfiguration/common/v1beta1/parameterassignment.go
  pkg/client/controller/applyconfiguration/common/v1beta1/sourcespec.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/experimentspec.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/optimaltrial.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestionspec.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestionstatus.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/trialassignment.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trialspec.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trialstatus.go
  pkg/client/controller/applyconfiguration/utils.go
  pkg/client/controller/clientset/versioned/clientset.go
  pkg/client/controller/clientset/versioned/fake/clientset_generated.go
  pkg/client/controller/clientset/versioned/fake/register.go
  pkg/client/controller/clientset/versioned/scheme/register.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/common_client.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/doc.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/fake/doc.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/fake/fake_common_client.go
  pkg/client/controller/clientset/versioned/typed/common/v1beta1/generated_expansion.go
  pkg/controller.v1beta1/experiment/experiment_controller.go
  pkg/controller.v1beta1/suggestion/suggestion_controller.go
  pkg/controller.v1beta1/trial/trial_controller.go
  pkg/mock/v1beta1/trial/managerclient/katibmanager.go
  pkg/webhook/v1beta1/experiment/mutate_webhook.go
  pkg/webhook/v1beta1/experiment/validation_webhook.go
  pkg/webhook/v1beta1/pod/inject_webhook.go
Labels: lgtm, size/XXL, approved

#2432 fix(trial): use propagated gomega to improve debuggability.
  pkg/controller.v1beta1/trial/trial_controller_test.go
Labels: lgtm, approved, size/M

#2478 Upgrade Kubernetes to v1.31.3
  .github/workflows/e2e-test-darts-cifar10.yaml
  .github/workflows/e2e-test-enas-cifar10.yaml
  .github/workflows/e2e-test-pytorch-mnist.yaml
  .github/workflows/e2e-test-simple-pbt.yaml
  .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
  .github/workflows/e2e-test-tune-api.yaml
  .github/workflows/e2e-test-ui-random-search-postgres.yaml
  .github/workflows/template-setup-e2e-test/action.yaml
  .github/workflows/test-go.yaml
  Makefile
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  examples/v1beta1/kind-cluster/README.md
  go.mod
  go.sum
  pkg/client/controller/applyconfiguration/experiments/v1beta1/configmapsource.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/experiment.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/experimentcondition.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/experimentspec.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/experimentstatus.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/feasiblespace.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/graphconfig.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/nasconfig.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/operation.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/optimaltrial.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/parameterspec.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/trialparameterspec.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/trialsource.go
  pkg/client/controller/applyconfiguration/experiments/v1beta1/trialtemplate.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestion.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestioncondition.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestionspec.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/suggestionstatus.go
  pkg/client/controller/applyconfiguration/suggestions/v1beta1/trialassignment.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trial.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trialcondition.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trialspec.go
  pkg/client/controller/applyconfiguration/trials/v1beta1/trialstatus.go
  pkg/client/controller/applyconfiguration/utils.go
  pkg/client/controller/clientset/versioned/fake/clientset_generated.go
  pkg/client/controller/clientset/versioned/typed/experiments/v1beta1/experiment.go
  pkg/client/controller/clientset/versioned/typed/experiments/v1beta1/fake/fake_experiment.go
  pkg/client/controller/clientset/versioned/typed/suggestions/v1beta1/fake/fake_suggestion.go
  pkg/client/controller/clientset/versioned/typed/suggestions/v1beta1/suggestion.go
  pkg/client/controller/clientset/versioned/typed/trials/v1beta1/fake/fake_trial.go
  pkg/client/controller/clientset/versioned/typed/trials/v1beta1/trial.go
  pkg/client/controller/informers/externalversions/factory.go
  pkg/client/controller/listers/experiments/v1beta1/experiment.go
  pkg/client/controller/listers/suggestions/v1beta1/suggestion.go
  pkg/client/controller/listers/trials/v1beta1/trial.go
  pkg/common/v1beta1/katib_manager_util.go
  pkg/controller.v1beta1/experiment/experiment_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/trial/trial_controller_test.go
  pkg/ui/v1beta1/backend.go
Labels: lgtm, size/XXL, approved

#2483 Upgrade grpcio version to v1.64.1
  cmd/earlystopping/medianstop/v1beta1/requirements.txt
  cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
  cmd/suggestion/hyperband/v1beta1/requirements.txt
  cmd/suggestion/hyperopt/v1beta1/requirements.txt
  cmd/suggestion/nas/darts/v1beta1/requirements.txt
  cmd/suggestion/nas/enas/v1beta1/requirements.txt
  cmd/suggestion/optuna/v1beta1/requirements.txt
  cmd/suggestion/pbt/v1beta1/requirements.txt
  cmd/suggestion/skopt/v1beta1/requirements.txt
  sdk/python/v1beta1/setup.py
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/S

#2487 Ignore cache exporting errors in the image building workflows
  .github/workflows/template-publish-image/action.yaml
Labels: size/XS, lgtm, approved

#2470 Upgrade klog to v2
  cmd/db-manager/v1beta1/main.go
  cmd/metricscollector/v1beta1/file-metricscollector/main.go
  cmd/suggestion/goptuna/v1beta1/main.go
  go.mod
  go.sum
  hack/swagger/main.go
  pkg/db/v1beta1/common/connection.go
  pkg/db/v1beta1/db.go
  pkg/db/v1beta1/mysql/init.go
  pkg/db/v1beta1/mysql/mysql.go
  pkg/db/v1beta1/postgres/init.go
  pkg/db/v1beta1/postgres/postgres.go
  pkg/metricscollector/v1beta1/common/pns.go
  pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
  pkg/suggestion/v1beta1/goptuna/service.go
Labels: lgtm, approved, size/M, ok-to-test

#2482 fix(api): resolve all api voilation exceptions in katib api
  hack/violation_exception_v1beta1.list
  pkg/apis/controller/common/v1beta1/common_types.go
  pkg/apis/controller/experiments/v1beta1/experiment_types.go
  pkg/apis/controller/suggestions/v1beta1/suggestion_types.go
  pkg/apis/controller/trials/v1beta1/trial_types.go
  pkg/apis/v1beta1/swagger.json
  pkg/apis/v1beta1/zz_generated.openapi.go
Labels: lgtm, approved, size/L, ok-to-test

#2465 chore: supporting the listen-address parameter on db-manager
  CONTRIBUTING.md
  cmd/db-manager/v1beta1/main.go
Labels: lgtm, approved, size/S

#2241 Update MutatingWebhookConfiguration: Switch from objectSelector to AdmissionWebhookMatchConditions
  manifests/v1beta1/components/controller/controller.yaml
  manifests/v1beta1/components/webhook/webhooks.yaml
Labels: lgtm, approved, size/S

#2497 [SDK] Update `tune` API
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/setup.py
Labels: lgtm, approved, size/S

#2423 [GSoC] Add unit tests for `tune` API
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/L

#2498 Sort experiments by descending creation date by default in katib-ui
  pkg/ui/v1beta1/frontend/cypress/e2e/index-page.cy.ts
  pkg/ui/v1beta1/frontend/src/app/pages/experiments/config.ts
Labels: lgtm, approved, size/S

#2496 [SDK] improve PVC creation name error
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
Labels: lgtm, approved, size/S

#2504 Install typing-extensions v4.10.0 to fix Python test error
  Makefile
Labels: size/XS, lgtm, approved

#2412 [GSOC] `hyperopt` suggestion service logic update
  .github/workflows/e2e-test-pytorch-mnist.yaml
  examples/v1beta1/hp-tuning/hyperopt-distribution.yaml
  pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
  pkg/apis/manager/v1beta1/api.pb.go
  pkg/apis/manager/v1beta1/api.proto
  pkg/apis/manager/v1beta1/python/api_pb2.py
  pkg/apis/manager/v1beta1/python/api_pb2.pyi
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
  pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
  pkg/suggestion/v1beta1/hyperopt/base_service.py
  pkg/suggestion/v1beta1/internal/constant.py
  pkg/suggestion/v1beta1/internal/search_space.py
  pkg/webhook/v1beta1/experiment/validator/validator.go
  test/unit/v1beta1/suggestion/test_hyperopt_service.py
Labels: lgtm, approved, size/XL, area/gsoc
