Repository kubeflow/katib, pull requests merged in 2025-03, with the labels that each got.

#2520 [feature] migrate docker images to ghcr
  .github/workflows/build-and-publish-images.yaml
Labels: lgtm, approved, size/M

#2536 Revert GHCR changes for Notebook examples
  examples/v1beta1/kubeflow-pipelines/early-stopping.ipynb
  examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
  examples/v1beta1/sdk/nas-with-darts.ipynb
Labels: lgtm, approved, size/S

#2537 chore(docs): Add Changelog Katib v0.18.0
  CHANGELOG.md
Labels: lgtm, approved, size/L
