Repository kubeflow/katib, pull requests merged in 2025-02, with the labels that each got.

#2505 [CI] optimize katib ui dockerfile
  cmd/ui/v1beta1/Dockerfile
Labels: lgtm, approved, size/S

#2468 Set experiment names at a max of 40 characters.
  pkg/webhook/v1beta1/experiment/validator/validator.go
  pkg/webhook/v1beta1/experiment/validator/validator_test.go
Labels: lgtm, approved, size/S, ok-to-test

#2507 fix(webhook): fix validation message in experiment webhook
  pkg/webhook/v1beta1/experiment/validator/validator.go
Labels: size/XS, lgtm, approved

#2446 [GSOC] `optuna` suggestion service logic update
  .github/workflows/e2e-test-pytorch-mnist.yaml
  examples/v1beta1/hp-tuning/optuna-distribution.yaml
  pkg/suggestion/v1beta1/hyperopt/base_service.py
  pkg/suggestion/v1beta1/optuna/base_service.py
  test/unit/v1beta1/suggestion/test_optuna_service.py
Labels: lgtm, approved, size/L

#2512 [SDK] Support PyTorchJob as a Trial Worker
  .github/workflows/e2e-test-tune-api.yaml
  .gitignore
  hack/gen-python-sdk/post_gen.py
  pkg/apis/v1beta1/swagger.json
  pkg/apis/v1beta1/zz_generated.openapi.go
  sdk/python/v1beta1/kubeflow/katib/__init__.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
  sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
  sdk/python/v1beta1/kubeflow/katib/types/trainer_resources.py
  sdk/python/v1beta1/kubeflow/katib/types/types.py
  sdk/python/v1beta1/kubeflow/katib/utils/utils.py
  sdk/python/v1beta1/setup.py
  test/e2e/v1beta1/scripts/gh-actions/run-e2e-tune-api.py
  test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/XL

#2514 Bump Katib Python SDK to 0.18.0rc0 version
  sdk/python/v1beta1/setup.py
Labels: size/XS, lgtm, approved

#2515 Add Changelog for Katib v0.18.0-rc.0
  CHANGELOG.md
Labels: lgtm, approved, size/L

#2509 Add 'KEP Usage' KEP and template link
  docs/proposals/README.md
Labels: size/XS, lgtm, approved

#2467 Support old-style TensorFlow events (tensorboard)
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  test/unit/v1beta1/metricscollector/test_tfevent_metricscollector.py
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/L

#2517 cherry-picked `c18035e1`
  pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
  test/unit/v1beta1/metricscollector/test_tfevent_metricscollector.py
  test/unit/v1beta1/requirements.txt
Labels: lgtm, approved, size/L
